catalog/nsili/catalog-nsili-source/pom.xml
catalog/nsili/catalog-nsili-transformer/pom.xml
libs/pom.xml
libs/stanag4609/pom.xml
libs/stanag4609/src/main/java/org/codice/alliance/libs/stanag4609/AbstractMetadataPacket.java
libs/stanag4609/src/main/java/org/codice/alliance/libs/stanag4609/AsynchronousMetadataPacket.java
libs/stanag4609/src/main/java/org/codice/alliance/libs/stanag4609/DecodedKLVMetadataPacket.java
libs/stanag4609/src/main/java/org/codice/alliance/libs/stanag4609/Stanag4609TransportStreamParser.java
libs/stanag4609/src/main/java/org/codice/alliance/libs/stanag4609/SynchronousMetadataPacket.java
libs/stanag4609/src/test/java/org/codice/alliance/libs/stanag4609/MetadataPacketTest.java
libs/stanag4609/src/test/java/org/codice/alliance/libs/stanag4609/Stanag4609TransportStreamParserTest.java
pom.xml

- Add libs module
- Add stanag4609 module that provides the ability to extract KLV metadata from MPEG transport streams
- Add junit, hamcrest, and mockito to root pom dependencies
@jaymcnallie @kcwire @bdeining 
Do a full build.
https://codice.atlassian.net/browse/CAL-20
https://codice.atlassian.net/browse/CAL-20

CAL-20 Add capability to extract KLV metadata from MPEG transport streams by the STANAG 4609 standard

---

catalog/imaging/catalog-imaging-transformer/src/main/java/com/connexta/alliance/transformer/nitf/NitfInputTransformer.java
catalog/imaging/catalog-imaging-transformer/src/main/java/com/connexta/alliance/transformer/nitf/NitfPreStoragePlugin.java
catalog/imaging/catalog-imaging-transformer/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/imaging/catalog-imaging-transformer/src/test/java/com/connexta/alliance/transformer/nitf/TestPreStoragePlugin.java

This change adds a pre-storage plugin, moves thumbnail creation there and adds the creation of an overview.
@bdeining (hero)
@kcwire 
@beyelerb 
1) install the alliance-imaging-app
2) ingest a NITF through the UI
3) search for the ingested NITF
4) on the Actions tab, click 'View overview'
--the overview will be shown in a preview pane.
CAL-32, DDF-2025
Added Pre-Storage plugin to extract overview image, store it in the content provider
and add the URI to it to the Metacard.

CAL-32 Add overview image to metacard

---

catalog/imaging/catalog-imaging-transformer/src/test/java/com/connexta/alliance/transformer/nitf/TestPreStoragePlugin.java

Fixes a unit test
@kcwire 
Run the unit tests.
The unit test was failing because it was expecting a specific string value for one of the attribute names.
That name changed in DDF which caused the validation to fail.  Updated the test to rely on the DDF-defined constant value instead of a hard-coded string.
CAL-34
N/A

CAL-34 Fix Unit Tests for NITF transformer pre-storage plugin.

---

catalog/nsili/catalog-nsili-transformer/pom.xml
pom.xml

Adds a Maven variable `project.report.output.directory` so JaCoCo reports go in a properly named folder. Also removes unnecessary JaCoCo configuration in `catalog-nsili-transformer`.
@jlcsmith 
@bdeining 
Build Alliance and confirm that JaCoCo's reports are in the folder `target/site/project-info/jacoco`.
[CAL-35](https://codice.atlassian.net/browse/CAL-35)

CAL-35 Add Maven variable for project report output directory

---

catalog/nsili/catalog-nsili-source/src/main/java/com/connexta/alliance/nsili/source/NsiliSource.java
catalog/nsili/catalog-nsili-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/nsili/catalog-nsili-source/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/nsili/catalog-nsili-transformer/src/main/java/com/connexta/alliance/nsili/transformer/DAGConverter.java
catalog/nsili/catalog-nsili-transformer/src/test/java/com/connexta/alliance/nsili/transformer/TestDAGConverter.java

Allows the NSILI source configuration to specify AccessCriteria fields (user/pass/license key).
Changes queries to only set SortAttributes if the query will return more than 1 result
@jaymcnallie @bdeining @dcruver 
Configure NSILI Federated Source in Admin UI and verify user/pass/license key fields are present.
Build and run JUnit tests
https://codice.atlassian.net/browse/CAL-37

CAL-37: Set AccessCriteria fields in NSILI Source

---

catalog/imaging/catalog-imaging-transformer/src/main/java/com/connexta/alliance/transformer/nitf/NitfInputTransformer.java
catalog/imaging/catalog-imaging-transformer/src/main/java/com/connexta/alliance/transformer/nitf/NitfPreStoragePlugin.java
catalog/imaging/catalog-imaging-transformer/src/test/java/com/connexta/alliance/transformer/nitf/TestPreStoragePlugin.java
catalog/imaging/catalog-imaging-transformer/src/test/java/com/connexta/alliance/transformer/nitf/TestPreStoragePluginMulti.java

Fix a bug in NitfPreStoragePlugin so the plugin only runs on nitf content and so the plugin handles multiple content items.
@dcruver @kcwire @jrnorth @rzwiefel 
1) Upload nitf content (sample content is in catalog/imaging/catalog-imaging-transformer/src/test/resources), verify that the overview is created
2) Upload non-nitif content, if debug logging is enable, there will be an entry: "skipping content item: filename={} mimeType={}"
CAL-38

CAL-38 update NitfStoragePlugin so it only runs on nitf content and multiple content items

---

catalog/nsili/catalog-nsili-common/src/main/java/com/connexta/alliance/nsili/common/NsiliConstants.java
catalog/nsili/catalog-nsili-endpoint/src/main/java/com/connexta/alliance/nsili/endpoint/NsiliWebEndpoint.java
catalog/nsili/catalog-nsili-endpoint/src/test/java/com/connexta/alliance/nsili/endpoint/TestNsiliWebEndpoint.java
catalog/nsili/catalog-nsili-source/src/main/java/com/connexta/alliance/nsili/source/NsiliSource.java
catalog/nsili/catalog-nsili-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/nsili/catalog-nsili-source/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/nsili/catalog-nsili-source/src/test/java/com/connexta/alliance/nsili/source/TestNsiliSource.java
catalog/nsili/catalog-nsili-transformer/pom.xml
catalog/nsili/catalog-nsili-transformer/src/main/java/com/connexta/alliance/nsili/transformer/DAGConverter.java
catalog/nsili/catalog-nsili-transformer/src/test/java/com/connexta/alliance/nsili/transformer/TestDAGConverter.java
distribution/sdk/sample-nsili-server/src/main/java/com/connexta/alliance/nsili/mockserver/client/NsiliClient.java

Updates the NSILI source to get thumbnail bytes when converting DAG to metacards.
Updated the NSILI endpoint to add a newline at the end of the IOR file for NSILI system compatibility.
Changed output charset encoding
@jaymcnallie @bdeining @dcruver 
Run JUnit test cases
https://codice.atlassian.net/browse/CAL-39

CAL-39 : Update NSILI Source to retrieve thumbnails during DAG conversion

---

catalog/nsili/catalog-nsili-endpoint/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/nsili/catalog-nsili-endpoint/src/main/resources/OSGI-INF/metatype/metatype.xml

Updates the NSILI endpoint to start the ORB server when it is created instead of after an admin configures the port.
@troymohl @jaymcnallie @jlcsmith 
Start up Alliance - go through installer - verify https://localhost:8993/services/nsili/ior.txt returns the ior file.
nope
CAL-13

CAL-13 - updated NsiliEndpoint to start ORB server on creation

---

catalog/nsili/catalog-nsili-common/src/main/java/org/codice/alliance/nsili/common/Nsili.java
catalog/nsili/catalog-nsili-source/OpenMap-LICENSE
catalog/nsili/catalog-nsili-source/pom.xml
catalog/nsili/catalog-nsili-source/src/main/java/org/codice/alliance/nsili/source/IOR.java
catalog/nsili/catalog-nsili-source/src/main/java/org/codice/alliance/nsili/source/NsiliSource.java
catalog/nsili/catalog-nsili-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/nsili/catalog-nsili-source/src/main/resources/OSGI-INF/metatype/metatype.xml

Add ability to specify timeout on IOR file retrieval.
Add additional IOR/CORBA debugging for host/port of remote ORB.
@jaymcnallie @bdeining @lcrosenbu @michaelmenousek 
Set logging for NSILI  to DEBUG:  log:set DEBUG org.codice.alliance.nsili
Add NSILI Federated Source
Verify option exists to set timeout for IOR retrieval
Verify that IOR details are logged at debug level
This will provide additional logging to help debug firewall and connectivity problems for STANAG-4559 sources.
The IOR.java file is reused from BBN OpenMap. Checkstyle is configured to ignore it for headers and Jacoco ignores it for unit testing metrics.
https://codice.atlassian.net/browse/CAL-51

CAL-51 Add ability to specify timeout on IOR file retrieval.

---

catalog/video/catalog-mpegts-stream/pom.xml
catalog/video/catalog-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/UdpStreamMonitor.java
catalog/video/catalog-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/netty/StreamProcessor.java
catalog/video/catalog-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/netty/UdpStreamProcessor.java
catalog/video/catalog-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/rollover/CatalogRolloverAction.java
catalog/video/catalog-mpegts-stream/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/video/catalog-mpegts-stream/src/test/java/org/codice/alliance/video/stream/mpegts/rollover/TestCatalogRolloverAction.java

Adds a delay before updating a metacard just after creating a new metacard when ingesting an mpeg-ts udp stream.
@jaymcnallie @jrnorth @rzwiefel @kcwire 
Install alliance with experimental features. Configure an mpeg-ts stream in Alliance Video App.
Start an mpeg-ts udp stream (external). Let me know if you need help. I have a utility program that generates a stream.
Watch the log. When a video chunk is ingested, you should not see stacktraces for each chunk indicating that the metacard update failed.
No unit tests for this.

CAL-43 add a delay before updating a metacard for mpeg-ts udp streams

---

catalog/imaging/catalog-imaging-transformer/pom.xml
catalog/imaging/catalog-imaging-transformer/src/main/java/org/codice/alliance/transformer/nitf/GraphicAttribute.java
catalog/imaging/catalog-imaging-transformer/src/main/java/org/codice/alliance/transformer/nitf/ImageAttribute.java
catalog/imaging/catalog-imaging-transformer/src/main/java/org/codice/alliance/transformer/nitf/LabelAttribute.java
catalog/imaging/catalog-imaging-transformer/src/main/java/org/codice/alliance/transformer/nitf/NitfAttribute.java
catalog/imaging/catalog-imaging-transformer/src/main/java/org/codice/alliance/transformer/nitf/NitfHeaderAttribute.java
catalog/imaging/catalog-imaging-transformer/src/main/java/org/codice/alliance/transformer/nitf/NitfInputTransformer.java
catalog/imaging/catalog-imaging-transformer/src/main/java/org/codice/alliance/transformer/nitf/NitfPreStoragePlugin.java
catalog/imaging/catalog-imaging-transformer/src/main/java/org/codice/alliance/transformer/nitf/SymbolAttribute.java
catalog/imaging/catalog-imaging-transformer/src/main/java/org/codice/alliance/transformer/nitf/TextAttribute.java
catalog/imaging/catalog-imaging-transformer/src/test/java/org/codice/alliance/transformer/nitf/TestNitfInputTransformer.java
catalog/imaging/pom.xml

Updated class and method names as required by imaging-nitf 0.3.  Also changed the nitf-transformer to use the imaginag-nitf fluent API.
@bdeining 
@jlcsmith 
@jaymcnallie 
Ingest a NITF as you would have prior to this change.  The only difference in functionality is that I removed the 'nitf.numberOfImages' attribute.  That attribute won't be part of our taxonomy and it's easy enough to see based on the multi-valued fields.  The value is not easily retrievable in 0.3.
CAL-48
No changes to documentation or tests.

CAL-48 Refactor alliance-imaging to use imaging-nitf 0.3

---

catalog/video/catalog-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/netty/UdpStreamProcessor.java
catalog/video/catalog-mpegts-stream/src/main/resources/OSGI-INF/metatype/metatype.xml

Remove subsample count from metatype. It isn't needed because subsampling is happening in the input transformer after the video chunk is uploaded to ddf.
@jaymcnallie @jrnorth @kcwire @rzwiefel 
Install alliance experimental and confirm that the 'subsample count' field does not appear in the metatype page.
I only removed the metatype field. I didn't strip the subsample count out of the code in case we decide to go back to computing the complete metacard in alliance-mpegts-stream instead of the input transformer.
CAL-46

CAL-46 remove subsample count from metatype admin page 

---

catalog/imaging/catalog-imaging-transformer/src/main/java/org/codice/alliance/transformer/nitf/NitfPreStoragePlugin.java
catalog/imaging/catalog-imaging-transformer/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/imaging/catalog-imaging-transformer/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/imaging/catalog-imaging-transformer/src/test/java/org/codice/alliance/transformer/nitf/TestNitfInputTransformer.java
catalog/imaging/catalog-imaging-transformer/src/test/java/org/codice/alliance/transformer/nitf/TestPreStoragePlugin.java
catalog/imaging/catalog-imaging-transformer/src/test/java/org/codice/alliance/transformer/nitf/TestPreStoragePluginMulti.java

Scales the overview image and added a separate derived resource for the full-scale image.
@bdeining 
@jlcsmith 
@jaymcnallie 
1) ingest a nitf
2) search for the nitf
3) on the actions tab, select 'view overview' and 'view original'
--verify that neither side of the overview is greater than the maximum (1024).
--verify that the overview maintained aspect ratio.
--verify that the original has the same size given on the metacard.
CAL-68

CAL-68 NitfPreStoragePlugin should create a scaled overview image.

---

libs/klv/src/main/java/org/codice/alliance/libs/klv/Stanag4609ProcessorImpl.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/TestStanag4609ProcessorImpl.java
libs/stanag4609/src/main/java/org/codice/alliance/libs/stanag4609/Stanag4609TransportStreamParser.java

KLV data in MPEG-TS videos can have encoded values that indicate an error. KLV entries
that indicate an error should be skipped.
@jrnorth @mweser @kcwire @rzwiefel 
Build and install Alliance Experimental.
Configure a MPEG-TS stream monitor. 
Use the UDP stream generator to transmit the file 1003-GBR-IRL-SIT-H450-clip02-1003_OS.ts.
After the stream has been ingested, check the solr admin page (https://localhost:8993/solr/#/catalog/query) and confirm that the LINESTRINGs in each video chunk do not contain invalid values. Invalid values are -90 -180. 
CAL-50

CAL-50 add KlvDataElement.isErrorIndicated support

---

catalog/nsili/catalog-nsili-common/src/main/java/org/codice/alliance/nsili/common/Nsili.java
catalog/nsili/catalog-nsili-common/src/main/java/org/codice/alliance/nsili/common/NsiliAttributeMap.java
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/LibraryImpl.java
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/NsiliEndpoint.java
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/managers/AccessManagerImpl.java
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/managers/CatalogMgrImpl.java
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/managers/OrderMgrImpl.java
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/managers/ProductMgrImpl.java
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/managers/StandingQueryMgrImpl.java
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/requests/GetParametersRequestImpl.java
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/requests/SubmitQueryRequestImpl.java
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/requests/SubmitStandingQueryRequestImpl.java
catalog/nsili/catalog-nsili-endpoint/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/nsili/catalog-nsili-endpoint/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/TestCatalogMgrImpl.java
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/TestProductMgrImpl.java
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/TestStandingQueryMgrImpl.java
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/TestSubmitStandingQueryRequestImpl.java
catalog/nsili/catalog-nsili-source/src/main/java/org/codice/alliance/nsili/source/NsiliFilterDelegate.java
catalog/nsili/catalog-nsili-source/src/main/java/org/codice/alliance/nsili/source/NsiliFilterFactory.java
catalog/nsili/catalog-nsili-source/src/main/java/org/codice/alliance/nsili/source/NsiliSource.java
catalog/nsili/catalog-nsili-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/nsili/catalog-nsili-source/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/nsili/catalog-nsili-source/src/test/java/org/codice/alliance/nsili/source/TestNsiliFilterDelegate.java
catalog/nsili/catalog-nsili-source/src/test/java/org/codice/alliance/nsili/source/TestNsiliSource.java

Added the ability to specify sources by name on the NSILI Endpoint for restricting enterprise searches
- Added query params to the source that get applied to each outgoing query to that source
- Fixed an issue with setting the port for the endpoint was causing port conflicts with the source
- Resolved 406 issues when attempting self-federation
- Resolved self-federation federated searching problems Self NSILI Source - NSILI Endpoint - External NSIL implementation
@jaymcnallie @bdeining @millerw8 @kcwire 
Run the JUnit tests
https://codice.atlassian.net/browse/CAL-61

CAL-61: Added the ability to specify sources by name on the NSILI Endpoint

---

catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/netty/PacketBuffer.java
catalog/video/video-mpegts-stream/src/test/java/org/codice/alliance/video/stream/mpegts/netty/TestPacketBuffer.java

Add a udp activity timeout so that incomplete framesets get flushed when udp data stops arriving.
@jrnorth @rzwiefel @bdeining @kcwire 
Build Alliance Experimental.
Configure an MPEG-TS stream monitor.
Transmit a udp stream.
After the stream has completed, wait long enough for the last bit of data to get ingested (the wait time should not exceed the rollover timeout condition). Shutdown Alliance. Alliance should not attempt to upload a final video chunk during the shutdown process.
CAL-52

CAL-52 add udp activity timeout

---

catalog/imaging/imaging-actionprovider-chip/.bowerrc
catalog/imaging/imaging-actionprovider-chip/Gruntfile.js
catalog/imaging/imaging-actionprovider-chip/bower.json
catalog/imaging/imaging-actionprovider-chip/package.json
catalog/imaging/imaging-actionprovider-chip/pom.xml
catalog/imaging/imaging-actionprovider-chip/src/main/grunt/tasks/bower.js
catalog/imaging/imaging-actionprovider-chip/src/main/java/org/codice/alliance/imaging/chip/actionprovider/ImagingChipActionProvider.java
catalog/imaging/imaging-actionprovider-chip/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/imaging/imaging-actionprovider-chip/src/main/webapp/chipping.html
catalog/imaging/imaging-actionprovider-chip/src/main/webapp/css/style.css
catalog/imaging/imaging-actionprovider-chip/src/main/webapp/js/chipping.js
catalog/imaging/imaging-actionprovider-chip/src/test/java/org/codice/alliance/imaging/chip/actionprovider/TestImageChipActionProvider.java
catalog/imaging/imaging-app/pom.xml
catalog/imaging/imaging-app/src/main/resources/features.xml
catalog/imaging/pom.xml
pom.xml

This PR adds an Action Page for the Image Chipping Service
@dcruver @glenhein 
@jlcsmith @kcwire 
Build Alliance and Install.  Ingest a NITF that has a Geolocation.  Click the `Chip Image` Action from the Action tab and Chip the image in various ways.
This PR is intended to be used in the new Catalog UI and the Action Page may be too large to be used reasonably in the Search UI.  There is currently a bug in the backend image chipping service that inverts north/south coordinates that is currently being resolved.  
https://codice.atlassian.net/browse/CAL-53
https://codice.atlassian.net/browse/CAL-53

CAL-53 Added Metacard Action for Image Chipping

---

catalog/nsili/catalog-nsili-common/src/main/java/org/codice/alliance/nsili/common/ResultDAGConverter.java
catalog/nsili/catalog-nsili-common/src/test/java/org/codice/alliance/nsili/common/TestResultDAGConverter.java
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/managers/CatalogMgrImpl.java
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/requests/GetParametersRequestImpl.java
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/requests/SubmitQueryRequestImpl.java
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/requests/SubmitStandingQueryRequestImpl.java
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/TestAccessManagerImpl.java
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/TestOrderMgrImpl.java
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/TestProductMgrImpl.java
catalog/nsili/catalog-nsili-transformer/src/main/java/org/codice/alliance/nsili/transformer/DAGConverter.java

Result DAG Converter previously returned all values that were known, which was incorrect as the source system may not have requested every attribute. This changes it to only populate the intersection of requested attributes and attributes that can be populated from resulting data.
@jaymcnallie @kcwire @bdeining @dcruver 
Run the JUnit Tests
This actually affected the Ad-Hoc queries as well as Standing Queries so the bug was expanded to handle both cases.
https://codice.atlassian.net/browse/CAL-56

CAL-56: Updated the Result DAG converter to only export attributes that are requested.

---

catalog/security/alliance-security-app/pom.xml
distribution/test/itests/test-itests-alliance/src/test/java/alliance/test/itests/TestBannerMarkings.java

This change fixes an itest that was broken when the classification format for NATO/COSMIC data was changed and adds a missing header to a pom file.
@stustison @kcwire 
Build/test
N/A
CAL-73
N/A

CAL-73 Create content metadata extractors for common and DoD banner markings.

---

catalog/nsili/catalog-nsili-source/pom.xml
catalog/nsili/catalog-nsili-source/src/main/java/org/codice/alliance/nsili/source/NsiliSource.java
catalog/nsili/catalog-nsili-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/nsili/catalog-nsili-source/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/nsili/catalog-nsili-source/src/test/java/org/codice/alliance/nsili/source/TestNsiliSource.java
distribution/sdk/sample-nsili-server/README.md
distribution/sdk/sample-nsili-server/pom.xml
distribution/sdk/sample-nsili-server/src/main/java/org/codice/alliance/nsili/mockserver/server/MockNsili.java
distribution/test/itests/test-itests-alliance/src/test/java/alliance/test/itests/MockNsiliRunnable.java
distribution/test/itests/test-itests-alliance/src/test/java/alliance/test/itests/TestNsili.java

Adds ability to configure a NSILI source with an FTP URL.
Updates MockNsili to also run an FTP endpoint.
@peterhuffer @troymohl @lcrosenbu @bdeining @jaymcnallie @kcwire 
Verify that TestNsili itest succeeds.
Run the NSILI Mock Server from the command line (see README.md), and configure a NSILI Federated Source or a NSILI Connected Source on the Admin UI with either the http or ftp server URL.
https://codice.atlassian.net/browse/CAL-60

CAL-60: Added ability for NSILI source to get ior string from an FTP URL

---

catalog/imaging/imaging-actionprovider-chip/src/main/java/org/codice/alliance/imaging/chip/actionprovider/ImagingChipActionProvider.java

For backwards compatibility, the ActionProvider interface was restored to its former definition and a new MultiActionProvider interface was added to DDF. This updates ImagingChipActionProvider to implement the new interface.
@pklinef @kcwire @jlcsmith 
Full build and integration tests should affirm this works correctly.
N/A
CAL-88
N/A

CAL-88 Updates ImagingChipActionProvider to correctly implement MultiActionProvider

---

catalog/imaging/imaging-actionprovider-chip/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/imaging/imaging-transformer-nitf/src/main/resources/OSGI-INF/blueprint/blueprint.xml
distribution/test/itests/test-itests-alliance/src/test/java/alliance/test/itests/TestAllianceApps.java
pom.xml

Alliance 0.1 will be released against DDF 2.9.1. Some of the services exported by the `imaging-app` can not be deployed because they were built against upcoming code in DDF 2.10.0. Comment out those services and create an integration test that affirms that all applications can be installed and started.
This additionally fixes an issue with the `imaging-actionprovider-chip` service.
@jlcsmith @kcwire @tbatie 
Full build with itests
N/A
CAL-89
N/A

CAL-89 Prepare Alliance for 0.1 release

---

catalog/nsili/catalog-nsili-common/src/main/java/org/codice/alliance/nsili/common/DagParsingException.java
catalog/nsili/catalog-nsili-common/src/main/java/org/codice/alliance/nsili/common/ResultDAGConverter.java
catalog/nsili/catalog-nsili-common/src/main/java/org/codice/alliance/nsili/common/datamodel/NsiliDataModel.java
catalog/nsili/catalog-nsili-common/src/test/java/org/codice/alliance/nsili/common/TestNsiliDataModel.java
catalog/nsili/catalog-nsili-common/src/test/java/org/codice/alliance/nsili/common/TestResultDAGConverter.java
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/LibraryImpl.java
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/NsiliEndpoint.java
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/managers/CatalogMgrImpl.java
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/managers/ProductMgrImpl.java
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/managers/StandingQueryMgrImpl.java
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/requests/GetParametersRequestImpl.java
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/requests/SubmitQueryRequestImpl.java
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/requests/SubmitStandingQueryRequestImpl.java
catalog/nsili/catalog-nsili-endpoint/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/nsili/catalog-nsili-endpoint/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/TestAccessManagerImpl.java
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/TestOrderMgrImpl.java
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/TestProductMgrImpl.java
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/TestSubmitStandingQueryRequestImpl.java
distribution/sdk/sample-nsili-client/src/main/java/org/codice/alliance/nsili/client/Client.java

CAL-57: ResultDAGConverter option to enforce mandatory nodes.. Can be enabled/disabled via the Admin UI.
@jaymcnallie @jlcsmith @dcruver @bdeining 
Build and run JUnit tests
Depends on CAL-56 being merged 1st, only the CAL-57 commit should be reviewed with this. Both commits are present due to the dependency.
https://codice.atlassian.net/browse/CAL-57

CAL-57 Check that DAG is compliant with Data Model before returning

---

catalog/nsili/catalog-nsili-transformer/pom.xml
catalog/nsili/catalog-nsili-transformer/src/main/java/org/codice/alliance/nsili/transformer/AnyConverter.java
catalog/nsili/catalog-nsili-transformer/src/main/java/org/codice/alliance/nsili/transformer/DAGConverter.java
catalog/nsili/catalog-nsili-transformer/src/test/java/org/codice/alliance/nsili/transformer/TestAnyConverter.java

-The nodes of the original DAG response received from an Nsili source are serialized to XML and added to the metadata field of the Nsili metacards.
@troymohl @bdeining @jlcsmith 
Configure a Nsili Federated Source and do a search. Verify the Metadata field is populated with an XML version of the nodes from the DAG. 
https://codice.atlassian.net/browse/CAL-72

CAL-72: Populates metadata field of Nsili metacards with serialization of the DAG's nodes

---

catalog/nsili/catalog-nsili-endpoint/pom.xml
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/requests/OrderRequestImpl.java
catalog/video/video-mpegts-transformer/src/main/java/org/codice/alliance/transformer/video/MpegTsInputTransformer.java

Change uses of FileBackedOutputStream with TemporaryFileBackedOutputStream.
@jrnorth 
@troymohl 
@kcwire 
@dcruver 
Just run the unit tests.
FBOS will leave temp files behind if not used correctly. TFBOS removes the temp files when the stream is closed.
CAL-76

CAL-76 replaced FileBackedOutputStream with TemporaryFileBackedOutputStream

---

catalog/security/pom.xml
catalog/security/security-app/pom.xml
catalog/security/security-app/src/main/resources/features.xml
distribution/alliance/pom.xml
distribution/alliance/src/main/filtered-resources/etc/org.apache.karaf.features.cfg
distribution/install-profiles/src/main/resources/features.xml
distribution/test/itests/test-itests-alliance/src/test/java/alliance/test/itests/TestAllianceApps.java
distribution/test/itests/test-itests-alliance/src/test/java/alliance/test/itests/TestBannerMarkings.java

This PR removes the alliance prefix from alliance-security-app to match the app conventions of all other apps within Alliance
@coyotesqrl @jlcsmith @lcrosenbu @jrnorth 
Build and run Alliance Experimental, observe all apps start
https://codice.atlassian.net/browse/CAL-100

CAL-100 Removed alliance prefix from alliance-security-app

---

catalog/nsili/catalog-nsili-common/src/main/java/org/codice/alliance/nsili/common/NsiliConstants.java
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/TestAccessManagerImpl.java
catalog/nsili/catalog-nsili-source/src/main/java/org/codice/alliance/nsili/source/NsiliFilterFactory.java
catalog/nsili/catalog-nsili-source/src/test/java/org/codice/alliance/nsili/source/TestNsiliFilterDelegate.java

CAL-99 Updated text searches to only query free text fields within the NSILI data model
Fixes handling of ANY_TEXT to NSILI text fields for queries.
@jaymcnallie @jlcsmith @bdeining @beyelerb 
Run the JUnit test cases
Previously we were passing the ANY_TEXT search criteria to enumerated fields. This could cause problems with systems that only expect those enumerated values to be queried. 
https://codice.atlassian.net/browse/CAL-99

CAL-99 Updated text searches to only query free text fields within the NSILI data model

---

catalog/nsili/catalog-nsili-common/src/main/java/org/codice/alliance/nsili/common/NsiliCbrnAlarmClassification.java
catalog/nsili/catalog-nsili-common/src/main/java/org/codice/alliance/nsili/common/NsiliCbrnEvent.java
catalog/nsili/catalog-nsili-common/src/main/java/org/codice/alliance/nsili/common/NsiliConstants.java
catalog/nsili/catalog-nsili-common/src/main/java/org/codice/alliance/nsili/common/NsiliEntityType.java
catalog/nsili/catalog-nsili-common/src/main/java/org/codice/alliance/nsili/common/NsiliSituationType.java
catalog/nsili/catalog-nsili-common/src/main/java/org/codice/alliance/nsili/common/ResultDAGConverter.java
catalog/nsili/catalog-nsili-common/src/main/java/org/codice/alliance/nsili/common/datamodel/NsiliAttributesGenerator.java
catalog/nsili/catalog-nsili-common/src/main/java/org/codice/alliance/nsili/common/datamodel/NsiliDataModel.java
catalog/nsili/catalog-nsili-common/src/test/java/org/codice/alliance/nsili/common/TestNsiliDataModel.java
catalog/nsili/catalog-nsili-common/src/test/java/org/codice/alliance/nsili/common/TestResultDAGConverter.java
catalog/nsili/catalog-nsili-endpoint/pom.xml
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/TestNsiliEndpoint.java
catalog/nsili/catalog-nsili-orb-impl/src/main/java/org/codice/alliance/nsili/orb/impl/CorbaOrbImpl.java
catalog/nsili/catalog-nsili-transformer/src/main/java/org/codice/alliance/nsili/transformer/DAGConverter.java

CAL-78: NSILI Ed 3 Amendment 2 data model additions
- Added the amendment 2 data model items
- Updated to use advancedGeoSpatial if it's available.
@jaymcnallie @bdeining @beyelerb @jlcsmith 
Run the build with JUnit tests.
This adds the Amendment 2 attributes to the DataModel and maps the advancedGeoSpatial field incoming and outgoing.
https://codice.atlassian.net/browse/CAL-78

CAL-78: NSILI Ed 3 Amendment 2 data model additions

---

catalog/nsili/catalog-nsili-common/pom.xml
catalog/nsili/catalog-nsili-common/src/main/java/org/codice/alliance/nsili/common/BqsConverter.java
catalog/nsili/catalog-nsili-common/src/main/java/org/codice/alliance/nsili/common/CorbaUtils.java
catalog/nsili/catalog-nsili-common/src/main/java/org/codice/alliance/nsili/common/ResultDAGConverter.java
catalog/nsili/catalog-nsili-common/src/test/java/org/codice/alliance/nsili/common/TestBqsConverter.java
catalog/nsili/catalog-nsili-common/src/test/java/org/codice/alliance/nsili/common/TestResultDAGConverter.java
catalog/nsili/catalog-nsili-endpoint/pom.xml
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/LibraryImpl.java
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/managers/CatalogMgrImpl.java
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/requests/SubmitQueryRequestImpl.java
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/requests/SubmitStandingQueryRequestImpl.java
catalog/nsili/catalog-nsili-endpoint/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/TestCatalogMgrImpl.java
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/TestNsiliCommon.java
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/TestSubmitStandingQueryRequestImpl.java
catalog/nsili/catalog-nsili-source/pom.xml
catalog/nsili/catalog-nsili-transformer/src/main/java/org/codice/alliance/nsili/transformer/AnyConverter.java
catalog/nsili/catalog-nsili-transformer/src/main/java/org/codice/alliance/nsili/transformer/DAGConverter.java
catalog/nsili/catalog-nsili-transformer/src/test/java/org/codice/alliance/nsili/transformer/TestDAGConverter.java
distribution/sdk/sample-nsili-client/src/main/java/org/codice/alliance/nsili/client/Client.java
distribution/sdk/sample-nsili-client/src/main/java/org/codice/alliance/nsili/client/NsiliClient.java
distribution/sdk/sample-nsili-server/pom.xml

Correctly populate the NSILI_CARD.status field with actual status from metacard information.
- History data used to populate OBSOLETE records
- Queries updated as well to match NSILI default inclusion of OBSOLETE records.
@jaymcnallie @bdeining @jlcsmith @beyelerb 
Run the JUnit tests.
https://codice.atlassian.net/browse/CAL-64

CAL-64: Correctly populate the NSIL_CARD.status field.

---

distribution/docs/pom.xml
pom.xml

Changes dependency version so docs can build on Oracle JDK on Linux
@ricklarsen @shaundmorris @coyotesqrl 
Docs build successfully

CAL-109: Docs fail to build using Oracle JDK on Linux

---

distribution/alliance/src/main/filtered-resources/etc/org.apache.karaf.features.cfg

Fix for itests breaking with invalid geowebcache-app reference
@bdeining 
@peterhuffer 
@jlcsmith
@pklinef
Run the full build for Alliance including itests.
https://codice.atlassian.net/browse/CAL-114

CAL-114: Fix for itests breaking with invalid geowebcache-app reference

---

catalog/imaging/imaging-transformer-nitf/pom.xml
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/gmti/NitfGmtiTransformer.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/image/ImageMetacardType.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/image/NitfImageTransformer.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/image/NitfPreStoragePlugin.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/TreTestUtility.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/image/TestImageInputTransformer.java
catalog/imaging/pom.xml

- adds support for JPEG2000 images using the Codice fork of the jai-imageio-jpeg2000 library. 
- fixes a bug where the transformer was leaving behind temporary files
- fixes a bug that caused the ingest to fail when the imaging-nitf library couldn't handle the image encoding.
@lcrosenbu 
@roelens8 
@kcwire 
@jlcsmith 
Starting with a clean DDF instance, install the alliance imaging app.  Ingest a JPEG2000 NITF file.  Verify that the thumbnail, overview and original images are generated.
CAL-111
- [x ] Update / Add Unit Tests

CAL-111: Add support for JPEG2000 images.

---

catalog/core/catalog-core-api-impl/src/main/java/org/codice/alliance/catalog/core/api/impl/types/IsrAttributes.java
catalog/core/catalog-core-api/src/main/java/org/codice/alliance/catalog/core/api/types/Isr.java

Adds the tdl-platform attribute to the normalized taxonomy.
@bdeining 
@jlcsmith
@kcwire 
Isr.platform-id is a string being used by other transformers for tail numbers, etc. This attribute is intended to map the platform ID from the data link.
https://codice.atlassian.net/browse/CAL-93

CAL-93: Updated Alliance Taxonomy to include isr.tdl-platform

---

catalog/plugin/catalog-plugin-defaultsecurityattributevalues/pom.xml

fix an issue with catalog-core-api-impl not getting embedded when a snapshot was downloaded from nexus
@adimka @tbatie 
@coyotesqrl
@jlcsmith
build alliance with a new .m2  mvn clean install -Dmaven.repo.local=/tmp/.m2 then jar -tvf catalog-plugin-defaultsecurityattributevalues.jar and verify two catalog-core-api-impl jars are embedded

CAL-104 fix embedded dependency not always being embedded

---

catalog/nsili/catalog-nsili-orb-impl/src/main/java/org/codice/alliance/nsili/orb/impl/CorbaOrbImpl.java
catalog/nsili/catalog-nsili-orb-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/nsili/catalog-nsili-orb-impl/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/nsili/catalog-nsili-orb-impl/src/test/java/org/codice/alliance/nsili/orb/impl/TestCorbaOrbImpl.java
distribution/alliance/pom.xml
distribution/docs/src/main/resources/_contents/_tables/org.codice.alliance.nsili.orb.impl.corbaorb-table-contents.adoc
distribution/test/itests/test-itests-alliance/src/test/java/alliance/test/itests/TestNsili.java

This PR refactors the default port for the NSILI endpoint so that it is configurable in system.properties. The NSILI endpoint default port in TestNsili itest is now set to a DynamicPort.
@lcrosenbu @mweser @peterhuffer @glenhein @troymohl 
@stustison 
@kcwire 
1. Ensure that the TestCorbaOrbImpl and TestNsili tests pass.
2. Confirm that the NSILI endpoint port number is configurable in system.properties:
1. Build Alliance.
2. Change ` org.codice.alliance.corba_default_port ` in $ALLIANCE_HOME/etc/system.properties file to a new port.
3. Start DDF.
4. Confirm that the default port number for the NSILI endpoint is now the new port that you set in the system.properties file, indicated by the debug log entry "Successfully initialized CORBA orb on port: [port number]".
5. Confirm that …

CAL-117 Refactored the NSILI endpoint default port to be configurable in system.properties

---

catalog/imaging/imaging-actionprovider-chip/pom.xml
catalog/imaging/imaging-actionprovider-chip/src/main/java/org/codice/alliance/imaging/chip/actionprovider/ImagingChipActionProvider.java
catalog/imaging/imaging-actionprovider-chip/src/test/java/org/codice/alliance/imaging/chip/actionprovider/TestImageChipActionProvider.java
catalog/imaging/imaging-transformer-chipping/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/imaging/imaging-transformer-nitf/pom.xml
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/MetacardFactory.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/SegmentHandler.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/image/NitfPreStoragePlugin.java
catalog/imaging/imaging-transformer-nitf/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/TestMetacardFactory.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/TreTestUtility.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/gmti/TestNitfGmtiTransformer.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/image/TestImageInputTransformer.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/image/TestPreStoragePlugin.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/image/TestPreStoragePluginMulti.java

Fixed image chipping action provider that was recently broken. This PR restores the generation of the original image, which is required for the image chipping function. Additionally, this removes the extra `Export as overview-chip` option from the Actions tab.
@dcruver 
@bdeining 
@emmberk 
@jlcsmith
@coyotesqrl 
1. Build/run alliance.
2. Ingest Image NITF.
3. Perform search to retrieve ingested NITF.
4. Verify the "Export as overview-chip" option is no longer available. 
5. Verify "Chip Image" function is present under Actions and works.
6. Additionally, ingest GMTI NITF to ensure "Chip Image" is not available in Actions list.
Dependent on PR https://github.com/codice/ddf/pull/1173.
https://codice.atlassian.net/browse/CAL-119
N/A

CAL-119 Restored image chipping action

---

catalog/security/banner-marking/pom.xml
pom.xml

Uses shaded jar and moves gmaven-plus plugin to root pom.
Dependent upon DDF-2426
@tbatie @dcruver 
@coyotesqrl
@jlcsmith
A full build with unit tests should be sufficient. Compilation errors would indicate issues with the shaded jar; coverage errors would indicate that the gmaven-plus plugin was not correctly being invoked.
N/A
CAL-122, DDF-2426
N/A

CAL-122 Uses Spock shaded jar and moves gmaven-plus plugin to root pom.

---

catalog/video/video-admin-plugin/src/main/webapp/js/view/StreamMonitor.view.js
catalog/video/video-mpegts-transformer/src/main/resources/OSGI-INF/metatype/metatype.xml

Corrects the tooltips for the maximum clip duration and maximum clip size fields in the admin stream monitor UI.
@glenhein 
@bdeining 
@jlcsmith
@kcwire
Install the video app, configure a new stream monitor, and verify that the tooltips for the maximum clip duration and maximum clip size are correct.
[CAL-42](https://codice.atlassian.net/browse/CAL-42)

CAL-42 Fix the admin stream monitor rollover tooltips

---

.gitignore
pom.xml

* Adds javadocs to release profile
* Adds sources to the release profile
* Ensures release profile is triggered during release
* Adds additional gitignores for maven
@pklinef
@shaundmorris
* Run `mvn release:prepare -Dmaven.repo.local=/tmp/m2` this should create javadoc and source jars for all artifacts
Previously javadoc and source jars were not created automatically during a release
[CAL-129](https://codice.atlassian.net/browse/CAL-129)

CAL-129: Added javadoc and source jars to release

---

catalog/core/catalog-core-api/src/main/java/org/codice/alliance/catalog/core/api/types/Isr.java
catalog/core/catalog-core-api/src/main/java/org/codice/alliance/catalog/core/api/types/Security.java
catalog/imaging/imaging-service-api/src/main/java/org/codice/alliance/imaging/chip/service/api/ChipService.java
catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/UdpStreamMonitor.java
catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/netty/PacketBuffer.java
catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/netty/UdpStreamProcessor.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/LocationKlvProcessor.java
pom.xml

Javadoc was failing due to invalid javadoc markup which was causing the release process to fail
* Fixed invalid html formatting
* Fixed invalid usage of greater-than and less-than
* Disabled doclint for missing annotations
@troymohl 
@kcwire
@lessarderic 
Run `mvn javadoc:javadoc` and ensure it completes successfully
[CAL-129](https://codice.atlassian.net/browse/CAL-129)

CAL-129: Cleaned up javadoc formatting

---

catalog/imaging/imaging-transformer-nitf/pom.xml
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/AcftbAttribute.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/NitfHeaderTransformer.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/SegmentHandler.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/TreDescriptor.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/TreUtility.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/gmti/IndexedMtirpbAttribute.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/gmti/MtirpbAttribute.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/gmti/NitfGmtiTransformer.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/image/NitfImageTransformer.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/AcftbAttributeTest.java

-Adds the capability to parse TREs when adding TRE attributes as instance fields into the enum TreDescriptor.java
-Parses TREs from both the nitf header and image segment.
@dcruver @jaymcnallie
Ingest a NITF with a TRE and verify that the metacard was populated with the fields from the NITF and its TREs.
CAL-79

CAL-79 Improve support for parsing TREs from NITFs

---

distribution/alliance/src/main/filtered-resources/etc/org.codice.ddf.admin.applicationlist.properties

This PR adds a missing file to the Alliance distribution that was causing warnings when using the configuration export functionality.
@lcrosenbu @jrnorth 
@jlcsmith
@stustison 
Build and install Alliance, export the configurations and observe no warnings
https://codice.atlassian.net/browse/CAL-140

CAL-140 Added missing org.codice.ddf.admin.applicationlist.properties

---

catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/SubmitStandingQueryRequestImplTest.java
catalog/nsili/catalog-nsili-sourcestoquery-ui/pom.xml
catalog/transformer/catalog-transformer-mgmp/pom.xml
distribution/test/itests/test-itests-common/pom.xml
pom.xml
support/support-checkstyle/pom.xml

- Add `argLine` parameter to surefire plugin in root pom
- Adjust jacoco coverage numbers for failing bundles
@bdeining @troymohl 
@coyotesqrl
@jlcsmith 
A full build
Jacoco coverage numbers were being ignored.
https://codice.atlassian.net/browse/CAL-141

CAL-141: Add argLine parameter to surefire plugin

---

catalog/imaging/imaging-transformer-nitf/pom.xml
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/AbstractNitfMetacardType.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/ExtNitfUtility.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/AcftbAttribute.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/NitfAttribute.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/NitfHeaderAttribute.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/SegmentHandler.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/gmti/GmtiMetacardType.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/gmti/IndexedMtirpbAttribute.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/gmti/MtirpbAttribute.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/gmti/NitfGmtiTransformer.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/image/GraphicAttribute.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/image/ImageAttribute.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/image/ImageMetacardType.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/image/LabelAttribute.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/image/NitfImageTransformer.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/image/SymbolAttribute.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/image/TextAttribute.java
catalog/imaging/imaging-transformer-nitf/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/gmti/NitfGmtiTransformerTest.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/image/ImageAttributeTest.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/image/ImageInputTransformerTest.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/image/TestTextAttribute.java

- Adds all previously available NITF attributes (and current supported TREs fields) into both Image and GMTI NITF `MetacardType`s under the `ext.nitf.*` namespace.
- NITF Attributes that also map to the taxonomy are duplicated in the `Metacard`. This is so that Imagery Analysts can operate on the `Metacard`'s attributes with terms they are familiar with.
- Removes `MtirpbAttribute.AIRCRAFT_LOCATION` -> `Isr.DWELL_LOCATION` taxonomy mapping.
@dcruver @lcrosenbu @bdeining @glenhein 
@jlcsmith 
@pklinef
Full build
Start an instance of Alliance and ingest some NITFs, verify that attributes are visible in the `Metacard` view in the UI as well as in the `Metacard` XML representation.
Some NITF specific fields that Imagery Analysts want, in order to perform operations against, do not map to the …

CAL-131: Add all Nitf attributes into Nitf metacard types

---

catalog/nsili/catalog-nsili-common/src/test/java/org/codice/alliance/nsili/common/TestBqsConverter.java

Removes an unused logger and mistakenly imported sun's logger.
@coyotesqrl
@shaundmorris
Full build successfully

CAL-14: Removed unused logger (Backport)

---

distribution/sdk/sample-mpegts-streamgenerator/pom.xml
distribution/sdk/sample-mpegts-streamgenerator/src/main/java/org/codice/alliance/distribution/sdk/video/stream/mpegts/MpegTsUdpClient.java

This PR sets the log level to trace for the MpegTsUdpClient so valuable information can be seen 
@troymohl 
@coyotesqrl
@jlcsmith
Run the sample-mpegts-generator maven profile (see README).

CAL-164 Set the log level to trace in the MpegTsUdpClient

---

catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/NitfParserAdapter.java
catalog/imaging/imaging-transformer-nitf/src/main/resources/OSGI-INF/blueprint/blueprint.xml

This change adds a call to NitfSegmentsFlow.end() at either end of the camel
route. This will delete the temporary files that are created as part of the
NITF ingest process.
@roelens8 
@rzwiefel 
@beyelerb
@jaymcnallie 
1) verify that there are no files in ${DDF_HOME}/data/tmp with names that start with 'nitf'.
2) start DDF
3) ingest any nitf file
4) repeat step 1
- temporary files should be created during ingest, but removed after ingest is complete.
On Windows, this test will only succeed when using an imaging-nitf build that includes IMG-191.  On Mac or Linux, the test should succeed with or without IMG-191.
CAL-148, IMG-191

CAL-148 imaging-transformer-nitf doesn't clean up temporary files

---

distribution/alliance/pom.xml

Updates `distribution/alliance/pom.xml` to allow skipping documentation on quick development builds.
@AzGoalie @harrison-tarr 
@jaymcnallie
@jlcsmith
successful build with documentation enabled
successful build with documentation disabled
https://codice.atlassian.net/browse/CAL-152

CAL-152 Moved docs to profile to enable excluded docs

---

distribution/test/itests/test-itests-alliance/src/test/java/org/codice/alliance/test/itests/FederationTest.java

Fixes the OpenSearch initialization during FederationTest so that the test will completely correctly now that errors are no longer ignored. 
@bdeining 
@coyotesqrl
@kcwire
Run the FederationTest integration test and verify it passes.
This will fix the build failure on: 
https://codice.atlassian.net/builds/browse/AL-AL-414/log
https://codice.atlassian.net/browse/CAL-170

CAL-170: Updated OpenSearch initialization to be correct so that the source starts correctly.

---

catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/image/ImageAttribute.java

The imageMagnification attribute of a nitf metacard was previously being assigned values of multiple types. This change uses the ImageSegment method to ensure a single double value is returned as described by the NGA NITF requirements document. 
@peterhuffer @dcruver @clockard 
@jaymcnallie
@jlcsmith
@kcwire 
Review the change. Build.
CAL-131: Add all Nitf attributes into Nitf metacard types

CAL-131 Updated Image Magnification to only set a double as per the Nitf Spec

---

libs/klv/pom.xml
libs/klv/src/main/java/org/codice/alliance/libs/klv/CopyPresentKlvProcessor.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/DistinctKlvProcessor.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/DistinctSingleKlvProcessor.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/UnionKlvProcessor.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/Utilities.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/CopyPresentKlvProcessorTest.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/KlvUtilities.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/UtilitiesTest.java

Provides the **second** part of a two-part fix to allow certain cases of mpegts video clips to ingest without error.
Adds static utility methods for sanitizing calls to `metacard::setAttribute` to prevent unexpected, deserialized types from KLV data. Relevant implementations of `KlvProcessor` defer to these utility methods instead of setting attributes themselves. 
@glenhein 
@bdeining 
@jrnorth 
@jlcsmith
@kcwire
In conjunction with [DDF PR 1360](https://github.com/codice/ddf/pull/1360); ingest video products, both good ones and some with bad packets (unexpected packet length - not necessarily corrupt data), and ensure the products successfully ingest and appear during search. Since security markings might be ignored, be sure to login to a profile that has access to system high. 
Also, a …

CAL-162: KlvProcessor impls no longer add attributes if the type does not match

---

catalog/imaging/imaging-transformer-nitf/pom.xml
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/image/ImageAttribute.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/image/TestImageInputTransformer.java

Backport of CAL-131 https://github.com/codice/alliance/pull/166
@peterhuffer @clockard 
@kcwire
@shaundmorris

CAL-131 0.1.x Backport - Updated Image Magnification to only set a double as per the NITF spec

---

catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/PiaimcAttribute.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/gmti/GmtiMetacardType.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/image/ImageMetacardType.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/common/PiaimcAttributeTest.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/image/ImageInputTransformerTest.java

CAL-134: Mapping of PIAIMC attributes to ext.nitf.\* fields.
@glenhein 
@bdeining
@peterhuffer
@kcwire
@lessarderic
Run complete build with tests.
The PR for CAL-134 will be broken out into multiple PRs.
This depends on: https://github.com/codice/alliance/pull/179

CAL-134: Mapping of PIAIMC attributes to ext.nitf.* fields.

---

catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/HistoaAttribute.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/TreDescriptor.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/gmti/GmtiMetacardType.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/image/ImageMetacardType.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/common/HistoaAttributeTest.java

CAL-134: Mapping for non-taxonomy HISTOA NITF TRE fields.
@glenhein 
@bdeining
@peterhuffer
@kcwire
@lessarderic
Run complete build with tests.
The PR for CAL-134 will be broken out into multiple PRs.
This depends on: https://github.com/codice/alliance/pull/179

CAL-134: Mapping of HISTOA attributes to ext.nitf.* fields.

---

catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/image/NitfImageTransformer.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/image/ImageInputTransformerTest.java

Inserts spaces between each individual comment before setting on the `IsrComments` attribute.
@troymohl @peterhuffer @glenhein 
@kcwire 
@millerw8 
- Build and install Alliance.
- Ingest a ntf image.
- View the metacard and verify the `Isr Comments` field has no words that are mashed together (e.g. "inaccordance").
[CAL-172](https://codice.atlassian.net/browse/CAL-172)

CAL-172: Fixing IsrComments attribute to be built up with spaces between each comment.

---

catalog/nsili/catalog-nsili-common/src/main/java/org/codice/alliance/nsili/common/NsiliConstants.java
catalog/nsili/catalog-nsili-common/src/main/java/org/codice/alliance/nsili/common/ResultDAGConverter.java
catalog/nsili/catalog-nsili-common/src/test/java/org/codice/alliance/nsili/common/ResultDAGConverterTest.java
distribution/sdk/sample-nsili-client/src/main/java/org/codice/alliance/nsili/client/NsiliClient.java

Fixes issue where NSIL_SECURITY and/or NSIL_METADATA_SECURITY were not always being set. These are mandatory fields in NSILI and they are now defaulted per the spec. Additionally, fixed a regression error where NSIL_FILE.ARCHIVE was not being in all cases, and set defaults on mandatory fields.
@bdeining 
@peterhuffer 
@jlcsmith
@millerw8 
Run a full build and the standalone test client in alliance/distribution/sdk/sample-nsili-client:
mvn -nsu -Pcorba.client -Dexec.args="https://localhost:8993/services/nsili/ior.txt"
Test with CSD Alpha.
https://codice.atlassian.net/browse/CAL-159

CAL-159: Ensure that NSIL_SECURITY and NSIL_METADATA_SECURITY are always populated

---

catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/AbstractNitfMetacardType.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/gmti/GmtiMetacardTypeTest.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/image/ImageMetacardTypeTest.java

Adds JUnit tests for ImageMetacardType and GmtiMetacardType to verify that they have the correct attributes present. 
@glenhein 
@peterhuffer 
@kcwire
@lessarderic
Run build + JUnit tests
https://codice.atlassian.net/browse/CAL-189

CAL-189: JUnit tests for NITF metacard types to ensure correct attributes are present

---

catalog/imaging/imaging-transformer-nitf/pom.xml
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/TreUtility.java

Backports https://github.com/codice/alliance/pull/179 for https://codice.atlassian.net/browse/CAL-134 to the 0.1.x branch.
@mcalcote 
@bdeining 
@kcwire
@shaundmorris 
This is the first dependency required for backporting CAL-134 changes to the 0.1.x branch.

(0.1.x) Backport CAL-134: Common TreUtility for processing CSEXRA, CSDIDA, PIAIMC, and HISTOA TREs

---

catalog/imaging/imaging-transformer-chipping/src/main/java/org/codice/alliance/imaging/chip/transformer/CatalogOutputAdapter.java

This PR fixes file extensions for image chips (jpeg) downloaded in windows.
@lcrosenbu @rzwiefel 
@jlcsmith
@kcwire
On windows : Build / Install / Ingest NITF / Download Chip and verify file extension
[CAL-199](https://codice.atlassian.net/browse/CAL-199)

CAL-199 Changed mime type so jpg file extension is applied in a windows environment for image chips

---

catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/netty/RawUdpDataToMTSPacketDecoder.java
distribution/sdk/sample-mpegts-streamgenerator/README.md
distribution/sdk/sample-mpegts-streamgenerator/src/main/java/org/codice/alliance/distribution/sdk/video/stream/mpegts/MpegTsUdpClient.java
distribution/test/itests/test-itests-alliance/src/test/java/org/codice/alliance/test/itests/VideoTest.java

Add thread locking around UDP buffer processing and improve exception logging when processing UDP packets.
@bdeining 
@jlcsmith 
@jlcsmith
@kcwire
Run within a window VM and stream with FFMPEG.
[CAL-173](https://codice.atlassian.net/browse/CAL-173)

CAL-173 Add thread locking to UDP video processing

---

catalog/imaging/imaging-actionprovider-chip/pom.xml
catalog/imaging/imaging-actionprovider-chip/src/main/java/org/codice/alliance/imaging/chip/actionprovider/ImagingChipActionProvider.java
catalog/imaging/imaging-actionprovider-chip/src/test/java/org/codice/alliance/imaging/chip/actionprovider/ImageChipActionProviderTest.java
pom.xml

This PR adds custom checking on derived resource URI for remote resources, which are not formatted the same as local resources. Fixes issue where NITF actions list is missing `Chip Image` action only for remote NITFs, due to a logic error in `canHandle` for the action provider, when it is parsing the derived resource URI.
@bdeining @dcruver @glenhein 
@coyotesqrl @jlcsmith 
- Build and run Alliance.
- Configure a CSW loopback source under `DDF Spatial` --> `CSW Specification Profile Federated Source` to mimic a remote source.
-- Add Source ID name
-- Change CSW URL to local: https://localhost:8993/services/csw
-- Change “Output Schema” to: urn:catalog:metacard
- Ingest a NITF formatted file, then perform a search to find the ingested file.
- Verify that the `Chip Image` action is …

CAL-195 Enable Chip Image action for remote NITF resources

---

libs/klv/src/main/java/org/codice/alliance/libs/klv/BaseKlvHandler.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/FrameCenterKlvProcessor.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/GeoBoxHandler.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/GeometryUtility.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/LatitudeLongitudeHandler.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/LocationKlvProcessor.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/GeoBoxHandlerTest.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/GeometryUtilityTest.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/LatitudeLongitudeHandlerTest.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/LocationKlvProcessorTest.java

Add fallback code to use Frame Center data for generating Core.LOCATION in cases when Corner and Offset Corner data is missing.
A video can now produce Core.LOCATION geographic data from three sources:
* Corner data
* Offset Corner and Frame Center, which when added together becomes Corner data
* Frame Center, which results in the location being a line string
@kcwire 
@bdeining 
@jlcsmith 
@coyotesqrl
@lessarderic
1) Build and install Alliance.
2) Configure the video stream monitor (default values should be fine)
3) Start the stream monitor (click the "start" button)
4) Using distribution/sdk/sample-mpegts-streamgenerator, stream an MPEG-TS file that contains Frame Center, but not Corner or Offset Corner data. If you don't have a video, please contact me.
5) After ingesting the video, …

CAL-171 Add support for videos that contain Frame Center data, but not Corner or Offset Corner

---

catalog/video/video-mpegts-transformer/src/main/resources/OSGI-INF/blueprint/blueprint.xml

Add video/vnd.dlna.mpeg-tts to list of mime types for MpegTsInputTransformer.
@bdeining 
@rzwiefel 
@jlcsmith
@kcwire
1) Build and install in a Windows environment.
2) Upload a video file that uses the ".ts" file extension.
3) Enable debug logging for MpegTsInputTransformer:
log:set DEBUG org.codice.alliance.transformer.video
4) Confirm that the MpegTsInputTransformer was triggered by looking for the debug message:
LOGGER.debug("processing video input for id = {}", id);
[CAL-200](https://codice.atlassian.net/browse/CAL-200)

CAL-200 add video/vnd.dlna.mpeg-tts to list of mime types for MpegTsInputTransformer

---

pom.xml

Adds the profile that runs the OWASP plugin. This way, a nightly build can be created to run OWASP on alliance daily.
@figliold @Lambeaux 
@lessarderic 
@shaundmorris 
Run `mvn clean install -Powasp` and OWASP should fail on multiple dependencies because of vulnerabilities.
[CAL-203](https://codice.atlassian.net/browse/CAL-203)

CAL-203: Adding profile for running dependency-check-maven (OWASP) plugin

---

catalog/video/video-security/src/main/java/org/codice/alliance/video/security/claims/videographer/VideographerClaimsHandler.java
catalog/video/video-security/src/test/java/org/codice/alliance/video/security/claims/videographer/VideographerClaimsHandlerTest.java

Update VideographerClaimsHandler to only add claims for the VideographerPrincipal.
@kcwire 
@bdeining 
@jlcsmith
@lessarderic
1) Build Alliance
2) Enable security logging:
log:set DEBUG ddf.security.service.impl
3) Complete install.
4) Look for the log line:
Adding permission: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier : guest
An incorrect log line includes the videographer, eg:
Adding permission: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier : videographer,guest
[CAL-201](https://codice.atlassian.net/browse/CAL-201)

CAL-201 Update VideographerClaimsHandler to only add claims for the VideographerPrincipal

---

catalog/video/video-admin-plugin/Gruntfile.js

This PR fixes the sed statement in the video admin plugin to prevent the browser from reaching out to google.apis
@lcrosenbu @rzwiefel 
@jlcsmith
@pklinef
Build and install Alliance Experimental, navigate to the Video Admin Plugin and observe that it does not reach out to google.
[CAL-191](https://codice.atlassian.net/browse/CAL-191)

CAL-191 Fixed sed block in video-admin-plugin

---

catalog/video/video-mpegts-transformer/src/main/resources/DDF_Custom_Mime_Type_Resolver.mpegts.config

Maps .mpg and .mpeg to the video/mp2t mime type
@bdeining @glenhein 
@kcwire 
1) Ingest .mpg and .mpeg files via the content directory monitor.  
2) Verify the resulting metacards have a metacard type of "isr:video".
[CAL-207](https://codice.atlassian.net/browse/CAL-207)

CAL-207 Added mpg and mepg extensions to MPEG-TS Content Resolver

---

catalog/video/video-admin-plugin/Gruntfile.js

This PR fixes the sed statement in the video admin plugin to prevent the browser from reaching out to google.apis
@lcrosenbu @rzwiefel 
@jlcsmith
@pklinef
Build and install Alliance Experimental, navigate to the Video Admin Plugin and observe that it does not reach out to google.
[CAL-191](https://codice.atlassian.net/browse/CAL-191)

(0.1.x) CAL-191 Fixed sed block in video-admin-plugin

---

pom.xml

Upgraded the frontend-maven-plugin to version 1.2 (latest). This will also allow Windows to use parallel builds.
@emanns95 @Lambeaux 
@pklinef
@shaundmorris
[CAL-xxxx](https://codice.atlassian.net/browse/CAL-xxxx)
Upgraded the frontend-maven-plugin to version 1.2 (latest). This will also allow Windows to use parallel builds.

CAL-194: Upgrade frontend-maven-plugin from 0.0.28 to 1.2

---

pom.xml

Adds the profile that runs the OWASP plugin. This way, a nightly build can be created to run OWASP on alliance daily.
@figliold @Lambeaux 
@lessarderic 
@shaundmorris 
Run 'mvn clean install -Powasp' and OWASP should fail on multiple dependencies because of vulnerabilities.
[CAL-203](https://codice.atlassian.net/browse/CAL-203)

[0.1.x]CAL-203: Adding profile for running dependency-check-maven (OWASP) plugin.

---

catalog/video/video-admin-plugin/pom.xml
catalog/video/video-admin-plugin/src/main/java/org/codice/alliance/video/ui/service/StreamMonitorHelper.java
catalog/video/video-admin-plugin/src/main/java/org/codice/alliance/video/ui/service/StreamMonitorHelperMBean.java
catalog/video/video-admin-plugin/src/main/webapp/css/index.css
catalog/video/video-admin-plugin/src/main/webapp/js/model/StreamMonitor.js
catalog/video/video-admin-plugin/src/main/webapp/js/view/StreamMonitor.view.js
catalog/video/video-admin-plugin/src/main/webapp/templates/addConfigurationModal.handlebars
catalog/video/video-admin-plugin/src/main/webapp/templates/streamMonitorTable.handlebars
catalog/video/video-admin-plugin/src/test/java/org/codice/alliance/video/ui/StreamMonitorHelperTest.java
catalog/video/video-mpegts-stream/pom.xml
catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/UdpStreamMonitor.java
catalog/video/video-mpegts-stream/src/main/resources/OSGI-INF/metatype/metatype.xml
distribution/sdk/sample-mpegts-streamgenerator/README.md
distribution/sdk/sample-mpegts-streamgenerator/src/main/java/org/codice/alliance/distribution/sdk/video/stream/mpegts/MpegTsUdpClient.java
distribution/test/itests/test-itests-alliance/src/test/java/org/codice/alliance/test/itests/VideoTest.java
pom.xml

Add support for multicast video streaming. Improves the video-admin-plugin to display a drop-down select of available network interfaces when a multicast IP address is entered in the URL field.
@jlcsmith 
@bdeining 
@kcwire
@lessarderic
Configure the video monitor for multicast with the video-admin-plugin. For the IP address in the URL field, use an IP in the range 224.0.0.0 - 239.255.255.255. A drop-down select will appear that allows you to select the network interface that will receive the multicast traffic. The correct interface depends on your environment. 
Use the sample-mpegts-streamgenerator to transmit an mpeg-ts video to the IP address used in the video-admin-plugin. 
Note: Depending on your network configuration/topology, you may encounter a high percentage of …

CAL-205 Add support for multicast video streaming

---

catalog/core/catalog-core-classification-api/pom.xml
catalog/core/catalog-core-classification-api/src/main/java/org/codice/alliance/catalog/core/internal/api/classification/SecurityClassificationService.java
catalog/core/catalog-core-classification-impl/pom.xml
catalog/core/catalog-core-classification-impl/src/main/java/org/codice/alliance/catalog/core/internal/impl/classification/SecurityClassificationServiceImpl.java
catalog/core/catalog-core-classification-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/core/catalog-core-classification-impl/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/core/catalog-core-classification-impl/src/test/java/org/codice/alliance/catalog/core/internal/impl/classification/SecurityClassificationServiceImplTest.java
catalog/core/pom.xml
catalog/security/security-app/pom.xml
catalog/security/security-app/src/main/resources/features.xml
catalog/video/video-app/src/main/resources/features.xml
catalog/video/video-mpegts-stream/pom.xml
catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/metacard/MetacardUpdater.java
catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/metacard/SecurityClassificationMetacardUpdater.java
catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/netty/UdpStreamProcessor.java
catalog/video/video-mpegts-stream/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/video/video-mpegts-transformer/pom.xml
catalog/video/video-mpegts-transformer/src/main/java/org/codice/alliance/transformer/video/MpegTsInputTransformer.java
catalog/video/video-mpegts-transformer/src/main/java/org/codice/alliance/transformer/video/SetDistanceToleranceVisitor.java
catalog/video/video-mpegts-transformer/src/main/java/org/codice/alliance/transformer/video/SetSecurityClassificationString.java
catalog/video/video-mpegts-transformer/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/video/video-mpegts-transformer/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/video/video-mpegts-transformer/src/test/java/org/codice/alliance/transformer/video/MpegTsInputTransformerTest.java
libs/klv/pom.xml
libs/klv/src/main/java/org/codice/alliance/libs/klv/BaseKlvProcessorVisitor.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/KlvProcessor.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/SecurityClassificationKlvProcessor.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/SecurityClassificationKlvProcessorTest.java

Add ability to map KLV security classification integers to security classification strings, for admins to configure the integer-to-string mapping, and for admins to control the sort order of classification strings so that the strictest classification is used when multiple classifications are present
@bdeining 
@Lambeaux 
@kcwire 
@jlcsmith 
@stustison 
@beyelerb
@lessarderic
- Build and install Alliance
- configure a video stream
- use the sample-mpegts-streamgenerator to stream a video that contains security classification KLV data (ask me if you don't have a test video)
- Using the UI, check that the parent metacard and the chunk metacard contains an attribute value for "Security Classification" that says "unclassified" (assuming you used the default security mappings)
CAL-163
…

CAL-163 Implement KLV security classification mapping

---

catalog/video/video-mpegts-transformer/src/main/java/org/codice/alliance/transformer/video/MpegTsInputTransformer.java
catalog/video/video-mpegts-transformer/src/test/java/org/codice/alliance/transformer/video/MpegTsInputTransformerTest.java

Set the datatype attribute to "Video" for MPEG-TS files.
@bdeining 
@jlcsmith 
@kcwire
@lessarderic
1) Build and install Alliance.
2) Upload an MPEG-TS file (.TS).
3) Confirm that the 'datatype' attribute it 'Video'.
[CAL-208](https://codice.atlassian.net/browse/CAL-208)

CAL-208 Set the datatype attribute to "Video" for MPEG-TS files.

---

catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/NitfParserAdapter.java

Improves performance of the Nitf Storage by only getting headers of the NITF.
@dcruver @glenhein   
@jlcsmith
@kcwire
Run the full build.
log:set DEBUG ddf.camel
Create a content directory monitor
Ingest a NITF. Verify the NITF ingests. Should see a metacard CREATED message in the logs.
Previously this code was retrieving the full NITF data when only the header information was needed, causing un-necessary parsing overhead.
https://codice.atlassian.net/browse/CAL-211

CAL-211: Update NitfParserAdapter to only get headers when returning NitfSegmentsFlow.

---

catalog/imaging/pom.xml

Updated dependency version number in catalog/imaging/pom.xml.
@glenhein 
@peterhuffer 
@jlcsmith
@kcwire
1) build the alliance imaging app
2) load alliance imaging app into a running DDF instance
3) upload some known-good test NITFs
--verify the test NITFs are ingested as they were with imaging-nitf 0.5
No API changes, only bug fixes and TRE parsing improvements.
CAL-216 (https://codice.atlassian.net/browse/CAL-216)

CAL-216 Update imaging-nitf library dependency to version 0.6

---

catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/netty/PacketBuffer.java

This PR prevents the creation of a child metacard with an empty temp file.
@glenhein @rzwiefel 
@jlcsmith
@kcwire
Build / Install Experimental / `log:set DEBUG org.codice.alliance` / Add video stream / Stream Video / Destroy Stream and observe correct behavior / Verify ingested video contents
[CAL-220](https://codice.atlassian.net/browse/CAL-220)

CAL-220 Fixed the creation of an empty content metacard when FMV streams are destroyed

---

catalog/imaging/imaging-app/src/main/resources/features.xml
catalog/nsili/nsili-app/src/main/resources/features.xml
catalog/security/security-app/src/main/resources/features.xml
catalog/video/video-app/src/main/resources/features.xml
pom.xml

Removes Alliance from app names. The Alliance Security app was not changed due to a collision with (DDF) Security.
@bdeining @clockard @gordocanchola @vinamartin @brianfelix @vinamartin @peterhuffer 
@jlcsmith
@shaundmorris 
Install DDF/Alliance and observe the app names in the admin ui.
[CAL-70](https://codice.atlassian.net/browse/CAL-70)

CAL-70 Removed Alliance from app names

---

distribution/docs/src/main/resources/_contents/_data/extended-attributes-table-contents.adoc
distribution/docs/src/main/resources/_contents/_data/isr-attributes-table-contents.adoc
distribution/docs/src/main/resources/_contents/_data/neutral-taxonomy-categories-contents.adoc
distribution/docs/src/main/resources/_contents/_data/security-attributes-table-contents.adoc
distribution/docs/src/main/resources/draft-documentation.adoc

adds documentation for neutral taxonomy to `draft-documentation`
@brendan-hofmann @emanns95 @AzGoalie
@jlcsmith
@kcwire
@pklinef
@shaundmorris
- review content of tables
- builds successfully.
[CAL-224](https://codice.atlassian.net/browse/CAL-224)
[DDF-2682](https://codice.atlassian.net/browse/DDF-2682)
[draft-documentation.pdf](https://github.com/codice/alliance/files/712000/draft-documentation.pdf)

CAL-224 added docs for neutral taxonomy

---

dependency-check-maven-config.xml

Address OWASP vulnerabilities by suppressing false positives using dependency-check-maven-config.xml.
@clockard @gordocanchola @vinamartin @mcalcote 
@shaundmorris
@stustison
Full OWASP build should pass
[CAL-229](https://codice.atlassian.net/browse/CAL-229)

CAL-229: Addressed false positive OWASP vulnerabilties

---

catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/NitfHeaderAttribute.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/image/ImageAttribute.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/image/NitfImageTransformer.java
catalog/imaging/imaging-transformer-nitf/src/test/groovy/NitfPreStoragePluginTest.groovy
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/TreTestUtility.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/image/ImageInputTransformerTest.java

This PR populates `effective` in the metacard with the date and time of the first image in the metacard. This PR also sets `datetime.start` and `datetime.end` from the image segments.
@clockard @dcruver @mcalcote @glenhein 
@kcwire 
@shaundmorris
- Ingest an image nitf.
- Confirm that the `dateTime` attributes are populated correctly in the metacard.
- `datetime.start` = `effective` = date and time of the first image segment
- `ext.nitf.image.image-date-and-time` = date and time of each image segment
- `datetime.end` = date and time of the last image segment
- `created` = `modified` = `ext.nitf.file-date-and-time` = file date and time of the header
- `metacard.created` = `metacard.modified` = time of ingest
- Confirm that attributes have as many values as expected. Only attributes …

CAL-235 Populated metacard effective attribute with date and time of first image in NITF

---

distribution/docs/src/main/resources/draft-documentation.adoc

Reorders the "Using" sections for UIs to match the DDF doc outline and prioritize Catalog UI as the default. 
@lcrosenbu @emmberk @vinamartin @mcalcote @jrnorth @Lambeaux 
@jlcsmith
@kcwire
@pklinef
@shaundmorris
builds successfully. 
[CAL-232](https://codice.atlassian.net/browse/CAL-232)
[DDF-2651](https://codice.atlassian.net/browse/DDF-2651)
n/a

CAL-232 reordered Using section in documentation

---

catalog/plugin/catalog-plugin-security-audit/pom.xml
catalog/plugin/catalog-plugin-security-audit/src/main/java/org/codice/alliance/catalog/plugin/security/audit/SecurityAuditPlugin.java
catalog/plugin/catalog-plugin-security-audit/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/plugin/catalog-plugin-security-audit/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/plugin/catalog-plugin-security-audit/src/test/java/org/codice/alliance/catalog/plugin/security/audit/SecurityAuditPluginTest.java
catalog/plugin/pom.xml
catalog/security/security-app/pom.xml
catalog/security/security-app/src/main/resources/features.xml
distribution/docs/src/main/resources/_contents/_plugins/security-audit-plugin-contents.adoc
distribution/docs/src/main/resources/draft-documentation.adoc
distribution/test/itests/test-itests-alliance/src/test/java/org/codice/alliance/test/itests/SecurityAuditPluginTest.java
distribution/test/itests/test-itests-alliance/src/test/resources/metacard1.xml
distribution/test/itests/test-itests-alliance/src/test/resources/metacard2.xml
pom.xml

Adds a security audit plugin with a configuration for security attributes that should be audited when changed.
Looking for feedback on the audit message, specifically, whether or not it should say something else and in addition if there seems there is anything missing from the configuration file. 
@codice/security 
@lessarderic 
@stustison
Ingest anything into the catalog and then change a security attribute (this is easier with the Catalog UI in DDF). Verify the change was audited. 
[CAL-215](https://codice.atlassian.net/browse/CAL-215)

CAL-215 Adds security audit plugin

---

catalog/plugin/catalog-plugin-defaultsecurityattributevalues/src/main/java/org/codice/alliance/catalog/plugin/defaultsecurity/DefaultSecurityAttributeValuesPlugin.java
catalog/plugin/catalog-plugin-defaultsecurityattributevalues/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/plugin/catalog-plugin-defaultsecurityattributevalues/src/test/java/org/codice/alliance/catalog/plugin/defaultsecurity/DefaultSecurityAttributeValuesPluginTest.java

Updates the `DefaultSecurityAttributeValuesPlugin` to no longer skip setting defaults when metacards have a non-empty policy. This change was needed due to the introduction of the `ResourceUriPolicy` plugin. 
@shaundmorris 
@ryeats 
@kcwire 
@stustison
Ingest a variety of test data, of different formats, and ensure that everything receives security attributes where appropriate. The attributes should render in the UI when inspecting a metacard. 
[CAL-234](https://codice.atlassian.net/browse/CAL-234)

CAL-234: Default security attributes get set on metacards if they contain no highwater security markings, regardless of policy

---

CHANGES.md

updates changelog
@bdeining @lcrosenbu 
@coyotesqrl
@figliold
@jaymcnallie
@jlcsmith
@kcwire
@lessarderic
@pklinef
@shaundmorris
@stustison
review content
comment any issues that should be added/highlighted.

CAL-240 updated changelog for 0.2.0 release

---

catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/CsexraAttribute.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/PiaimcAttribute.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/TreUtility.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/common/CsexraAttributeTest.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/common/PiaimcAttributeTest.java

Includes a check within convertToInteger(), convertToFloat()..etc methods inside the TreUtility class to verify that the TRE fields of type Integer, Float..etc have values that are not equal to empty string before attempting to parse them into their corresponding type.
Also TRE attributes that call a specific accessor function, for example the CLOUDCVR field in PIAIMC calls getCloudCoverFunction(), need to include the not empty check also as they may attempt to parse an empty string into some other type.
@dcruver 
@coyotesqrl
@jaymcnallie 
Ingest a NITF containing a PIAIMC TRE. The NITF's PIAMIC TRE needs to have the field: CLOUDCVR with the value equal to: "".
Verify that no exceptions occur in the logs when ingesting the NITF and that all TRE data from all TREs in the …

CAL-250 Prevent parse exceptions from occurring when ingesting NITFs that have TRE fields with values equal to empty string

---

catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/CsexraAttribute.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/PiaimcAttribute.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/TreUtility.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/common/CsexraAttributeTest.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/common/PiaimcAttributeTest.java

Backport CAL-250 to 0.2.x
See (https://github.com/codice/alliance/pull/248) for more information.

CAL-250 (Backport 0.2.x) Prevent parse exceptions from occurring when ingesting NITFs that have TRE fields with values equal to empty string

---

catalog/video/video-admin-plugin/src/main/webapp/js/view/StreamMonitor.view.js
catalog/video/video-admin-plugin/src/main/webapp/templates/addConfigurationModal.handlebars
catalog/video/video-mpegts-stream/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/video/video-mpegts-stream/src/main/resources/OSGI-INF/metatype/metatype.xml

Change the default distance tolerance to 0.01.
@bdeining 
@jlcsmith 
@kcwire
@lessarderic
Configure a new stream through the FMV Stream Management and MPEG-TS UDP Stream Monitor. Note that the default value in both places is 0.01.
[CAL-246](https://codice.atlassian.net/browse/CAL-246)

CAL-246 change the default distance tolerance to 0.01

---

catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/AbstractNitfMetacardType.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/PiatgbAttribute.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/TreDescriptor.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/gmti/GmtiMetacardType.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/image/ImageMetacardType.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/common/AcftbAttributeTest.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/common/AimidbAttributeTest.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/common/PiatgbAttributeTest.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/gmti/GmtiMetacardTypeTest.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/image/ImageInputTransformerTest.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/image/ImageMetacardTypeTest.java
distribution/docs/src/main/resources/_contents/_formats/supported-file-formats-contents.adoc

-Adds support for populating the metacard with PIATGB TRE data when ingesting a NITF.
-Adds common attribute descriptors between the ImageMetcardType and the GmtiMetacardType into the AbstractNitfMetacardType to prevent code duplication.
@dcruver 
@bdeining 
@jaymcnallie
@jlcsmith
Ingest a NITF containing the PIATGB TRE, perform a query and verify in the search UI that the TRE data shows up in the metacard.
[CAL-251](https://codice.atlassian.net/browse/CAL-251)
- [N/A] Update / Add Integration Tests

CAL-251 Add support for the PIATGB TRE

---

distribution/alliance/pom.xml
distribution/docs/pom.xml
pom.xml

Backport of https://github.com/codice/alliance/pull/257
_distribution/alliance/pom.xml, distribution/docs/pom.xml_
Changes the documentation profile to be activated when the property “skipDocs” is false or not provided. (Reference an example here: http://maven.apache.org/guides/introduction/introduction-to-profiles.html). This was done to prevent issues with profile activation that were happening. 
From the Maven website, emphasis mine:
_[A profile using `<activeByDefault>`] will automatically be active for all builds unless another profile **in the same POM** is activated using one of the previously described methods. All profiles that are active by default are **automatically deactivated when a profile in the POM is activated** on the command line or through its activation config._ …

CAL-257: Fixes documentation activation bug

---

catalog/imaging/imaging-transformer-nitf/pom.xml

Restores dependencies that were removed when imaging-plugin-nitf was moved
@mcalcote  @emmberk 
@kcwire
@shaundmorris
Verify the itest ImagingTest passes on the first try
[CAL-258](https://codice.atlassian.net/browse/CAL-258)

CAL-258 Fix dependencies in imaging-transformer-nitf.

---

catalog/imaging/imaging-transformer-nitf/pom.xml

(cherry picked from commit 52a4b11)
Port for https://github.com/codice/alliance/pull/267
@bdeining @emmberk 
@jlcsmith
@kcwire
Verify itests pass
[CAL-258](https://codice.atlassian.net/browse/CAL-258)

CAL-258 -Port- Fix dependencies in imaging-transformer-nitf.

---

catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/netty/UdpStreamProcessor.java
catalog/video/video-mpegts-stream/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/video/video-mpegts-transformer/src/main/java/org/codice/alliance/transformer/video/SetDistanceToleranceVisitor.java
libs/klv/pom.xml
libs/klv/src/main/java/org/codice/alliance/libs/klv/ConvertSubpolygonsToEnvelopes.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/FrameCenterKlvProcessor.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/ConvertSubpolygonsToEnvelopesTest.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/FrameCenterKlvProcessorTest.java

* subsample the frame-center data in child metacards
* do not merge frame-center data from the child metacards to the parent
* convert the subpolygons in the parent location geometry to envelopes (ConvertSubpolygonsToEnvelopes.java)
@bdeining 
@jlcsmith 
@kcwire
@lessarderic
Test child frame center: ingest an MPEG-TS video that contains frame center data. Examine the resulting metacard and verify that the number of frame center data points is less than or equal to the subsample configuration (default is 50).
Test parent metacard does not have frame center: ingest a streaming video that contains frame center data. Examine the parent metacard and verify that the frame center field is not present.
Test subpolygons: ingest a streaming video that contains location data. Examine the parent …

CAL-255 Improve FMV ingest performance.

---

catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/netty/UdpStreamProcessor.java
catalog/video/video-mpegts-stream/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/video/video-mpegts-transformer/src/main/java/org/codice/alliance/transformer/video/SetDistanceToleranceVisitor.java
libs/klv/pom.xml
libs/klv/src/main/java/org/codice/alliance/libs/klv/ConvertSubpolygonsToEnvelopes.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/FrameCenterKlvProcessor.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/ConvertSubpolygonsToEnvelopesTest.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/FrameCenterKlvProcessorTest.java

* subsample the frame-center data in child metacards
* do not merge frame-center data from the child metacards to the parent
* convert the subpolygons in the parent location geometry to envelopes (ConvertSubpolygonsToEnvelopes.java)
@bdeining 
@jlcsmith 
@kcwire
@lessarderic
Test child frame center: ingest an MPEG-TS video that contains frame center data. Examine the resulting metacard and verify that the number of frame center data points is less than or equal to the subsample configuration (default is 50).
Test parent metacard does not have frame center: ingest a streaming video that contains frame center data. Examine the parent metacard and verify that the frame center field is not present.
Test subpolygons: ingest a streaming video that contains location data. Examine the parent …

CAL-255 (Backport 0.2.x) Improve FMV ingest performance.

---

pom.xml

Adds the `gitflow-incremental-builder` build extension to the root `pom.xml` to support local and PR incremental builds.
@oconnormi
@LinkMJB
@coyotesqrl
@shaundmorris
1. Run `mvn clean install` and make sure a normal build is executed.
1. Make a local change to a source file, run `mvn -Dgib.enaled=true clean install` and make sure only the module that was changed and all its dependent modules are built
[CAL-266](https://codice.atlassian.net/browse/CAL-266)

CAL-266 [0.2.x] Add incremental builder extension to speed up PR builds

---

pom.xml

Adds the `gitflow-incremental-builder` build extension to the root `pom.xml` to support local and PR incremental builds.
@oconnormi
@LinkMJB
@coyotesqrl
@shaundmorris
1. Run `mvn clean install` and make sure a normal build is executed.
1. Make a local change to a source file, run `mvn -Dgib.enaled=true clean install` and make sure only the module that was changed and all its dependent modules are built
[CAL-266](https://codice.atlassian.net/browse/CAL-266)

CAL-266 Add incremental builder extension to speed up PR builds

---

catalog/video/video-mpegts-transformer/src/main/java/org/codice/alliance/transformer/video/MpegTsInputTransformer.java
libs/klv/pom.xml
libs/klv/src/main/java/org/codice/alliance/libs/klv/ConvertSubpolygonsToEnvelopes.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/GeometryReducer.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/GeometryUtility.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/SimplifyGeometryFunction.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/GeometryReducerTest.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/GeometryUtilityTest.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/SimplifyGeometryFunctionTest.java

- Added checks for empty geos
- Added checks for null geos
- Added geo validity checking
- In geometry union method, added fallback to convex hull to handle validity issues
@glenhein @bdeining 
@millerw8 
1) Turn up TRACE level logging on org.codice.alliance
2) Start one or more video streams.  Use ffmpeg or similar utility to stream video.
3) Verify that no NPEs occur during streaming
During video streaming, depending on the video metadata, empty or null geometries may be encountered during the geometry subsampling and simplification process.  Also, there have been instances of invalid geometries occurring as the result of the geometry calculations which can cause failures during solr indexing.
This PR handles those cases gracefully.
[CAL-267](https://codice.atlassian.net/browse/CAL-267)

CAL-267 Improved handling of empty or null geos in KLV library

---

catalog/imaging/imaging-plugin-nitf/pom.xml
catalog/imaging/imaging-plugin-nitf/src/main/java/org/codice/alliance/plugin/nitf/NitfPreStoragePlugin.java
catalog/imaging/imaging-plugin-nitf/src/test/java/org/codice/alliance/plugin/nitf/PreStoragePluginTest.java
catalog/imaging/imaging-plugin-nitf/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker

Catches an `IllegalArgumentException` being thrown by jai-imageio-jpeg2000 when there is an image with 0 bands. This allows nitfs to be ingested without a successful thumbnail being generated. 
This PR uses an incubating feature in Mockito version 2 for mocking finals, more details here: https://github.com/mockito/mockito/wiki/What%27s-new-in-Mockito-2#unmockable
@clockard @brendan-hofmann @garrettfreibott @brianfelix @emanns95 
@lessarderic
@figliold 
@jlcsmith 
[CAL-283](https://codice.atlassian.net/browse/CAL-283)

CAL-283- Catches exception that could cause thumbnail gen to fail

---

catalog/video/video-mpegts-transformer/src/main/java/org/codice/alliance/transformer/video/MpegTsInputTransformer.java
libs/klv/pom.xml
libs/klv/src/main/java/org/codice/alliance/libs/klv/ConvertSubpolygonsToEnvelopes.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/GeometryReducer.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/GeometryUtility.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/SimplifyGeometryFunction.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/GeometryReducerTest.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/GeometryUtilityTest.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/SimplifyGeometryFunctionTest.java

Backport of CAL-267
- Added checks for empty geos
- Added checks for null geos
- Added geo validity checking
- In geometry union method, added fallback to convex hull to handle validity issues
@bdeining @glenhein 
@millerw8
See https://github.com/codice/alliance/pull/279
[CAL-267](https://codice.atlassian.net/browse/CAL-267)

CAL-267 (0.2.x) Improved handling of empty or null geos in KLV library (#279)

---

pom.xml

Enables a ddf-support maven plugin which scans the project at build for any package.json files which incorrectly use version ranges for dependencies.
@ahoffer @emanns95 @AzGoalie @vinamartin 
[Build](https://github.com/orgs/codice/teams/build)
@coyotesqrl
@pklinef
Will need to pull in ddf-support PR as well (https://github.com/codice/ddf-support/pull/38) for the actual plugin, and then run `mvn verify` in Alliance. Successful if verify errors out with a MojoException due to incorrect version range symbols. 
Version ranges expose the codebase to potential vulnerabilities, unlike sticking to exact, known versions of dependencies. 
[](https://codice.atlassian.net/browse/DDF-2819)
[](https://codice.atlassian.net/browse/CAL-261)

CAL-261 Add maven-version-validation-plugin to root pom.xml

---

distribution/test/itests/test-itests-alliance/src/test/java/org/codice/alliance/test/itests/AllianceAppsTest.java
distribution/test/itests/test-itests-alliance/src/test/java/org/codice/alliance/test/itests/BannerMarkingsTest.java
distribution/test/itests/test-itests-alliance/src/test/java/org/codice/alliance/test/itests/ImagingTest.java
distribution/test/itests/test-itests-alliance/src/test/java/org/codice/alliance/test/itests/NsiliEndpointTest.java
distribution/test/itests/test-itests-alliance/src/test/java/org/codice/alliance/test/itests/NsiliSourceTest.java
distribution/test/itests/test-itests-alliance/src/test/java/org/codice/alliance/test/itests/SecurityAuditPluginTest.java
distribution/test/itests/test-itests-alliance/src/test/java/org/codice/alliance/test/itests/VideoTest.java

All itests reset catalog contents in an @after with the karaf command "catalog:removeall -f -p". Previous cleanup logic has been removed from relevant itests. Additonally, data used by itests are now ingested in @before.
@ahoffer @emanns95 @mweser @brendan-hofmann 
@coyotesqrl
@shaundmorris
[CAL-268](https://codice.atlassian.net/browse/CAL-268)

CAL-268 Reset the catalog contents after every itest

---

catalog/imaging/imaging-plugin-nitf/pom.xml

Fixes a problem with dependencies that caused the ImagingTest to not pass.
@bdeining
@glenhein
@coyotesqrl
@millerw8
Run a full `mvn clean install`
The ImagingTest was still intermittently failing after https://github.com/codice/alliance/pull/295 was merged. 
[CAL-286](https://codice.atlassian.net/browse/CAL-286)

CAL-286 Fix errors with the ImagingTest itest.

---

catalog/core/catalog-core-api-impl/src/main/java/org/codice/alliance/catalog/core/api/impl/types/IsrAttributes.java

backport of https://github.com/codice/alliance/pull/270
Updates isr.mission-id to be multi-valued
@bdeining @brendan-hofmann 
@kcwire
[CAL-263](https://codice.atlassian.net/browse/CAL-263)

(0.2.x) CAL-263: Changed isr.mission-id to be multi-valued

---

distribution/docs/pom.xml
distribution/docs/src/assembly/docs-export.xml
distribution/docs/src/assembly/jdocs.xml
distribution/docs/src/main/jdocs/content/jdocumentation.adoc
distribution/docs/src/main/jdocs/jbake.properties
distribution/docs/src/main/resources/_contents/jconfig.adoc

Sets up jbake as part of documentation process to render docs from templates.
@coyotesqrl
@jlcsmith
@pklinef
@shaundmorris
- fresh build with a clean repo
- no test failures or unresolved directive errors in rendered documentation
- all marked content included correctly
As part of the larger automation process, the incomplete documentation will be rendered as a file called `jdocumentation.html` / `pdf`. Once all sections are migrated, this non-deployed file will replace the current documentation.html files being generated.
[DDF-2802](https://codice.atlassian.net/browse/DDF-2802)
[CAL-274](https://codice.atlassian.net/browse/CAL-274)
[jdocumentation.zip](https://github.com/codice/alliance/files/863233/jdocumentation.zip)

CAL-274 added template for documenting endpoints in auto-docs

---

gitsetup/pom.xml

Fix to the gitsetup module. A maven build (normal or quick) is not actually skipping execution of these plugins on the gitsetup module, as intended.
@Lambeaux @figliold 
@coyotesqrl 
@lessarderic 
Run both a `mvn clean install` and `quickbuild` from the root. The build can be stopped after the Gitsetup module is built (it's only the second one). Verify in the maven output that `maven-dependency-plugin`, `findbugs-maven-plugin`, and `maven-checkstyle` plugins are not executed under the Gitsetup module.
[CAL-288](https://codice.atlassian.net/browse/CAL-288)

CAL-288 Fixing gitsetup to truly not run plugins from the parent pom

---

Jenkinsfile

The goal of this change is to add the initial Jenkinsfile to the project repo and establish the format for follow-on work. 
@oconnormi @vinamartin @emmberk
[Build](https://github.com/orgs/codice/teams/build) @brendan-hofmann 
@lessarderic 
@clockard 
This job is currently running in the test Jenkins environment. After this ticket is merged we can set up a job for it on the standard jenkins to eventually migrate our nightly (and beyond) to.
This jenkinsfile utilizes the declarative syntax. This is currently in its 1.0 state and will likely have refinements and improvements rolling out in the near future.
[CAL-294](https://codice.atlassian.net/browse/CAL-294)

CAL-294 Added initial jenkinsfile

---

catalog/plugin/catalog-plugin-defaultsecurityattributevalues/src/main/java/org/codice/alliance/catalog/plugin/defaultsecurity/DefaultSecurityAttributeValuesPlugin.java
catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/netty/UdpStreamProcessor.java

Changes code to use non-static version of `Security.runAsAdmin()` method.
@glenhein 
@clockard 
@stustison
Full build, install and make sure default security attribute values plug-in and UDP stream processor are still working as expected.
This change depends on https://github.com/codice/ddf/pull/1966
[CAL-298](https://codice.atlassian.net/browse/CAL-298)

CAL-298 Refactor code to use new DDF Security class' non-static runAsAdmin method

---

distribution/test/itests/pom.xml
distribution/test/itests/test-itests-alliance/pom.xml

Release Notes:
https://ops4j1.jira.com/wiki/display/PAXEXAM4/2017/05/16/Pax+Exam+4.11.0+released
Referenced: 
https://github.com/ops4j/org.ops4j.pax.exam2/blob/exam-reactor-4.11.0/pom/pom.xml
@emmberk @stustison @kcwire 
@clockard 
@lessarderic 
Run the integration tests and make sure everything passes
[CAL-303](https://codice.atlassian.net/browse/CAL-303)

CAL-303 Upgrade to Pax Exam 4.11.0

---

catalog/imaging/imaging-app/src/main/resources/features.xml
catalog/imaging/imaging-nitf-api/pom.xml
catalog/imaging/imaging-nitf-impl/pom.xml
catalog/imaging/imaging-nitf-impl/src/main/java/org/codice/alliance/imaging/nitf/impl/NitfParserServiceImpl.java
catalog/imaging/imaging-plugin-nitf/pom.xml
catalog/imaging/imaging-plugin-nitf/src/main/java/org/codice/alliance/plugin/nitf/NitfPreStoragePlugin.java
catalog/imaging/imaging-transformer-chipping/pom.xml
catalog/imaging/imaging-transformer-chipping/src/main/java/org/codice/alliance/imaging/chip/transformer/CatalogOutputAdapter.java
catalog/imaging/imaging-transformer-chipping/src/test/java/org/codice/alliance/imaging/chip/transformer/CatalogOutputAdapterTest.java
catalog/imaging/imaging-transformer-nitf/pom.xml
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/image/NitfImageTransformer.java
catalog/imaging/imaging-transformer-nitf/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/RoutingSlipTest.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/TreTestUtility.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/gmti/NitfGmtiTransformerTest.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/image/ImageInputTransformerTest.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/image/TestTextAttribute.java
catalog/imaging/pom.xml
distribution/test/itests/test-itests-alliance/src/test/java/org/codice/alliance/test/itests/ImagingTest.java
distribution/test/itests/test-itests-dependencies-app/pom.xml
distribution/test/itests/test-itests-dependencies-app/src/main/filtered-resources/features.xml
pom.xml

The imaging-nitf fluent-api bundle was recently split into 'fluent' and 'fluent-api'.  The imaging-nitf core bundle was recently split into 'core-api' and 'core'. The bulk of these changes remove unneeded embedded dependencies from pom files and to make code changes to reflect the imaging-nitf API changes.
Imaging-nitf core also added the ability to deal with coordinates in UTM and MGRS formats. This PR also modifies a line of code that was filtering out locations that weren't in DMS or decimal degrees format.
@glenhein 
@roelens8 
@vinamartin 
@jaymcnallie
@kcwire
@jlcsmith 
1) build and start Alliance
-- verify that the imaging-app starts up
2) ingest some NITFs that have locations recorded with various coordinate systems (UTMNORTH, UTMSOUTH, MGRS, etc.)
-- verify that the product …

CAL-284 Update imaging-app to use imaging-nitf 0.8

---

distribution/docs/src/main/jdocs/jbake.properties

updates `jbake.properties` for including the Quick Start Tutorial in the templated documentation.
@vinamartin @Lambeaux @ahoffer @jrnorth @troymohl 
@clockard 
@coyotesqrl
@lessarderic
@pklinef
@shaundmorris
- compare attached pdf to existing documentation for completeness.
- "New" `-contents.adoc` files are existing content with headers added. Content review is OPTIONAL.
- moved the quickstart closer to the beginning of the documentation.
[CAL-271](https://codice.atlassian.net/browse/CAL-271)
[jdocumentation.pdf](https://github.com/codice/alliance/files/1069040/jdocumentation.pdf)

CAL-271 added quick start guide to docs template

---

distribution/common/src/main/resources/common-bin.xml
distribution/common/src/main/resources/etc/log4j2.config.xml
distribution/common/src/main/resources/etc/org.ops4j.pax.logging.cfg

This PR renames the main log filename from `ddf.log` to `alliance.log`.
@vinamartin @alexaabrd @josephthweatt 
@clockard 
@figliold 
- Confirm that the log file in `/data/log` is named `alliance.log` and contains the regular log entries.
- Confirm that the documentation uses `alliance.log`, not `ddf.log`.
Alliance used to pull these 2 log configuration files from DDF, which caused the log file name to be `ddf.log`. The 2 added files in this PR are copied exactly from DDF, except the text `ddf.log` is replaced with `alliance.log`.
[CAL-314](https://codice.atlassian.net/browse/CAL-314)

CAL-314 Renamed main log filename from ddf.log to alliance.log

---

catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/NitfHeaderAttribute.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/image/ImageInputTransformerTest.java

NITF metacard format and format-version was being set incorrectly to "NITF_TWO_ONE" and "NITF_TWO_ZERO".  Updated the NITF transformer to set the format and version correctly.
@rzwiefel @dcruver 
@beyelerb
Verify ingested NITF 2.1, 2.0, and NSIF 1.0 files have media.format and media.format-version attributes set correctly.
[CAL-306](https://codice.atlassian.net/browse/CAL-306)

CAL-306 Corrected NITF metacard format and version

---

distribution/alliance/src/main/filtered-resources/etc/org.apache.karaf.features.cfg

This PR removed the extra comma that was added to the end of the `featuresBoot` list in the `org.apache.karaf.feature.cfg` file because it is no longer needed.
@mcalcote @vinamartin @alexaabrd @josephthweatt 
@clockard
@lessarderic
- itests
- `/bin/ddf` script
[CAL-312](https://codice.atlassian.net/browse/CAL-312)

CAL-312 Fixed tech debt in featuresBoot in org.apache.karaf.features.cfg

---

catalog/security/security-app/src/main/resources/features.xml

Typo in version for alliance-catalog-core-api in catalog/security/security-app/src/main/resources/features.xml causes the feature to have an invalid version.
Typo in version for alliance-catalog-core-api in catalog/security/security-app/src/main/resources/features.xml causes the feature to have an invalid version.
The typo declares the version "${project.version" resulting in the feature to have a version of 0.0.0.__project_version.
This PR adds trailing curly brace to resolve the issue.
@bdeining 
@brianfelix 
@coyotesqrl
@pklinef
Build Alliance, run it, check feature:list and confirm alliance-catalog-core-api feature has the appropriate version as opposed to 0.0.0.__project_version
[CAL-310](https://codice.atlassian.net/browse/CAL-310)

CAL-310 Typo in version for alliance-catalog-core-api in feature file

---

dependency-check-maven-config.xml

Karaf 4.1.1 uses pax-web-jsp 6.0.3 which is a dependency of ddf-kernel and contains several CVEs. None of these vulnerabilities are exposed through this code, so Apache must mitigate them.
kernel-2.11.0-SNAPSHOT.zip: pax-web-jsp-6.0.3.jar: CVE-2016-8735, CVE-2014-0230, CVE-2013-2185, CVE-2011-3190, CVE-2009-3548
@emmberk @vinamartin @alexaabrd 
@clockard  @pklinef 
Read the CVEs and make a determination if this CPE is the correct approach.
These CVEs do not cause the DDF owasp check to fail, but instead affect alliance only.
[CAL-312](https://codice.atlassian.net/browse/CAL-312)

CAL-312 Added CPE suppression for CVEs exposed through karaf dependency on pax-web-jsp

---

distribution/common/src/main/resources/etc/log4j2.config.xml
distribution/common/src/main/resources/etc/org.ops4j.pax.logging.cfg

Adds failover log back to logging configuration.
With the Karaf upgrade, there is an issue with the pax logging configuration that makes it unavailable to use through our default configuration, however, when using the log4j2.config.xml file failover seems to be functional (though errors populate the log).
@emmberk 
@mcalcote 
@coyotesqrl
@figliold 
- Create a disk image and mount it (Here's an example of how to do so on a mac: https://support.apple.com/kb/PH22247?locale=en_US&viewlocale=en_US)
- Unzip the Alliance
- Configure the Alliance's logging configuration per the documentation and setup the securityMain appender to write to a log file inside of the disk image
- Start up the Alliance
- Verify logs are written to the security log inside the disk image
- Begin to fill up the disk …

CAL-321 Adds failover log back to logging config

---

catalog/imaging/imaging-plugin-nitf/src/test/groovy/org/codice/alliance/plugin/nitf/NitfPreStoragePluginSpec.groovy
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/image/TextAttributeTest.java
catalog/security/banner-marking/src/test/groovy/org/codice/alliance/security/banner/marking/BannerCommonMarkingExtractorSpec.groovy
catalog/security/banner-marking/src/test/groovy/org/codice/alliance/security/banner/marking/BannerMarkingsSpec.groovy
catalog/security/banner-marking/src/test/groovy/org/codice/alliance/security/banner/marking/Dod520001MarkingExtractorSpec.groovy
catalog/security/banner-marking/src/test/groovy/org/codice/alliance/security/banner/marking/ValidationErrorSpec.groovy
pom.xml

- Updates Surefire to include Spock tests that end in `*Spec.class`.
- Removes unused surefire includes
- Renames some tests classes to comply with test guide lines
@vinamartin @lessarderic @emmberk 
@coyotesqrl
@lessarderic
Run unit tests to ensure coverage numbers are still met.
[CAL-322](https://codice.atlassian.net/browse/CAL-322)

CAL-322 Update Surefire to account for Spock tests

---

dependency-check-maven-config.xml

Added another CVE to the suppression list for geowebcache.
@clockard
@coyotesqrl
@stustison
`[ERROR] One or more dependencies were identified with vulnerabilities that have a CVSS score greater then '7.0': 
[ERROR] 
[ERROR] geowebcache-server-standalone-0.7.0.war: gwc-sqlite-1.9.1.jar: CVE-2017-10989
[ERROR] geowebcache-server-standalone-0.7.0.war: sqlite-jdbc-3.8.6.jar: CVE-2017-10989`
https://github.com/codice/alliance/blob/master/dependency-check-maven-config.xml#L279
[CAL-311](https://codice.atlassian.net/browse/CAL-311)

CAL-311 Updated suppressions for geowebcache based on latest owasp findings

---

Jenkinsfile

Added `-DretryFailedDeploymentCount=10` to the deploy command
@oconnormi @clockard @shaundmorris @LinkMJB 
@codice/build 
This change matches the command used in the legacy jenkins deploy jobs.

CAL-299 Update deploy command to retry failed deployments

---

catalog/security/banner-marking/src/main/java/org/codice/alliance/security/banner/marking/BannerMarkings.java

change ClassificationLevel and SciControl to be public instead of package-private
@coyotesqrl 
@rzwiefel 
@bdeining
@jlcsmith
Run unit tests and itests.
[CAL-325](https://codice.atlassian.net/browse/CAL-325)

CAL-325 change ClassificationLevel and SciControl to be public instead of package-private

---

catalog/imaging/imaging-actionprovider-chip/pom.xml
catalog/imaging/imaging-actionprovider-chip/src/main/java/org/codice/alliance/imaging/chip/actionprovider/ImagingChipActionProvider.java
catalog/imaging/imaging-actionprovider-chip/src/main/webapp/js/chipping.js

* Fixed imaging chip to return remote url 
This is a workaround for not being able to download the overview for a remote resource in order to chip it. The workaround being we now route the user directly to the system containing the resource. 
@lcrosenbu @bdeining 
@jlcsmith
@coyotesqrl 
Ensure chipping url for remote source is correct. 
[CAL-119](https://codice.atlassian.net/browse/CAL-119)

CAL-119 Fixed imaging chip to return remote url

---

catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/AbstractNitfMetacardType.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/StdidcAttribute.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/TreDescriptor.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/common/StdidcAttributeTest.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/gmti/GmtiMetacardTypeTest.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/image/ImageMetacardTypeTest.java
distribution/docs/src/main/resources/_contents/_formats/supported-file-formats-contents.adoc

Add nitf support for STDIDC
- Also set the location.country-code based on the STDIDC_COUNTRY
@emmberk @mcalcote 
@bdeining
@coyotesqrl
Install alliance and ingest a nitf with a populated  stdidc tre
Verify that the ext.nitf.stdidc.country is populated with a 2 character country code
Verify that the location.country-code is populated with a 3 character country code
[CAL-333](https://codice.atlassian.net/browse/CAL-333)

CAL-333 Add nitf support for STDIDC

---

pom.xml

- Replaces references to `localhost` in documentation example URLs to `{FQDN}:{PORT}` to reflect likely system changes made at install. 
- disabled these example links so they will not link to unresolvable URLs.
@mcalcote @vinamartin @emmberk @Lambeaux @jrnorth @ahoffer 
@clockard
@coyotesqrl
@lessarderic
@pklinef
@shaundmorris
@stustison
- builds successfully
- references to `localhost:8993` or `localhost:8991` replaced with new values of maven property.
[DDF-3227](https://codice.atlassian.net/browse/DDF-3227)
[CAL-327](https://codice.atlassian.net/browse/DDF-327)
[documentation.pdf](https://github.com/codice/alliance/files/1278685/documentation.pdf)
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment …

CAL-327 replaced 'localhost' in example URLs in docs

---

catalog/security/banner-marking/pom.xml
catalog/security/banner-marking/src/main/java/org/codice/alliance/security/banner/marking/BannerCommonMarkingExtractor.java
catalog/security/banner-marking/src/main/java/org/codice/alliance/security/banner/marking/MarkingMismatchException.java
catalog/security/banner-marking/src/test/groovy/org/codice/alliance/security/banner/marking/BannerCommonMarkingExtractorSpec.groovy
distribution/docs/src/main/jdocs/content/_banner-markings/banner-markings-extractor-contents.adoc
distribution/docs/src/main/jdocs/content/_banner-markings/banner-markings-intro-contents.adoc
distribution/sdk/pom.xml
distribution/sdk/sample-content-metadata-extractor/pom.xml
distribution/sdk/sample-content-metadata-extractor/src/main/java/org/codice/alliance/sdk/extraction/SampleContentMetadataExtractor.java
distribution/sdk/sample-content-metadata-extractor/src/main/resources/OSGI-INF/blueprint/blueprint.xml
distribution/sdk/sdk-app/src/main/resources/features.xml
distribution/test/itests/test-itests-alliance/src/test/java/org/codice/alliance/test/itests/BannerMarkingsTest.java

Sets the Banner Markings extractor to throw a runtime exception and fail the ingest when security markings derived from the banner markings do not match those already present on a metacard (which would have been derived from other means). The reason for this is that if there is a mismatch in derived markings, it could be caused by an error when the document had markings updated and the true markings of the document cannot be determined. The ingest is rejected to avoid a data spill.
@AzGoalie 
@ahoffer 
@mweser 
@jhunzik 
@coyotesqrl
@stustison
@bdeining 
Attempt to ingest a metacard that will have mismatch markings extracted from the metadata and the banner markings. The ingest should fail.
[CAL-331](https://codice.atlassian.net/browse/CAL-331)

CAL-331 Banner markings extractor rejects when conflicting security markings found

---

Jenkinsfile

The static analysis step is now quality analysis and security analysis steps. The quality checks have been moved after the deploy step and codecov was added as another parallel task. The jenkinsfile was also formatted.
@emanns95 @oconnormi @LinkMJB 
@clockard @shaundmorris @rzwiefel 
Run a multibranch pipeline build with this jenkinsfile
Any background context you want to provide?
The quality analysis stage contains items that should inform the development team without failing the build. However the security analysis stage must still be passed for the build to deploy.
[CAL-351](https://codice.atlassian.net/browse/CAL-351)

(0.3.x) CAL-351 Separated static analysis into two steps, formatted jenkinsfile, added Codecov check

---

distribution/docs/src/main/resources/content/_configuring/banner-markings-content-extractor.adoc

fixes a malformed link in documentation.
@mcalcote @vinamartin @ahoffer 
@clockard
@coyotesqrl
@lessarderic
@pklinef
@rzwiefel
@shaundmorris
-builds successfully
-link works
n/a

CAL-291 fix typo in docs, broken link

---

catalog/imaging/imaging-actionprovider-chip/pom.xml
catalog/imaging/imaging-actionprovider-chip/src/main/java/org/codice/alliance/imaging/chip/actionprovider/ImagingChipActionProvider.java
catalog/imaging/imaging-actionprovider-chip/src/main/resources/chipping.html
catalog/imaging/imaging-actionprovider-chip/src/main/webapp/js/chipping.js
catalog/imaging/imaging-actionprovider-chip/src/test/groovy/org/codice/alliance/imaging/chip/actionprovider/ImageChipActionProviderSpec.groovy
catalog/imaging/imaging-actionprovider-chip/src/test/java/org/codice/alliance/imaging/chip/actionprovider/ImageChipActionProviderTest.java
catalog/imaging/imaging-transformer-chipping/src/main/java/org/codice/alliance/imaging/chip/transformer/CatalogInputAdapter.java
catalog/imaging/imaging-transformer-chipping/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/imaging/imaging-transformer-chipping/src/test/java/org/codice/alliance/imaging/chip/transformer/CatalogInputAdapterTest.java

- Fixed handling resources from remote sources in the imaging-transformer-chipping
- The chipping transformer now specifies the source when retrieving the overview, original, and NITF from the Catalog.
- Fixed fetching the overview image for remote resources in the imaging-actionprovider-chip
- The chipping UI now uses the source name to get the overview image instead of assuming a local source.
- Updated the imaging-actionprovider-chip to better parse the chipping url from the derived resource uris if possible
- More error handling was added, and the parsing logic was updated to grab the source id from the derived image URI instead of from the metacard source id.
- Updated the components-font-awesome version in imaging-actionprovider-chip to match the pom
@peterhuffer @AzGoalie …

[0.3.x] CAL-355 Fixed Download Chip as JPEG and as NITF

---

catalog/video/video-mpegts-stream/pom.xml
libs/stanag4609/src/main/java/org/codice/alliance/libs/stanag4609/Stanag4609TransportStreamParser.java

Handles a country code that may not be UTF-8 encoded by detecting its encoding.
Uses : https://github.com/codice/ddf/pull/2426
@brendan-hofmann @glenhein 
@ahoffer @mcalcote @garrettfreibott 
@rzwiefel 
@lessarderic
[CAL-353](https://codice.atlassian.net/browse/CAL-353)

[0.3.x] CAL-353 Handles non-UTF8 country codes

---

catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/image/NitfImageTransformer.java
catalog/video/video-mpegts-transformer/src/main/java/org/codice/alliance/transformer/video/MpegTsInputTransformer.java
distribution/test/itests/test-itests-dependencies-app/src/main/filtered-resources/features.xml
pom.xml

Update MpegTsInputTransformer to use correct DCMI data type
@emmberk 
@bdeining
@lessarderic
Install Alliance and start the Video app
Ingest an Mpeg ts file and verify you can search and find the metacard.
[CAL-361](https://codice.atlassian.net/browse/CAL-361)

[0.3.x] CAL-361 Update MpegTsInputTransformer to use correct DCMI data type

---

Jenkinsfile

Changes the node security scan to only scan projects that are actually packaging dependencies
@mcalcote @LinkMJB 
@clockard @shaundmorris 
[CAL-362](https://codice.atlassian.net/browse/CAL-362)

CAL-362 Updated nsp Static Analysis stage to only scan projects using browserify or webpack

---

distribution/test/itests/test-itests-alliance/pom.xml
distribution/test/itests/test-itests-dependencies-app/pom.xml
distribution/test/itests/test-itests-dependencies-app/src/main/filtered-resources/features.xml

Updates the maven coordinates of DDF versions of Restito and RestAssured as a follow on to https://github.com/codice/ddf/pull/2349.
@tbatie 
@AzGoalie 
@coyotesqrl
@rzwiefel 
[CAL-345](https://codice.atlassian.net/browse/CAL-345)

CAL-345 Update pom and feature files to reflect new third-party module maven coordinates

---

pom.xml

Replaces inconsistent references to the DDF_HOME directory with a maven property to ensure consistent usage. 
@mcalcote @vinamartin @ahoffer @rzwiefel @garrettfreibott @emmberk 
@clockard
@coyotesqrl
@lessarderic
@pklinef
@rzwiefel
@shaundmorris
- All references to `${branding}_HOME`, `INSTALL_HOME`, or `INSTALLATION_DIR` (or others) have been replaced with the ${home_directory} property.
[DDF-3391](https://codice.atlassian.net/browse/DDF-3391)
(Depends on changes from https://github.com/codice/ddf/pull/2538
[CAL-364](https://codice.atlassian.net/browse/CAL-364)
- ❓ (Question Mark) …

[0.3.x] CAL-364 Standardized docs references to ALLIANCE_HOME directory

---

distribution/docs/src/main/resources/content/_metadataAttributes/NITF-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_Header-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_Segment_Graphic-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_Segment_Image-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_Segment_Label-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_Segment_Symbol-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_Segment_Text-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_TRE_ACFTB-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_TRE_AIMIDB-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_TRE_CSDIDA-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_TRE_CSEXRA-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_TRE_HISTOA-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_TRE_MTIRPB-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_TRE_PIAIMC-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_TRE_PIAPRD-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_TRE_PIATGB-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_TRE_STDIDC-table.adoc

This PR adds Documentation for NITF FSCTLH and FSREL mappings.
@peterhuffer @vinamartin 
@bdeining
@clockard
Build the Documentation, and check that the 4 new rows are added to the `NITF Header Attribute Mappings` table.
[documentation.zip](https://github.com/codice/alliance/files/1432296/documentation.zip)
[CAL-348](https://codice.atlassian.net/browse/CAL-348)

[0.3.x] CAL-348 Added Documentation for NITF FSCTLH and FSREL mappings

---

Jenkinsfile

Updating the sonar coverage exclusion helps improve coverage by avoiding files that should not be analyzed by sonarqube. This includes .adoc .js .xml as well as JAXB and WSDL directories. 
@oconnormi @vinamartin 
@codice/build 
@clockard @lessarderic @shaundmorris 
This exclusion pattern can be seen in the locally running/succeeding DDF sonar job.
On DDF, this pattern helped improve the coverage from 48% to 63%.
- ❗ (Exclamation Mark) This comment …

CAL-351 Update sonar exclusion pattern to improve coverage

---

catalog/security/banner-marking/src/main/java/org/codice/alliance/security/banner/marking/BannerMarkings.java
catalog/security/banner-marking/src/test/groovy/org/codice/alliance/security/banner/marking/BannerMarkingsSpec.groovy

Adds support for parsing U//FOUO in the BannerMarkings parser.
@bdeining 
@glenhein 
@coyotesqrl
@stustison
Full build with tests. 
[CAL-372](https://codice.atlassian.net/browse/CAL-372)

CAL-372 Security Marking parser support for U//FOUO data

---

Jenkinsfile

Several maven commands in the Jenkinsfile were not being run in batch-mode. This change updates them all for consistency. This also should reduce log output and size.
@mackncheesiest @LinkMJB @oconnormi 
@codice/build 
@clockard @shaundmorris
Adding this `-B` to the other maven commands greatly reduced log size.

CAL-351 Update Jenkinsfile maven commands to all run in batch-mode

---

distribution/common/src/main/resources/common-bin.xml

It excludes the Branding.txt file from DDF when building the distro.
@emanns95 
@tbatie 
@Lambeaux 
@clockard
@figliold
Build and unzip the distro. Verify that the Branding.txt file at the root says Alliance.
[CAL-377](https://codice.atlassian.net/browse/CAL-377)
[DDF-3447](https://codice.atlassian.net/browse/DDF-3447)

[0.3.x] CAL-377 Exclude Branding.txt from DDF when building the distro

---

distribution/common/src/main/resources/common-bin.xml

It excludes the Branding.txt file from DDF when building the distro.
@emanns95 
@tbatie 
@Lambeaux 
@clockard
@figliold
Build and unzip the distro. Verify that the Branding.txt file at the root says Alliance.
[CAL-377](https://codice.atlassian.net/browse/CAL-377)
[DDF-3447](https://codice.atlassian.net/browse/DDF-3447)

CAL-377 Exclude Branding.txt from DDF when building the distro

---

dependency-check-maven-config.xml
pom.xml

Backport for https://github.com/codice/alliance/pull/464
Suppresses the Xerces warning since it does not apply to Alliance.
@emmberk @mcalcote @vinamartin 
@coyotesqrl 
@shaundmorris
[CAL-380](https://codice.atlassian.net/browse/CAL-380)

[0.3.x]CAL-380 Suppressed warning for Xerces OWASP finding (#464)

---

distribution/console-branding/src/main/resources/org/apache/karaf/branding/branding.properties

Removes hardcoded admin console link on console.
@emanns95
@tbatie
@djblue
@clockard
@figliold
Unzip distro and check console, it should no longer show `Open a browser to https://localhost:8993/admin to access the Admin Console.`
[CAL-383](https://codice.atlassian.net/browse/CAL-383)

[0.3.x] CAL-383 Removed hardcoded admin console link on console

---

distribution/console-branding/src/main/resources/org/apache/karaf/branding/branding.properties

Removes hardcoded admin console link on console.
@emanns95
@tbatie
@djblue
@clockard
@figliold
Unzip distro and check console, it should no longer show `Open a browser to https://localhost:8993/admin to access the Admin Console.`
[CAL-383](https://codice.atlassian.net/browse/CAL-383)

CAL-383 Removed hardcoded admin console link in console

---

dependency-check-maven-config.xml

Reverts this PR https://github.com/codice/alliance/pull/451 based on the Solr 6.6.2 upgrade (https://github.com/codice/ddf/pull/2698)
@brjeter @mcalcote 
@coyotesqrl
@figliold

CAL-373 Removes OWASP suppression for Solr 6.6.1

---

catalog/plugin/catalog-plugin-defaultsecurityattributevalues/pom.xml
catalog/plugin/catalog-plugin-defaultsecurityattributevalues/src/main/java/org/codice/alliance/catalog/plugin/defaultsecurity/DefaultSecurityAttributeValuesPlugin.java
catalog/plugin/catalog-plugin-defaultsecurityattributevalues/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/plugin/catalog-plugin-defaultsecurityattributevalues/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/plugin/catalog-plugin-defaultsecurityattributevalues/src/test/java/org/codice/alliance/catalog/plugin/defaultsecurity/DefaultSecurityAttributeValuesPluginTest.java
distribution/docs/src/main/resources/content/_plugins/default-attribute-plugin.adoc
distribution/docs/src/main/resources/content/_tables/DefaultAttributeValuesPlugin.adoc
pom.xml

This PR updates the DefaultSecurityAttributeValuesPlugin to grab the system high attribute values from the users.attributes file instead of the user's claims.
@peterhuffer @AzGoalie @oconnormi @Lambeaux @ryeats
@clockard
@lessarderic
This PR is dependent on https://github.com/codice/ddf/pull/2695.
Confirm that metacard security attributes are updated as expected on ingested metacards when the `DefaultSecurityAttributeValuesPlugin` configuration is updated.
[CAL-375](https://codice.atlassian.net/browse/CAL-375)

[0.3.x] CAL-375 Updated the DefaultSecurityAttributeValuesPlugin to use the system high values from the etc/users.attributes file

---

catalog/security/banner-marking/pom.xml
catalog/security/banner-marking/src/main/java/org/codice/alliance/security/banner/marking/AeaMarking.java
catalog/security/banner-marking/src/main/java/org/codice/alliance/security/banner/marking/AeaType.java
catalog/security/banner-marking/src/main/java/org/codice/alliance/security/banner/marking/BannerCommonMarkingExtractor.java
catalog/security/banner-marking/src/main/java/org/codice/alliance/security/banner/marking/BannerMarkings.java
catalog/security/banner-marking/src/main/java/org/codice/alliance/security/banner/marking/BannerValidator.java
catalog/security/banner-marking/src/main/java/org/codice/alliance/security/banner/marking/ClassificationLevel.java
catalog/security/banner-marking/src/main/java/org/codice/alliance/security/banner/marking/DissemControl.java
catalog/security/banner-marking/src/main/java/org/codice/alliance/security/banner/marking/Dod520001MarkingExtractor.java
catalog/security/banner-marking/src/main/java/org/codice/alliance/security/banner/marking/MarkingExtractor.java
catalog/security/banner-marking/src/main/java/org/codice/alliance/security/banner/marking/MarkingType.java
catalog/security/banner-marking/src/main/java/org/codice/alliance/security/banner/marking/OtherDissemControl.java
catalog/security/banner-marking/src/main/java/org/codice/alliance/security/banner/marking/PortionMarkings.java
catalog/security/banner-marking/src/main/java/org/codice/alliance/security/banner/marking/SapControl.java
catalog/security/banner-marking/src/main/java/org/codice/alliance/security/banner/marking/SciControl.java
catalog/security/banner-marking/src/test/groovy/org/codice/alliance/security/banner/marking/BannerCommonMarkingExtractorSpec.groovy
catalog/security/banner-marking/src/test/groovy/org/codice/alliance/security/banner/marking/BannerMarkingsSpec.groovy
catalog/security/banner-marking/src/test/groovy/org/codice/alliance/security/banner/marking/Dod520001MarkingExtractorSpec.groovy
catalog/security/banner-marking/src/test/groovy/org/codice/alliance/security/banner/marking/PortionMarkingsSpec.groovy

Adds ability to parse portion marking style security attributes.
@bdeining 
@adimka 
@coyotesqrl
@stustison
Full build with tests.
This PR expands the capabilities that existed in the BannerMarkings parser to handle the abbreviated forms used with portion marks.
[CAL-384](https://codice.atlassian.net/browse/CAL-384)

CAL-384 Add parsing for portion marks

---

catalog/core/catalog-core-api-impl/src/main/java/org/codice/alliance/catalog/core/api/impl/types/IsrAttributes.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/CsexraAttribute.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/common/CsexraAttributeTest.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/image/ImageInputTransformerTest.java
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_TRE_CSEXRA-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/isr-attributes-table.adoc

Change NIIRS values from integers to floats.
@emmberk @peterhuffer @troymohl 
@bdeining
@beyelerb
@lessarderic
1. Install Alliance
2. Ingest a NITF that contains a NIIRS value
3. Verify when searching that the NITF has the proper NIIRS value represented as a float.
[CAL-391](https://codice.atlassian.net/browse/CAL-391)

CAL-391 Changed NIIRS values from int to float.

---

catalog/imaging/imaging-transformer-chipping/src/main/java/org/codice/alliance/imaging/chip/transformer/CatalogOutputAdapter.java

Backport of https://github.com/codice/alliance/pull/482
Closes an input stream in `CatalogOutputAdapter` and fixed a SonarQube finding
@brjeter @idperez 
@coyotesqrl
@rzwiefel
Full build
[CAL-389](https://codice.atlassian.net/browse/CAL-389)

[0.3.x] CAL-389 Ensure that inputstream is closed in CatalogOutputAdapter

---

catalog/imaging/imaging-transformer-chipping/src/main/java/org/codice/alliance/imaging/chip/transformer/CatalogOutputAdapter.java

Closes an input stream in `CatalogOutputAdapter` and fixed a SonarQube finding
@brjeter @idperez 
@coyotesqrl
@rzwiefel
Full build
[CAL-389](https://codice.atlassian.net/browse/CAL-389)

CAL-389 Ensure that inputstream is closed in CatalogOutputAdapter

---

catalog/pom.xml
dependency-check-maven-config.xml
pom.xml

- Removes beanutils from the project since it's not used and the maven property for the version points to an old version **causing the build to fail** on an OWASP error.
- Also suppressing this CVE because OWASP still fails because it looks at the DDF version to determine the vulnerability.
@mackncheesiest 
@bdeining 
@clockard 
[CAL-397](https://codice.atlassian.net/browse/CAL-397)

[0.3.x]CAL-397 Removing commons-beanutils from the project

---

catalog/pom.xml
dependency-check-maven-config.xml
pom.xml

Forward-port for https://github.com/codice/alliance/pull/501
- Removes beanutils from the project since it's not used and the maven property for the version points to an old version **causing the build to fail** on an OWASP error.
- Also suppressing this CVE because OWASP still fails because it looks at the DDF version to determine the vulnerability.
@mackncheesiest 
@bdeining 
@clockard 
[CAL-397](https://codice.atlassian.net/browse/CAL-397)

CAL-397 Removing commons-beanutils from the project

---

libs/klv/src/main/java/org/codice/alliance/libs/klv/AlphanumericDistinctKlvProcessor.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/DistinctKlvProcessor.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/DistinctSingleKlvProcessor.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/SecurityInformationKlvProcessor.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/UnionKlvProcessor.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/Utilities.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/AlphanumericDistinctKlvProcessorTest.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/DistinctKlvProcessorTest.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/UtilitiesTest.java

- Filters out blank values for metacard attributes being set from KLV data
- Filters out non-alphanumeric values for dissemination and SCI Controls from KLV data
@glenhein @blen-desta 
@bdeining 
@coyotesqrl 
- Full build
- Install Alliance then start the `video-app`
- Test ingesting video files of `mpegts` format with invalid klv values
- Verify they can be ingested and the invalid values are not set on the metacard
Various `mpegts` files were failing to ingest
[CAL-390](https://codice.atlassian.net/browse/CAL-390)

[0.3.x]CAL-390 Add validation for KLV processing for dissemination and SCI Controls

---

pom.xml

See: https://github.com/vackosar/gitflow-incremental-builder/issues/15#issuecomment-318679437
Updates default GIB behavior to perform a full build if it loses git context
@oconnormi @lessarderic @shaundmorris @vinamartin 
@lessarderic
@shaundmorris
Perform PR build on CI environment
Perform manual GIB enabled build (use options: `-Dgib.enabled=true -Dgib.referenceBranch=refs/remotes/origin/master`)
See: https://trello.com/c/7iBsxkdi
- https://codice.atlassian.net/projects/CAL/issues/CAL-395
- [N/A] Documentation Updated
- [N/A] Update / Add Unit Tests
- [N/A] Update / Add Integration Tests
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment …

CAL-395 Set gib.failOnError=false

---

libs/klv/src/main/java/org/codice/alliance/libs/klv/AlphanumericDistinctKlvProcessor.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/DistinctKlvProcessor.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/DistinctSingleKlvProcessor.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/SecurityInformationKlvProcessor.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/UnionKlvProcessor.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/Utilities.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/AlphanumericDistinctKlvProcessorTest.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/UtilitiesTest.java

forward-port for https://github.com/codice/alliance/pull/491
- Filters out blank values for metacard attributes being set from KLV data
- Filters out non-alphanumeric values for dissemination and SCI Controls from KLV data
@glenhein @blen-desta 
@bdeining 
@coyotesqrl 
- Full build
- Install Alliance then start the `video-app`
- Test ingesting video files of `mpegts` format with invalid klv values
- Verify they can be ingested and the invalid values are not set on the metacard
Various `mpegts` files were failing to ingest …

CAL-390 Add validation for KLV processing for dissemination and SCI Controls

---

Jenkinsfile

Suppresses lines of the form 
```
18:43:23 [INFO] Downloading: http://NEXUS/PATH/TO/ARTIFACT
18:43:23 [INFO] Downloaded: http://NEXUS/PATH/TO/ARTIFACT (27 KB at 985.4 KB/sec)
```
from the Jenkins Pipeline build logs
@vinamartin @blen-desta @oconnormi @mcalcote @LinkMJB 
@bdeining
@clockard
It has been verified both on a downstream project and in [CAL master](https://github.com/codice/alliance/commit/4f9e0c933d3dc541d88b838e567b521d7d878f72) that only the desired logs are suppressed.
As a bonus, this also brings the 0.3.x pipeline up to date with master with regards to #477
[CAL-392](https://codice.atlassian.net/browse/CAL-392)

[0.3.x] CAL-392 Suppress 'Downloading/Downloaded' status lines in logs

---

pom.xml

Upgrade the node version to comply with yarn
@LinkMJB @vinamartin 
@clockard 
This upgrade is to get rid of the errors we get from yarn:
`[ERROR] warning You are using Node "7.1.0" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || ^8.0.0"`
[CAL-398](https://codice.atlassian.net/browse/CAL-398)

CAL-398 Update node version to comply with yarn

---

catalog/imaging/imaging-actionprovider-chip/src/main/webapp/js/chipping.js

**What does this PR do?**
This PR fixes an issue with the chipping function that prevents the user from selecting the area of an image unless the first coordinate specified is the top-left one. 
**Who is reviewing it?** 
@emmberk 
@peterhuffer 
**Choose 2 committers to review/merge the PR.**
@bdeining 
@clockard
**How should this be tested?**
Ingest a valid NITF file. Navigate to the file inspector in Intrigue. Select Chip Image under the Actions tab and create a bounding box by dragging from all possible directions. Confirm that the generated URL/JPEG/NITF file are correct. 
**What are the relevant tickets?**
[CAL-406](https://codice.atlassian.net/browse/CAL-406)

CAL-406 Updated Chipping.js to allow bounding selection from all directions

---

pom.xml

**Port to `master` of PR https://github.com/codice/alliance/pull/532**
Aligns with changes to displaying default URLs in documentation. See also PR https://github.com/codice/ddf/pull/2955
@clockard
@coyotesqrl
@lessarderic
@rzwiefel
@shaundmorris

CAL-291 fixed formatting for sample Alliance urls in docs

---

catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/NitfAttributeImpl.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/SegmentHandler.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/image/ImageAttribute.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/image/ImageInputTransformerTest.java

-Updates the NitfAttributeImpl class to allow the non-normalized (extension) field to contain a different value than the normalized/taxonomy field.
@derekwilhelm 
@dcruver 
@bdeining
@jaymcnallie
Run a full build, make sure all tests pass.
There are some attributes that use the same value for the normalized field as they do for the non-normalized (extension field). Sometimes the value of the normalized field is not the actual value that is stored in the NITF for that attribute, we should have the ability to allow the value of …

CAL-407 Allow the normalized and extension fields of a NITF attribute to contain different values

---

catalog/imaging/imaging-plugin-nitf/pom.xml
catalog/imaging/imaging-plugin-nitf/src/main/java/org/codice/alliance/plugin/nitf/NitfPostIngestPlugin.java
catalog/imaging/pom.xml
distribution/docs/src/main/resources/content/_dependency-list/alliance-dependency-list.adoc

Update jpeg2000 library to latest codice version which has a fix for an infinite loop problem
Depends on codice/jai-imageio-jpeg2000#3
@emmberk @peterhuffer
Choose 2 committers to review/merge the PR.
@bdeining
@lessarderic
How should this be tested? (List steps with links to updated documentation)
Ingest the nitf that caused infinite loop and verify it no longer is an issue. See me for dataset.
What are the relevant tickets?
[CAL-413](https://codice.atlassian.net/browse/CAL-413)

CAL-413 Update jpeg2000 library to latest codice version

---

catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/NitfAttribute.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/NitfAttributeImpl.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/SegmentHandler.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/image/GraphicAttribute.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/image/LabelAttribute.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/image/SymbolAttribute.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/image/TextAttribute.java

A line in SegmentHandler made an unchecked cast on an interface. Changed
the interface and implementing classes so that the cast was no longer
needed.
@emanns95 @peterhuffer @harrison-tarr @roelens8 
@clockard
@coyotesqrl
CI Build
[CAL-407](https://codice.atlassian.net/browse/CAL-407)

CAL-407 Fix unchecked cast in SegmentHandler

---

catalog/core/catalog-core-api-impl/src/main/java/org/codice/alliance/catalog/core/api/impl/types/Dod520001Attributes.java
catalog/core/catalog-core-api-impl/src/test/java/org/codice/alliance/catalog/core/api/impl/types/MetacardTypeAttributeTest.java
catalog/core/catalog-core-api/src/main/java/org/codice/alliance/catalog/core/api/types/Dod520001.java
catalog/security/banner-marking/pom.xml
catalog/security/banner-marking/src/main/java/org/codice/alliance/security/banner/marking/BannerCommonMarkingExtractor.java
catalog/security/banner-marking/src/main/java/org/codice/alliance/security/banner/marking/Dod520001MarkingExtractor.java
catalog/security/banner-marking/src/main/java/org/codice/alliance/security/banner/marking/MarkingExtractor.java
catalog/security/banner-marking/src/test/groovy/org/codice/alliance/security/banner/marking/BannerCommonMarkingExtractorSpec.groovy
distribution/sdk/sample-content-metadata-extractor/pom.xml
distribution/sdk/sample-content-metadata-extractor/src/main/java/org/codice/alliance/sdk/extraction/SampleContentMetadataExtractor.java
distribution/test/itests/test-itests-alliance/src/test/java/org/codice/alliance/test/itests/BannerMarkingsTest.java

Use the attribute descriptors already defined for attributes instead of redefining them. This ensures they are consistent.
@emmberk @peterhuffer @kcover 
@coyotesqrl
@figliold
Install and setup security defaults. You can use this profile 
```json
{
"TestUnclass": {
"guestClaims": {
"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier": "guest",
"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/role": "guest"
},
"systemClaims": {
"ownerProducer" : "USA",
"releasableTo": "USA",
"classification": "U"
},
"configs": []
}
}
```
Ingest a text file with banner markings. (first line is something like `TOP SECRET`)
Export the metacard xml and verify that the security markings are not duplicated.
[CAL-424](https://codice.atlassian.net/browse/CAL-424)

CAL-424 Update banner marking extractors to use common attribute descriptors

---

distribution/docs/src/main/resources/content/config.adoc

Adds `release-notes-url` property to docs config file to point to Alliance release notes page.
@clockard
@lessarderic
@shaundmorris
text replacement renders working link

CAL-291 added release notes URL to documentation

---

catalog/plugin/catalog-plugin-defaultsecurityattributevalues/src/main/java/org/codice/alliance/catalog/plugin/defaultsecurity/DefaultSecurityAttributeValuesPlugin.java
catalog/plugin/catalog-plugin-defaultsecurityattributevalues/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/plugin/catalog-plugin-defaultsecurityattributevalues/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/plugin/catalog-plugin-defaultsecurityattributevalues/src/test/java/org/codice/alliance/catalog/plugin/defaultsecurity/DefaultSecurityAttributeValuesPluginTest.java
distribution/docs/src/main/resources/content/_tables/DefaultAttributeValuesPlugin.adoc

Update how DefaultSecurityAttributeValuesPlugin is configured.
Should the SecurityAttributes usage/checks be replaced with AttributeRegistry lookup of the configured terms?
@emmberk @ryeats @peterhuffer @kcover 
@bdeining
@coyotesqrl
Unzip the alliance distro and put the following in a file called profiles.json in <installhome>/etc/ws-security/
```json
{
"TestUnclass": {
"guestClaims": {
"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier": "guest",
"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/role": "guest"
},
"systemClaims": {
"ownerProducer" : "USA",
"releasableTo": "USA",
"classification": "U"
},
"configs": []
}
}
```
Install Alliance and select the TestUnclass profile on the claims installer page.
Ingest a text or jpg file and verify that it has the three …

CAL-428 Update how DefaultSecurityAttributeValuesPlugin is configured

---

dependency-check-maven-config.xml

Suppress build failing CVEs that stems from pax-web-jsp-6.0.6.jar and its use in Apache Tomcat (which is not being used).
@ahoffer @mackncheesiest @clockard @oconnormi @rzwiefel @stustison
CI build to run OWASP
[CAL-396](https://codice.atlassian.net/browse/CAL-396)

CAL-396 Update dependency check suppressions

---

pom.xml

Allow RHEL Jenkins using Maven 3.5.0 to successfully build DDF. But we will need to verify that it doesn't break in other environment (especially Windows since I don't have Windows)
@jlcsmith @AzGoalie @ricklarsen
@millerw8
Verified that it build in Windows / Mac / Linux
It failed in RHEL when the version is at 1.7.26
Source of reference: asciidoctor/asciidoctorj#586
[CAL-434](https://codice.atlassian.net/browse/CAL-434)

CAL-434 Upgrade jruby version for doc build for RHEL

---

distribution/docs/pom.xml

Ensure that PDF generation only occurs when using the release profile. HTML docs will still be generated when building the docs module.
@ahoffer @austinsteffes @sblackmore
@codice/docs
@clockard @ricklarsen @rzwiefel
`mvn clean install` in \distribution\docs to confirm HTML docs are still generated
`mvn clean install -P release` in \distribution\docs to confirm both HTML and PDF docs are generated
This change reduced the standard build of the docs module by several minutes on my machine.
[CAL-435](https://codice.atlassian.net/browse/CAL-435)

CAL-435 Moved PDF generation to the release profile

---

distribution/alliance/pom.xml
distribution/alliance/src/main/filtered-resources/etc/org.apache.karaf.features.cfg

Once https://github.com/codice/ddf/pull/3230 gets into DDF, Alliance will be broken. This PR re-adds the ui as a distribution level boot feature to fix the problem.
@mackncheesiest 
@tbatie 
@bdeining
@pklinef
- build https://github.com/codice/ddf/pull/3230
- build Alliance
- ensure ui comes up and works correctly
[CAL-426](https://codice.atlassian.net/browse/CAL-426)

CAL-426 Adds UI as a distribution boot feature

---

catalog/imaging/imaging-actionprovider-chip/src/main/java/org/codice/alliance/imaging/chip/actionprovider/ImagingChipActionProvider.java
catalog/nsili/catalog-nsili-common/src/main/java/org/codice/alliance/nsili/common/ResultDAGConverter.java
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/LibraryImpl.java
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/NsiliLibraryImplTest.java

DDF-3817 introduced support for explicit internal and external url properties which is useful when an Alliance is behind a proxy and the URL a user sees is different than the local url Alliance uses.
@alexaabrd @SmithJosh @rzwiefel 
@bdeining
Build this PR on top of: https://github.com/codice/ddf/pull/3225 and follow the instructions in that PR
[CAL-438](https://codice.atlassian.net/browse/CAL-438)

CAL-438 Update Alliance to support separate external/internal urls

---

distribution/docs/pom.xml
distribution/docs/src/assembly/docs-export.xml
distribution/docs/src/main/resources/content/quickstart.adoc

- fixes template to work with changes made in DDF in PR https://github.com/codice/ddf/pull/3321. 
- creates a standalone Quick Start document.
@mcalcote @ahoffer @austinsteffes @rzwiefel @garrettfreibott 
@lessarderic
@rzwiefel
@shaundmorris
. (checkout and build changes on this branch: https://github.com/codice/ddf/pull/3321)
. build these changes
.. documentation.html should appear the same.
.. quickstart.html should build successfully. 
[DDF-3870](https://codice.atlassian.net/browse/DDF-3870)

CAL-291 added adoc file to create quick start document

---

pom.xml

added `deprecated` property to the pom file to resolve `${deprecated}` usage in documentation
@lessarderic
@rzwiefel
@shaundmorris
[DDF-3954](https://codice.atlassian.net/browse/CAL-3954)

CAL-291 added deprecation verbiage to pom file

---

Jenkinsfile

Removes the javadoc:aggregate step from the pipeline. This step is no longer needed.
@LinkMJB @oconnormi 
@lessarderic
@shaundmorris
The Jenkins pipeline is not used in CI at the moment
There has been recent CI instability in this maven execution. It is believed to no longer be needed, so we're removing it.
[DDF-3981](https://codice.atlassian.net/browse/DDF-3981)
- ❓ (Question Mark) This …

DDF-3981 Removed javadoc:aggregate step from pipeline

---

distribution/common/src/main/resources/common-bin.xml

This script is needed to run Alliance as a background process using the start.bat command.
This allows the system to be run with the start.bat scripts.
@clockard @rzwiefel @kcover @ahoffer @austinsteffes @peterhuffer @taz77 @kcrowe01
How should this be tested?
Build, unzip the distribution and confirm service.ps1 is present in the bin directory.

1.1.X CAL-458 Update common-bin to include DDF ps script

---

catalog/video/video-mpegts-stream/pom.xml
catalog/video/video-mpegts-stream/src/test/java/org/codice/alliance/video/stream/mpegts/plugins/FindChildrenStreamEndPluginTest.java
catalog/video/video-mpegts-stream/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker

Prevents overriding of the Security.getSystemSubject method in DDF. These changes are to fix unit tests to allow mocking of final methods and classes. 
@ethantmanns 
@jhunzik 
@coyotesqrl 
@tbatie 
Get changes and test respective unit tests
In reality, any user who could replace a secured piece of code would already have full access to the system and could do much more. That is why this issue is of low-priority.
[CAL-460](https://codice.atlassian.net/browse/CAL-460)
[DDF-4055](https://codice.atlassian.net/browse/DDF-4055)

[1.1.x]CAL-460 Changed to allow mocking of final methods/classes

---

Jenkinsfile

Decreases requested build container resources from 4 CPU's and 8GB of RAM, to 2 CPU's and 6GB of RAM. This will release resources back for other builds when it is not necessary for Alliance to build successfully
@oconnormi 
@clockard 
@mcalcote 
@clockard
@shaundmorris 
This will take effect on pipeline builds post-merge. We are already running using 'linux-medium' on the legacy Alliance builds, as well as PR builds.
[CAL-468](https://codice.atlassian.net/browse/CAL-468)

CAL-468 Decrease requested build container resources from linux-large to linux-medium

---

catalog/nsili/catalog-nsili-sourcestoquery-ui/pom.xml
catalog/video/video-admin-plugin/pom.xml
distribution/docs/src/main/resources/content/_reference/_dependency-list/alliance-dependency-list.adoc
pom.xml

Upgrade moment in NSILI code to 2.20.1 to get rid of a security vulnerability.
Note: When testing alliance as an NSILI source I receive 0 query results and get a series of exceptions printed in the client alliance. Since this occurs on 1.1.1 it is unrelated to my changes and I think should be handled in a separate PR if it can be reproduced. @beyelerb is making some changes in this area and said he would investigate this issue further.
@peterhuffer @emmberk @bakejeyner 
@beyelerb 
@clockard
Install alliance and start the NSILI app. To test the ability to query …

CAL-469 Upgrade moment in NSILI code to 2.20.1

---

catalog/imaging/pom.xml
distribution/docs/src/main/resources/content/_dependency-list/alliance-dependency-list.adoc

PR corresponds to https://github.com/codice/ddf/pull/3651
Upgrades Camel to 2.22.0
@emmberk @ryeats @kcover 
@clockard
@vinamartin
CI Build + itests
Verify ingesting of NITFs and NITF Chipping still work
Addresses vulnerabilities found from Sonatype
[CAL-467](https://codice.atlassian.net/browse/CAL-467)

CAL-467 Upgrade camel to 2.22.0

---

distribution/common/src/main/resources/etc/profiles/ha.json

Updates the ha profile to remove solr-server-standalone which was removed from DDF.
@figliold
@ethantmanns
@tyler30clemens
@clockard
@pklinef
No impact to production or HA since the entry removed was simply stopping the bundle if present.
PR build should be sufficient.
[CAL-471](https://codice.atlassian.net/browse/CAL-471)
[DDF-4136](https://codice.atlassian.net/browse/DDF-4136)

CAL-471 Updated ha profile because of solr-server-standalone removal

---

distribution/docs/src/main/resources/content/using.adoc

updates documentation templates to publish standalone User documentation. 
@mcalcote @ahoffer @garrettfreibott @austinsteffes 
@clockard
@lessarderic
@shaundmorris
Builds successfully and creates a `using.html` and a `using.pdf` (if built with the `release` profile)
Relies on changes found in this upstream PR: https://github.com/codice/ddf/pull/3761
[DDF-3887](https://codice.atlassian.net/browse/DDF-3887)
[CAL-447](https://codice.atlassian.net/browse/CAL-447)

CAL-447 updated docs template to publish user guide

---

catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/AbstractNitfMetacardType.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/TreDescriptor.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/complex/CmetaaAttribute.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/complex/CmetaaAttributeTest.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/gmti/GmtiMetacardTypeTest.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/image/ImageMetacardTypeTest.java
pom.xml

ABBREVIATED REVIEW BETWEEN 1.1.X AND MASTER
Link to 1.1.x PR: [#645](https://github.com/codice/alliance/pull/645)
Add support for the NITF CMETAA TRE.
@ryeats 
@dcruver 
@clockard
@jlcsmith 
This needs to be built with this imaging-nitf PR: [IMG-244 PR#190](https://github.com/codice/imaging-nitf/pull/190)
Ingest a NITF with a CMETAA TRE
Verify that the metacard has the "ext.nitf.cmetaa.*" attributes
[CAL-436](https://codice.atlassian.net/browse/CAL-436)
[IMG-244](https://codice.atlassian.net/browse/IMG-244)

CAL-436 - Add CMETAA TRE Support

---

distribution/test/itests/test-itests-alliance/pom.xml

This PR fixes the case where the build fails running mvn clean install when the solr executable is not present. 
@oconnormi @GabrielFabian 
@jlcsmith
@millerw8
Fresh clone / Delete Target directory and mvn clean install
[CAL-458](https://codice.atlassian.net/browse/CAL-458)

CAL-458 Fixed solr executable not being found

---

pom.xml

Upgrade Jacoco, codice-maven, codice-test, ac debugger versions in support of Java 11	
Updated ddf-parent to 1.5 and ddf-support to 2.3.16
@ethantmanns 
@jhunzik 
@AzGoalie 
@coyotesqrl
@figliold
@tbatie
- The PR build should be sufficient
[CAL-498](https://codice.atlassian.net/browse/CAL-498)
[DDF-4223](https://codice.atlassian.net/browse/DDF-4223)
- ❓ (Question Mark) This comment is to gain a …

[Java11] CAL-498 Upgrade Jacoco, codice-maven, codice-test, ac debugger versions in support of Java 11

---

distribution/docs/src/main/resources/content/_core-concepts/data-standards.adoc
distribution/docs/src/main/resources/content/_core-concepts/service-standards.adoc
distribution/docs/src/main/resources/content/_endpoints/nsili-endpoint.adoc
distribution/docs/src/main/resources/content/_managing/attributes-added-by-pre-ingest-plugins.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/isr-attributes-table.adoc
distribution/docs/src/main/resources/content/config.adoc

Adds a visual icon to mark external links that take the user away from the Alliance documentation.
(https://github.com/codice/ddf/pull/4053)
@mcalcote @ahoffer @austinsteffes @garrettfreibott @vinamartin @alexaabrd 
@clockard
@lessarderic
@shaundmorris
@vinamartin
- builds successfully
- icons added. 
[CAL-496](https://codice.atlassian.net/browse/CAL-496)
[DDF-4291](https://codice.atlassian.net/browse/DDF-4291)

CAL-496 added external link icon to external links in docs

---

catalog/nsili/catalog-nsili-source/src/main/java/org/codice/alliance/nsili/source/NsiliSource.java

- move the completionService instance to the submitQuery function
- makes the list with Futures and the completionService operate in the same context (thread) and stay in sync
@blen-desta
@brjeter
@Kjames5269
@clockard
@coyotesqrl
Deploy a version of Alliance and attempt multiple quick searches against a CSD source.  It should not lock anymore.
When searching the CSD the search can lock (i.e. does not complete). This can be reproduced by several consecutive clicks on the search/cancel search button when querying the CSD source. …

CAL-484 CSD Search lock (multithreading issue)

---

catalog/imaging/imaging-plugin-nitf/src/main/java/org/codice/alliance/plugin/nitf/NitfPostIngestPlugin.java
catalog/imaging/imaging-plugin-nitf/src/test/java/org/codice/alliance/plugin/nitf/NitfPostIngestPluginTest.java
catalog/imaging/imaging-postprocess-plugin-nitf/src/main/java/org/codice/alliance/plugin/nitf/NitfPostProcessPlugin.java
catalog/imaging/imaging-postprocess-plugin-nitf/src/test/groovy/org/codice/alliance/plugin/nitf/NitfPostProcessPluginSpec.groovy
catalog/imaging/imaging-service-impl/pom.xml
catalog/imaging/imaging-service-impl/src/main/java/org/codice/alliance/imaging/chip/service/impl/ChipServiceImpl.java
catalog/imaging/imaging-service-impl/src/test/java/org/codice/alliance/imaging/chip/service/impl/ChipServiceImplTest.java
catalog/imaging/imaging-transformer-chipping/src/main/java/org/codice/alliance/imaging/chip/transformer/CatalogOutputAdapter.java
catalog/imaging/imaging-transformer-chipping/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/imaging/imaging-transformer-chipping/src/test/java/org/codice/alliance/imaging/chip/transformer/CatalogOutputAdapterTest.java
catalog/video/video-security/pom.xml
catalog/video/video-security/src/test/java/org/codice/alliance/video/security/validator/videographer/VideographerValidatorTest.java
distribution/alliance/pom.xml

- This is a temporary fix to attempt to restrict the number of threads allowed to each of the image processing steps. The real fix for this code is to remove it from Alliance and have it run in a separate process or as a separate service.
@brjeter
@coyotesqrl
@stustison
@tbatie

CAL-502 restricted the number of threads allowed to do NITF operations

---

distribution/docs/src/main/resources/content/using.adoc

**Port to `1.1.x` of PR [#640](https://github.com/codice/alliance/pull/640)**
updates documentation templates to publish standalone User documentation. 
@mcalcote @ahoffer @garrettfreibott @austinsteffes 
@clockard
@lessarderic
@shaundmorris
Builds successfully and creates a `using.html` and a `using.pdf` (if built with the `release` profile)
Relies on changes found in this upstream PR: https://github.com/codice/ddf/pull/3761
[DDF-3887](https://codice.atlassian.net/browse/DDF-3887)
[CAL-447](https://codice.atlassian.net/browse/CAL-447)

CAL-447 updated docs template to publish user guide (#640)

---

distribution/docs/src/main/resources/content/_transformers/nitf-input-transformer.adoc

fixes a typo in the NITF transformer docs.
@ahoffer @austinsteffes @bakejeyner 
@clockard
@coyotesqrl
@lessarderic
@shaundmorris
verify content

CAL-291 fixed typo in NITF transformer docs

---

distribution/docs/src/main/resources/content/_metadataAttributes/attribute-mappings.adoc
distribution/docs/src/main/resources/content/metadata.adoc

**Port to `1.1.x` of PR [#639](https://github.com/codice/alliance/pull/639)**
updates documentation templates to publish standalone metadata reference.
@garrettfreibott @austinsteffes @bakejeyner 
@brjeter
@clockard
@lessarderic
@shaundmorris
@mcalcote 
metadata.html (and metadata.pdf if using the `-Prelease` profile) are published and available.
[CAL-452](https://codice.atlassian.net/browse/CAL-452)

CAL-452 updated docs templates to add metadata reference

---

distribution/docs/pom.xml
distribution/docs/src/main/resources/content/_endpoints/nsili-endpoint.adoc
distribution/docs/src/main/resources/content/integrating.adoc

**Port to `1.1.x` of PR [#651](https://github.com/codice/alliance/pull/639)**
Updates docs templates to publish standalone Integrator docs.
@garrettfreibott @bakejeyner @austinsteffes 
@mcalcote 
@brjeter
@clockard
@lessarderic
@shaundmorris
integrating.html file is generated during build; tests pass
[CAL-448](https://codice.atlassian.net/browse/CAL-448)

CAL-448 updated docs templates for standalone integrator docs (#651)

---

catalog/video/video-mpegts-transformer/src/main/java/org/codice/alliance/transformer/video/MpegTsInputTransformer.java
catalog/video/video-mpegts-transformer/src/test/java/org/codice/alliance/transformer/video/MpegTsInputTransformerTest.java

@ahoffer @tyler30clemens @austinsteffes 
@emmberk 
@vinamartin
- Install Alliance.
- `feature:install video-app`
- `catalog:ingest -t mpegts <path-to-mpegts-file>` (https://github.com/codice/alliance/blob/master/catalog/video/video-mpegts-stream/src/test/resources/Closed_Caption_EIA_MPEG2.ts can be used)
- Verify through Intrigue that the media type is `video/mp2t` instead of `application/octet-stream`
[CAL-506](https://codice.atlassian.net/browse/CAL-506)

[1.1.x]CAL-506 Update MpegTsInputTransformer to set media type to video/mp2t

---

catalog/imaging/imaging-actionprovider-chip/pom.xml
catalog/nsili/catalog-nsili-common/pom.xml
catalog/nsili/catalog-nsili-endpoint/pom.xml
dependency-check-maven-config.xml

https://github.com/codice/ddf/pull/4334 cleans up catalog core api dependencies and this pr addressed the now missing transitive dependences that were previously provided.
Also addressed owasp findings.
@peterhuffer @kcover
@paouelle 
@vinamartin
Good CI Build
[CAL-477](https://codice.atlassian.net/browse/CAL-477)

CAL-477 Declare dependencies that were received transitively

---

catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/AbstractNitfMetacardType.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/image/ImageMetacardType.java

Updates MetacardTypeImpl usage to reflect changes made in upstream DDF project.
Depends on: https://github.com/codice/ddf/pull/4271
@zta6
@leo-sakh
@bdeining
@coyotesqrl 
Full build with tests
Update required due to how implementation class from upstream was extended and used.
[CAL-508](https://codice.atlassian.net/browse/CAL-508)

CAL-508 Update for upstream MetacardTypeImpl changes

---

Jenkinsfile

Remove Coverity stage from the Jenkins file
@codice/build 
@LinkMJB 
@rymach
@jrnorth 
@vinamartin
@oconnormi 
Verification of the syntax on the build file should be sufficient
We haven't been able to build with Coverity in about a year
[CAL-505](https://codice.atlassian.net/browse/CAL-505)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codice/alliance/694)

CAL-505 removed Coverity stage from Jenkinsfile

---

dependency-check-maven-config.xml
distribution/docs/src/main/resources/content/_reference/_dependency-list/alliance-dependency-list.adoc

**PORT to `master` of PR #701**
fixes incorrect document type in dependency list docs. 
@ahoffer @bakejeyner @blen-desta @garrettfreibott 
@clockard
@lessarderic
@shaundmorris
builds successfully with dependency list included. 

CAL-291 fixed typo in dependency list docs and added a dependency check suppression

---

Jenkinsfile

The pipeline builds are constantly failing on Windows which prevents them from running the static analysis steps such as OWASP. We're temporarily skipping the windows build stages in the Jenkins builds until pipeline issues are resolved.
@brjeter
@clockard
@LinkMJB 
@shaundmorris 
Fixes: https://github.com/codice/alliance/issues/705

CAL-0705 Commented out the windows build stage until Jenkins issues are resolved

---

Jenkinsfile

The pipeline builds are constantly failing on Windows which prevents them from running the static analysis steps such as OWASP. We're temporarily skipping the windows build stages in the Jenkins builds until pipeline issues are resolved.
@brjeter
@clockard
@LinkMJB 
@shaundmorris 
Fixes: https://github.com/codice/alliance/issues/705

[1.1.x] CAL-0705 Commented out the windows build stage until Jenkins issues are resolved

---

libs/pom-fix-run/yarn.lock
pom.xml

DDF 2.13.7 is deployed.
Bumped DDF version in root POM from 2.13.6 to 2.13.7
@brjeter @clockard @shaundmorris

Bump DDF version to version 2.13.7

---

distribution/docs/pom.xml
distribution/docs/src/main/resources/content/config.adoc
pom.xml

Reconfigures the directory structure of the documentation build to include version number to prevent issues on quickbuilds or releases
@ahoffer @austinsteffes @Kjames5269 
@codice/build 
@codice/docs 
@brjeter
@clockard
@lessarderic
@mcalcote
(Depends on changes in this PR: https://github.com/codice/ddf/pull/4707)
- check out `master` branch
- build docs module with `mvn clean install`
- check out this branch
- build docs module with `mvn install` (leave previous build artifacts in target directory)
- smoke test
[CAL-516](https://codice.atlassian.net/browse/CAL-516)

[1.1.x] CAL-516 updated docs module to add version checking

---

distribution/docs/pom.xml
distribution/docs/src/main/resources/content/config.adoc

Reconfigures the directory structure of the documentation build to include version number to prevent issues on quickbuilds or releases
@ahoffer @austinsteffes @Kjames5269 
@codice/build 
@codice/docs 
@brjeter
@clockard
@lessarderic
@mcalcote
(Depends on changes in this PR: https://github.com/codice/ddf/pull/4712)
- check out `master` branch
- build docs module with `mvn clean install`
- check out this branch
- build docs module with `mvn install` (leave previous build artifacts in target directory)
- smoke test
[CAL-516](https://codice.atlassian.net/browse/CAL-516)

CAL-516 updated docs module to add version checking

---

catalog/core/catalog-core-api-impl/src/main/java/org/codice/alliance/catalog/core/api/impl/types/IsrAttributes.java
catalog/nsili/catalog-nsili-common/src/main/java/org/codice/alliance/nsili/common/ResultDAGConverter.java
catalog/nsili/catalog-nsili-common/src/test/java/org/codice/alliance/nsili/common/ResultDAGConverterTest.java
catalog/nsili/catalog-nsili-transformer/src/main/java/org/codice/alliance/nsili/transformer/DAGConverter.java
catalog/nsili/catalog-nsili-transformer/src/test/java/org/codice/alliance/nsili/transformer/DAGConverterTest.java

Changes the NSIL Transformer to map COMMON.subjectCategoryCode to the isr.nato-reporting-code. The old CAL-308 PR was closed and this one replaces it. Updated with the code formatting and review comments addressed from the previous PR.
@dcruver 
@troymohl
@ricklarsen 
@bdeining
@jlcsmith
Verify that the value(s) from subjectCategoryCode are set in isr.nato-reporting-code
(don't have test case available, verify the unit test and expected results and that it passes)
[CAL-308](https://codice.atlassian.net/browse/CAL-308)

CAL-308 Updated NSILI mapping of subjectCategoryCode in both directions

---

catalog/video/video-mpegts-transformer/src/main/resources/OSGI-INF/blueprint/blueprint.xml
libs/klv/src/main/java/org/codice/alliance/libs/klv/AlphanumericDistinctKlvProcessor.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/SecurityReleasingInstructionsKlvProcessor.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/Utilities.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/UtilitiesTest.java
pom.xml

adds a none check into the mpeginputtransformer
@brjeter @brendan-hofmann 
see me for testing protocol
#734 

[1.3.x] CAL-734 add none check on specific mpeg transformers

---

catalog/imaging/imaging-nitf-impl/pom.xml
catalog/nsili/catalog-nsili-endpoint/pom.xml
pom.xml

Upgrades Karaf to 4.2.3 and cleans up log4j versions
@bdeining
@beyelerb
@brjeter
@clockard
@coyotesqrl
@figliold
@jaymcnallie
@jlcsmith
@kcwire
@lessarderic
@millerw8
@mrmateo
@pklinef
@rzwiefel
@shaundmorris
@stustison
@tbatie
@vinamartin
Full Build / Install
https://github.com/codice/alliance/issues/725

CAL-0725 Karaf Upgrade

---

catalog/nsili/nsili-app/src/main/resources/features.xml
distribution/sdk/sample-content-metadata-extractor/pom.xml
distribution/test/itests/test-itests-dependencies-app/src/main/filtered-resources/features.xml
pom.xml

Upgrades Guava to `25.1-jre`. Depends on https://github.com/codice/ddf/pull/5379. 
@ryeats 
@brianfelix 
@bdeining
@stustison
- Full build. ✅ 
- Container starts up, Intrigue is usable logged in. ✅ 
- Features that depend on older Guava versions can be installed (i.e. camel-protobuf). ✅ 
Will create a ticket upon request if we deem it necessary.

Upgrade Guava to 25.1

---

Jenkinsfile
pom.xml

Upgraded depdency-check from 3.1.1 to 5.2.2
Updated dependency-check stage to be more efficient. Instead of using Maven verify phase, directly call dependency-check.
Re-adds dependency-check into the build with the -POwasp profile
The build does not fail on CVEs currently, instead it enables reporting to take place. Need to consider our process improvements for those cases. It seems most PRs will be unrelated to the CVE that was reported yesterday.
Also switches to the JSON feed rather than the removed XML feed that was causing builds to fail
Removed obsolete NodeJsSecurity stage
@TonyMorrison 
@AdamBurstynski 
@bakejeyner …

CAL-753 Upgraded to DDF-Parent 1.0.8 and Dependency-Check 5.2.2

---

catalog/ddms/catalog-ddms-transformer/src/test/java/org/codice/alliance/ddms/v2/Ddms20InputTransformerTest.java
pom.xml

Updates Alliance's DDF version to 2.21.0-SNAPSHOT and fixes a compilation error due to the update.
@bdeining
@shaundmorris

Update DDF version to 2.21.0-SNAPSHOT

---

Jenkinsfile

`1.13.1-SNAPSHOT` artifacts aren't being deployed to http://artifacts.connexta.com/content/groups/public.
Kudus to @AdamBurstynski for finding the solution 👏 
@AdamBurstynski 
@blen-desta
@shaundmorris
I don't think we can test this before merging and confirming that `1.13.1-SNAPSHOT` artifacts are deployed to http://artifacts.connexta.com/content/groups/public.
`+` = one or more
`*` = zero or more
https://github.com/codice/ddf/blob/67f76f9eb62a8df9cb31038fa7b770a9cacf9889/Jenkinsfile#L149

Update Jenkinsfile so that 1.13.x is deployed

---

catalog/imaging/imaging-app/src/main/resources/features.xml
catalog/video/video-mpegts-stream/pom.xml
distribution/install-profiles/src/main/resources/features.xml
distribution/test/itests/test-itests-alliance/pom.xml
distribution/test/itests/test-itests-common/src/main/java/org/codice/alliance/test/itests/common/AbstractAllianceIntegrationTest.java
distribution/test/itests/test-itests-dependencies-app/src/main/filtered-resources/features.xml
libs/klv/src/test/java/org/codice/alliance/libs/klv/KlvUtilities.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/Stanag4609ProcessorImplTest.java
libs/stanag4609/src/main/java/org/codice/alliance/libs/stanag4609/Stanag4609TransportStreamParser.java
pom.xml

Bumps DDF version to 2.26.0, and bumps dependency versions to match what DDF uses. Includes the commits from this PR: https://github.com/codice/alliance/pull/829
@derekwilhelm @jlcsmith
CI
N/a
Fixes: #828

Upgrade to DDF 2.26.0

---

catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/metacard/DerivedAssociationMetacardUpdater.java
catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/plugins/FindChildrenStreamEndPlugin.java
catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/rollover/CatalogRolloverAction.java
catalog/video/video-mpegts-stream/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/video/video-mpegts-stream/src/test/java/org/codice/alliance/video/stream/mpegts/metacard/DerivedAssociationMetacardUpdaterTest.java
catalog/video/video-mpegts-stream/src/test/java/org/codice/alliance/video/stream/mpegts/rollover/CatalogRolloverActionTest.java
distribution/test/itests/test-itests-alliance/src/test/java/org/codice/alliance/test/itests/VideoTest.java

For video streams, the parent metacard (representing the entire stream) now points to its children (the chunk metacards) using the `metacard.associations.derived` attribute, instead of the children pointing to the parent via the same attribute. The DDF documentation states that this attribute is the 'ID of one or more metacards derived from this metacard'.
@peterhuffer 
@aj-brooks 
@jlcsmith
@glenhein 
1. Install Alliance with the video app.
2. Configure a video stream in the Admin UI. The default settings will work fine, but you can change the title or filename template if you want.
3. Stream an MPEG-TS video to the address specified in the stream configuration from the previous step (the default is `127.0.0.1:50000`). Two sample videos are available here: …

[1.10.x] Set the derived associations on the stream parent metacard instead of the chunk metacards

---

catalog/video/video-mpegts-stream/src/main/resources/OSGI-INF/metatype/metatype.xml
distribution/docs/src/main/resources/content/_reference/_tables/UdpStreamMonitor.adoc

Updates documentation about video chunk size and limit are not respected when streaming. Certain frame types are looked for when determining when to finish a chunk but some videos (more specifically in this scenario, streaming videos) have very few of these frames causing larger chunks which also causes it to take more time to process. 
@kcover 
@josephthweatt 
@jrnorth 
@clockard
@ricklarsen

Update docs about chunk frames when streaming video

---

catalog/video/video-app/pom.xml
catalog/video/video-app/src/main/resources/features.xml

Creates a feature that will start just the core bundles needed for
streaming and ingesting video, excluding any UI components.
@jrnorth 
@aj-brooks 
@clockard
@pklinef
Start with a DDF-catalog distribution, install the video-core feature, create a video stream by placing a config file in `/etc` (e.g. 
[video1.config.txt](https://github.com/codice/alliance/files/5518320/org.codice.alliance.video.stream.mpegts.UdpStreamMonitor-video1.config.txt), minus the `.txt` extension), ingest a video using something like TSDuck. Contact me if you're not familiar with …

Create video-core feature

---

catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/metacard/DerivedAssociationMetacardUpdater.java
catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/plugins/FindChildrenStreamEndPlugin.java
catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/rollover/CatalogRolloverAction.java
catalog/video/video-mpegts-stream/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/video/video-mpegts-stream/src/test/java/org/codice/alliance/video/stream/mpegts/metacard/DerivedAssociationMetacardUpdaterTest.java
catalog/video/video-mpegts-stream/src/test/java/org/codice/alliance/video/stream/mpegts/rollover/CatalogRolloverActionTest.java
distribution/test/itests/test-itests-alliance/src/test/java/org/codice/alliance/test/itests/VideoTest.java

For video streams, the parent metacard (representing the entire stream) now points to its children (the chunk metacards) using the `metacard.associations.derived` attribute, instead of the children pointing to the parent via the same attribute. The DDF documentation states that this attribute is the 'ID of one or more metacards derived from this metacard'.
@peterhuffer 
@aj-brooks 
@glenhein 
@jlcsmith
@clockard  
1. Install Alliance with the video app.
2. Configure a video stream in the Admin UI. The default settings will work fine, but you can change the title or filename template if you want.
3. Stream an MPEG-TS video to the address specified in the stream configuration from the previous step (the default is `127.0.0.1:50000`). Two sample videos are available here: …

Set the derived association IDs on video stream metacards correctly

---

Jenkinsfile

This removes the `mvn install` command from the sonar stage. This currently will fail now that the sonar stage requires jdk 11 to be accepted. 
@codice/build 
@TonyMorrison 
@LinkMJB 
@Lambeaux 
Jenkins build
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codice/alliance/882)

Remove mvn install from sonar stage

---

Jenkinsfile

Skips the distribution/alliance module when running the Sonar analysis. There is still a dependency on ACDebugger, which requires JDK8 (specifically tools.jar which has been removed in Java 9). Even running the sonar command on this module will cause a build failure as tools.jar will not be resolved. The workaround here is to skip the module on this stage since sonar primarily does Java analysis which the distribution/alliance module does not include.
@TonyMorrison 
@codice/build 
@stustison 
@LinkMJB 
@Lambeaux …

Skip distribution/alliance module sonar

---

Jenkinsfile
dependency-check-maven-config.xml
distribution/docs/pom.xml
distribution/test/pom.xml
pom.xml

A few things:
* Skips docs and itest modules when running OWASP scans. Don't care about those CVEs as they don't matter at runtime.
* Changes the CI scans to analyze the distribution zip when doing nightly builds, which takes longer but may catch some dependencies that the normal scans won't
* Makes the OWASP reports available in Jenkins
The changes are similar to https://github.com/codice/ddf/pull/6347
@codice/build 
@codice/security 
Verify that:
* CI passes
* The OWASP reports are available
* itest and docs CVEs don't show up in the reports (look for asciidoctor, jruby, groovy)

Skip itests and docs when doing OWASP scans, scan distro during nightly builds, and archive OWASP reports

---

Jenkinsfile

Skips more modules on Sonar Analysis. For some reason there are JDK failures on these modules. I'm also open to more elegant solutions but this is currently failing on the build. This change passed on this build: https://jenkins.phx.connexta.com/service/jenkins/job/Alliance/job/master/809/
@TonyMorrison 
@LinkMJB 
@SmithJosh 
@codice/build
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codice/alliance/886)

Skipping more modules on sonar analysis

---

Jenkinsfile

Stops running Sonar Analysis on the 1.6.x branch since we can only use one branch at a time. Currently this stage is failing since Sonar requires JDK 11 analysis.
@TonyMorrison 
@Lambeaux 
@andrewzimmer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codice/alliance/887)

Only run Sonar analysis on master

---

Jenkinsfile
distribution/docker/alliance/pom.xml
distribution/docker/pom.xml
distribution/pom.xml

Added Docker credentials to maven steps that do anonymous calls to Docker Hub to prevent exceeding the Docker call limits.
Docker recently instituted new limits for anonymous pulls from the Docker Hub registry, and by using the bot with the credential to access, we effectively double the number of calls we can make vs the anonymous calls
@jlcsmith 
@LinkMJB 
@jlcsmith
@shaundmorris

BR-154 Add Docker Credentials to prevent exceeding the Docker call limits

---

catalog/nsili/catalog-nsili-endpoint/pom.xml
catalog/security/banner-marking/src/main/java/org/codice/alliance/security/banner/marking/BannerMarkings.java
catalog/security/banner-marking/src/test/groovy/org/codice/alliance/security/banner/marking/BannerMarkingsSpec.groovy
catalog/security/banner-marking/src/test/groovy/org/codice/alliance/security/banner/marking/PortionMarkingsSpec.groovy

Adds a field to `BannerMarkings` to indicate whether the banner marking contains concealed FGI.
@kcwire
@millerw8
@shaundmorris 
Check out the unit tests.

[1.6.x] Support concealed FGI

---

distribution/docs/pom.xml
distribution/docs/src/main/resources/content/config.adoc

adds content for ddf-ui repo into the 1.15.x documentation module.
verify content is included in html and pdf versions of documentation.

added import of ddf-ui documentation to docs module

---

distribution/docs/src/main/resources/content/_architecture/_plugins/audit-classified-access-plugin.adoc
distribution/docs/src/main/resources/content/_metadataReference/isr-attributes-table.adoc
distribution/docs/src/main/resources/content/_metadataReference/security-attributes-table.adoc
distribution/docs/src/main/resources/content/_reference/_tables/UdpStreamMonitor.adoc

**FORWARD PORT to MASTER of #917**
updates documentation to remove parens from optional plurals. 
Aligns with Google Developer documentation style guidance on [Optional Plurals](https://developers.google.com/style/plurals-parentheses?hl=en).
@shaundmorris 
@jaymcnallie 
@sgalla 
@rececoffin 
@codice/docs 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is …

Updates documentation to remove parens from optional plurals.

---

distribution/docs/src/main/resources/content/_metadataReference/isr-attributes-table.adoc
distribution/docs/src/main/resources/content/_reference/_tables/UdpStreamMonitor.adoc

**FORWARD PORT to MASTER of #916**
Simplifies docs content to remove latin abbreviations to match Google Developer documentation style guide: https://developers.google.com/style/abbreviations?hl=en#dont-use
@jaymcnallie 
@shaundmorris 
@sgalla 
@rececoffin 
@codice/docs 
review content
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action …

edits to docs to remove latin abbreviations (#916)

---

distribution/docs/src/main/resources/content/_architecture/_plugins/default-attribute-plugin.adoc
distribution/docs/src/main/resources/content/_managing/_configuring/banner-markings-content-extractor.adoc
distribution/docs/src/main/resources/content/_managing/_installing/cal-setup-types.adoc
distribution/docs/src/main/resources/content/_managing/attributes-added-by-pre-ingest-plugins.adoc
distribution/docs/src/main/resources/content/_metadataReference/isr-attributes-table.adoc
distribution/docs/src/main/resources/content/_reference/_tables/MpegTsInputTransformer.adoc
distribution/docs/src/main/resources/content/_reference/_tables/NITF_Post_Process_Plugin.adoc
distribution/docs/src/main/resources/content/_reference/_tables/NITF_Render_Plugin.adoc

**PORT to MASTER of #921**
edits to documentation to standardize present tense usage over future tense. 
This aligns with the Google Developer Documentation Style Guide guidance: https://developers.google.com/style/tense?hl=en
@shaundmorris 
@jaymcnallie 
@rececoffin 
@sgalla 
@ahoffer 
@codice/docs 
review content.
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, …

removed future tense from docs content #921

---

libs/stanag4609/pom.xml
libs/stanag4609/src/main/java/org/codice/alliance/libs/stanag4609/SynchronousMetadataPacket.java
libs/stanag4609/src/test/java/org/codice/alliance/libs/stanag4609/MetadataPacketTest.java
pom.xml

Fixes an issue where the optional metadataAccessUnit header is not present.
@jrnorth 
@shaundmorris
Verify both mpeg ts files with and without the header can be ingested with location information

Fix the stanag klv reader to account for optional header

---

catalog/video/video-mpegts-stream/pom.xml
catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/UdpStreamMonitor.java
catalog/video/video-mpegts-stream/src/test/java/org/codice/alliance/video/stream/mpegts/UdpStreamMonitorTest.java

Fix UdpStreamMonitor update callback to set all properties
@clockard
@glenhein 
Can be tested downstream @clockard

Fix UdpStreamMonitor update callback to set all properties

---

.gitignore
catalog/imaging/imaging-actionprovider-chip/pom.xml
distribution/alliance/src/main/filtered-resources/etc/org.apache.karaf.features.cfg
distribution/alliance/src/main/filtered-resources/etc/org.apache.karaf.features.xml
distribution/common/src/main/resources/common-bin.xml
distribution/docs/pom.xml
distribution/test/itests/test-itests-alliance/pom.xml
distribution/test/itests/test-itests-alliance/src/test/java/org/codice/alliance/test/itests/ImagingTest.java
distribution/test/itests/test-itests-common/pom.xml
distribution/test/itests/test-itests-common/src/main/java/org/codice/alliance/test/itests/common/AbstractAllianceIntegrationTest.java
distribution/test/itests/test-itests-dependencies-app/pom.xml
pom.xml

Tentatively upgrade DDF to newest 2.29.x release.
I would like to wait for 
- https://github.com/codice/ddf/commit/cf1e79169a8ec9f3f7d33b5c3229de235b329150
- A CXF upgrade to 3.5.12 
in a future 2.29.x release before upgrading, but would be fine with this intermediate step. 
**Caveats:**
- Styling is broken for the Chipping `wab/war`
@clockard @pklinef @glenhein @ahoffer

Upgrades DDF to 2.29.17
