LICENSE.md
PULL_REQUEST_TEMPLATE
README.md
catalog/pom.xml
distribution/pom.xml
pom.xml

ALLIANCE01 Added Initial Framework

---

catalog/imaging/pom.xml
catalog/pom.xml

Fixes the current failing alliance build due to an incorrect catalog pom artifact id
@bdeining @kcwire @troymohl 
Verify a clean build works

CAL-25: Fixed catalog pom artifactId

---

distribution/alliance/pom.xml

Fixes distribution
@jlcsmith 
@kcwire 
Build alliance, verify zip size and system contents

CAL-24 Fixed distribution bug

---

catalog/nsili/catalog-nsili-source/pom.xml
pom.xml

Added maven release version and corrected platform util dependency
@troymohl @bdeining 
mvn -nsu clean install
mvn release:prepare -DdryRun=true

Cal 26: Added maven release version and corrected platform util dependency

---

distribution/alliance/pom.xml

Fixes sitename bug
@jlcsmith 
Build alliance and hit a REST endpoint

CAL-24 Fixed sitename bug

---

libs/pom.xml
libs/stanag4609/pom.xml
pom.xml
support/pom.xml
support/support-checkstyle/pom.xml

fix squashed poms not in last merge
@glenhein
Build against clean repo and start/run alliance
Several files were squashed before last merge and this will fix build
https://github.com/connexta/alliance/issues/21

alliance-21 updated pom files for new artifacts

---

catalog/nsili/catalog-nsili-endpoint/src/main/resources/OSGI-INF/metatype/metatype.xml
libs/pom.xml
libs/stanag4609/pom.xml
libs/stanag4609/src/main/java/com/connexta/alliance/libs/stanag4609/AbstractMetadataPacket.java
libs/stanag4609/src/main/java/com/connexta/alliance/libs/stanag4609/AsynchronousMetadataPacket.java
libs/stanag4609/src/main/java/com/connexta/alliance/libs/stanag4609/DecodedKLVMetadataPacket.java
libs/stanag4609/src/main/java/com/connexta/alliance/libs/stanag4609/Stanag4609TransportStreamParser.java
libs/stanag4609/src/main/java/com/connexta/alliance/libs/stanag4609/SynchronousMetadataPacket.java
libs/stanag4609/src/test/java/com/connexta/alliance/libs/stanag4609/MetadataPacketTest.java
libs/stanag4609/src/test/java/com/connexta/alliance/libs/stanag4609/Stanag4609TransportStreamParserTest.java
pom.xml

updates headers in STANAG 4609 code
@troymohl @glenhein
Grep for any old packages 'org.codice.alliance' or copyright headers 'Codice Foundation' in the checkout.
https://github.com/connexta/alliance/issues/26

alliance-26 updated copyrights in STANAG4609 source

---

catalog/nsili/catalog-nsili-source/src/main/java/com/connexta/alliance/nsili/source/NsiliSource.java

Updates log messages for NSILI sources. Moves stack traces from WARN/ERROR to DEBUG level.
@troymohl @jaymcnallie @kcwire 
Install NSILI App into a DDF instance and add source with bologna information. No stack traces should appear.
N/A
[CAL-27](https://codice.atlassian.net/projects/CAL/issues/CAL-27)
[DDF-1971](https://codice.atlassian.net/projects/DDF/issues/DDF-1971)
N/A
- Moves stack traces from ERROR to DEBUG level for NSILI sources
- Add some checks for when IOR file gives null or empty string.

CAL-27: Update log messages for unavailable sources

---

catalog/nsili/catalog-nsili-common/src/main/java/com/connexta/alliance/nsili/common/NsilCorbaExceptionUtil.java
catalog/nsili/catalog-nsili-source/src/main/java/com/connexta/alliance/nsili/source/NsiliFilterFactory.java
catalog/nsili/catalog-nsili-source/src/main/java/com/connexta/alliance/nsili/source/NsiliSource.java
catalog/nsili/catalog-nsili-source/src/test/java/com/connexta/alliance/nsili/source/TestNsiliFilterDelegate.java
catalog/nsili/catalog-nsili-source/src/test/java/com/connexta/alliance/nsili/source/TestNsiliSource.java
catalog/nsili/catalog-nsili-transformer/src/main/java/com/connexta/alliance/nsili/transformer/DAGConverter.java

Fixes exceptions that occur when attempting to retrieve hit counts and results against a STANAG-4559 server.
@jaymcnallie @kcwire @bdeining @jlcsmith 
Build and run unit tests
https://github.com/connexta/alliance/issues/36

alliance-36 Fixes for exceptions when attempting to retrieve results.

---

catalog/nsili/catalog-nsili-common/src/main/java/org/codice/alliance/nsili/common/NsiliConstants.java
catalog/nsili/catalog-nsili-common/src/main/java/org/codice/alliance/nsili/common/PackagingSpecFormatType.java
catalog/nsili/catalog-nsili-endpoint/pom.xml
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/LibraryImpl.java
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/NsiliEndpoint.java
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/managers/AccessManagerImpl.java
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/managers/CatalogMgrImpl.java
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/managers/CreationMgrImpl.java
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/managers/OrderMgrImpl.java
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/managers/ProductMgrImpl.java
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/requests/GetParametersRequestImpl.java
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/requests/OrderRequestImpl.java
catalog/nsili/catalog-nsili-endpoint/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/nsili/catalog-nsili-endpoint/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/TestCatalogMgrImpl.java
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/TestCreationMgrImpl.java
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/TestNsiliCommon.java
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/TestNsiliLibraryImpl.java
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/TestOrderMgrImpl.java
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/TestOrderRequestImpl.java
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/TestProductMgrImpl.java
distribution/sdk/sample-nsili-server/src/main/java/org/codice/alliance/nsili/mockserver/client/NsiliClient.java

Adds the OrderMgr STANAG-4559 interface.
Added property to control whether or not to perform local or enterprise catalog searches. Default to local.
@jaymcnallie @bdeining @dcruver 
JUnit test cases for OrderMgr
https://codice.atlassian.net/browse/CAL-15

CAL-15 Added OrderMgr interface for support of simple product retrieval

---

catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/NsiliEndpoint.java
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/NsiliWebEndpoint.java
distribution/pom.xml
distribution/sdk/sample-nsili-client/README.md
distribution/sdk/sample-nsili-client/pom.xml
distribution/sdk/sample-nsili-client/src/main/java/org/codice/alliance/nsili/client/Client.java
distribution/sdk/sample-nsili-client/src/main/java/org/codice/alliance/nsili/client/NsiliClient.java
distribution/sdk/sample-nsili-client/src/main/java/org/codice/alliance/nsili/client/NsiliWeb.java
distribution/sdk/sample-nsili-server/src/main/java/org/codice/alliance/nsili/mockserver/server/MockNsili.java
distribution/sdk/sample-nsili-server/src/main/java/org/codice/alliance/nsili/mockserver/server/MockWebService.java
distribution/test/itests/pom.xml
distribution/test/itests/test-itests-alliance/pom.xml
distribution/test/itests/test-itests-alliance/src/test/java/alliance/test/itests/MockNsiliRunnable.java
distribution/test/itests/test-itests-alliance/src/test/java/alliance/test/itests/TestNsili.java
distribution/test/pom.xml

Adding initial set of itests in Alliance, including NSILI Federated Source.
Separated the NSILI Mock Server and NSILI Client into two separate packages.
@peterhuffer @jrnorth @jaymcnallie @kcwire 
Build Alliance
https://codice.atlassian.net/browse/CAL-55

CAL-55 Added integration test package and integration tests for NSILI

---

catalog/nsili/catalog-nsili-endpoint/pom.xml
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/NsiliEndpoint.java
catalog/nsili/catalog-nsili-endpoint/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/nsili/catalog-nsili-endpoint/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/TestNsiliCommon.java
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/TestNsiliEndpoint.java
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/TestNsiliLibraryImpl.java
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/TestNsiliWebEndpoint.java
catalog/nsili/catalog-nsili-orb-api/pom.xml
catalog/nsili/catalog-nsili-orb-api/src/main/java/org/codice/alliance/nsili/orb/api/CorbaOrb.java
catalog/nsili/catalog-nsili-orb-api/src/main/java/org/codice/alliance/nsili/orb/api/CorbaServiceListener.java
catalog/nsili/catalog-nsili-orb-impl/pom.xml
catalog/nsili/catalog-nsili-orb-impl/src/main/java/org/codice/alliance/nsili/orb/impl/CorbaOrbImpl.java
catalog/nsili/catalog-nsili-orb-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/nsili/catalog-nsili-orb-impl/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/nsili/catalog-nsili-orb-impl/src/main/resources/describable.properties
catalog/nsili/catalog-nsili-orb-impl/src/test/java/org/codice/alliance/nsili/orb/impl/TestCorbaOrbImpl.java
catalog/nsili/catalog-nsili-source/pom.xml
catalog/nsili/catalog-nsili-source/src/main/java/org/codice/alliance/nsili/source/NsiliSource.java
catalog/nsili/catalog-nsili-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/nsili/catalog-nsili-source/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/nsili/catalog-nsili-source/src/test/java/org/codice/alliance/nsili/source/TestNsiliSource.java
catalog/nsili/nsili-app/pom.xml
catalog/nsili/nsili-app/src/main/resources/features.xml
catalog/nsili/pom.xml

Creates a common ORB service for both the NSILI Endpoint and Source to use. 
@jaymcnallie @bdeining @kcwire 
Run the JUnit Tests
Build and run alliance and verify that: https://localhost:8993/services/nsili/ior.txt returns text starting with IOR:
https://codice.atlassian.net/browse/CAL-63

CAL-63 Create a separate ORB service from which the NSILI Source and Endpoint will get the ORB

---

catalog/nsili/catalog-nsili-endpoint/pom.xml

Fixes build errors with CAL-56 automated build
@jaymcnallie 
Run the full build using mvn clean install

CAL-56: Fix to the build failures due to jacoco coverage numbers

---

distribution/test/itests/test-itests-alliance/src/test/java/alliance/test/itests/TestBannerMarkings.java

Fixes an itest that should have been resolved in the prior commit.
@stustison @ryeats @tbatie 
Full build and itest.
N/A
CAL-73
N/A

CAL-73 Fixes broken itest checking an outdated assertion.

---

distribution/alliance/pom.xml
distribution/pom.xml

Add documentation to alliance zip
@shaundmorris 
alliance sections in rendered documentation
CAL-96

CAL-69: included docs in distribution .zip

---

catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/metacard/LineStringMetacardUpdater.java
catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/metacard/LocationMetacardUpdater.java
catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/netty/UdpStreamProcessor.java
catalog/video/video-mpegts-stream/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/video/video-mpegts-stream/src/test/java/org/codice/alliance/video/stream/mpegts/metacard/TestLineStringMetacardUpdater.java
catalog/video/video-mpegts-stream/src/test/java/org/codice/alliance/video/stream/mpegts/rollover/TestCatalogRolloverAction.java
catalog/video/video-mpegts-transformer/pom.xml
catalog/video/video-mpegts-transformer/src/main/java/org/codice/alliance/transformer/video/SetDistanceToleranceVisitor.java
catalog/video/video-mpegts-transformer/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/video/video-mpegts-transformer/src/test/java/org/codice/alliance/transformer/video/TestMpegTsInputTransformer.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/FrameCenterKlvProcessor.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/GeoBoxHandler.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/GeometryOperator.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/GeometryOperatorList.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/GeometryReducer.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/GeometryUtility.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/LocationKlvProcessor.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/NormalizeGeometry.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/SimplifyGeometryFunction.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/TestGeometryFunction.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/TestGeometryFunctionList.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/TestGeometryOperatorList.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/TestLocationKlvProcessor.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/TestNormalizeGeometry.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/TestSimplifyGeometryFunction.java

Add precision reducer to JTS geometry objects.
@jrnorth 
@rzwiefel 
@lcrosenbu 
@bdeining 
Ingest a video with known precision problems (contact me for the file). Verify that the file is ingested.
CAL-80

CAL-80 add precision reducer to JTS geometry

---

catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/UdpStreamMonitor.java
catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/netty/PacketBuffer.java
catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/netty/UdpStreamProcessor.java

Add more logging to video streaming.
@beyelerb 
@jlcsmith 
@dcruver 
@bdeining 
Build alliance experimental. Set the logging level to debug (log:set DEBUG org.codice.alliance.video.stream). Configure a UDP stream. Transmit a stream. 
Look for the debug log messages that detail the stream activity.
CAL-75

CAL-75 add more logging to video streaming

---

catalog/video/video-admin-plugin/src/main/java/org/codice/alliance/video/ui/service/StreamMonitorHelper.java
catalog/video/video-admin-plugin/src/main/webapp/js/model/StreamMonitor.js
catalog/video/video-admin-plugin/src/main/webapp/js/view/StreamMonitor.view.js
catalog/video/video-admin-plugin/src/main/webapp/templates/addConfigurationModal.handlebars
catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/UdpStreamMonitor.java
catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/netty/UdpStreamProcessor.java

This PR adds the Distance Tolerance field to the Video Admin plugin
@glenhein @jlcsmith @lcrosenbu @kcwire 
Build Alliance Experimental, configure an FMV Stream via the Video Admin plugin, and verify that the Distance Tolerance is set and updated correctly
https://codice.atlassian.net/browse/CAL-96
https://codice.atlassian.net/browse/CAL-96

CAL-96 Added Distance Tolerance to Video Admin Plugin

---

libs/klv/src/main/java/org/codice/alliance/libs/klv/BaseKlvHandler.java

Fix broken build that was cause by the merge of CAL-84.
@troymohl 
@jaymcnallie 
@kcwire 
@peterhuffer 
Just build and make sure the libs/klv tests succeed.
CAL-103

CAL-103 change BaseKlvHandler from package to public

---

catalog/core/catalog-core-api-impl/pom.xml
catalog/core/catalog-core-api-impl/src/main/java/org/codice/alliance/catalog/core/api/impl/types/IsrAttributes.java
catalog/core/catalog-core-api-impl/src/main/java/org/codice/alliance/catalog/core/api/impl/types/SecurityAttributes.java
catalog/core/catalog-core-api-impl/src/test/java/org/codice/alliance/catalog/core/api/impl/types/TestMetacardTypeAttributes.java
catalog/core/catalog-core-api/pom.xml
catalog/core/catalog-core-api/src/main/java/org/codice/alliance/catalog/core/api/types/Isr.java
catalog/core/catalog-core-api/src/main/java/org/codice/alliance/catalog/core/api/types/Security.java
catalog/core/pom.xml
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/NitfMetacardType.java
catalog/pom.xml

This PR implements the expanded taxonomy within Alliance
@jlcsmith @brendan-hofmann @lcrosenbu @pklinef 
Build Alliance
Information for the new taxonomy can be found at https://codice.atlassian.net/wiki/display/DDF/Attributes.  This PR depends on DDF-2275
https://github.com/codice/ddf/pull/976
https://codice.atlassian.net/browse/CAL-77
https://codice.atlassian.net/browse/DDF-2275

CAL-77 Implemented expanded taxonomy and created catalog-core

---

catalog/nsili/catalog-nsili-common/src/test/java/org/codice/alliance/nsili/common/TestBqsConverter.java

Removes an unused logger and mistakenly imported sun's logger.
@coyotesqrl 
Full build successfully

CAL-14:  Removed unused logger

---

PULL_REQUEST_TEMPLATE

CAL-113: Update Alliance PR template

---

catalog/core/catalog-core-metacardtypes/pom.xml
distribution/test/itests/test-itests-alliance/src/test/java/alliance/test/itests/TestAllianceApps.java

This PR fixes alliance itests failures related to a video-app missing dependency issue.
@troymohl @glenhein @bdeining 
@coyotesqrl
Verify Alliance itests pass

CAL-90: Resolved video-app dependency issue causing itest failures

---

catalog/core/catalog-core-api-impl/src/main/java/org/codice/alliance/catalog/core/api/impl/types/IsrAttributes.java
catalog/core/catalog-core-api-impl/src/main/java/org/codice/alliance/catalog/core/api/impl/types/SecurityAttributes.java
catalog/core/catalog-core-api/src/main/java/org/codice/alliance/catalog/core/api/types/Isr.java
catalog/core/catalog-core-api/src/main/java/org/codice/alliance/catalog/core/api/types/Security.java
catalog/pom.xml
catalog/transformer/catalog-transformer-mgmp/pom.xml
catalog/transformer/catalog-transformer-mgmp/src/main/java/org/codice/alliance/catalog/transformer/mgmp/MgmpConstants.java
catalog/transformer/catalog-transformer-mgmp/src/main/java/org/codice/alliance/catalog/transformer/mgmp/MgmpTransformer.java
catalog/transformer/catalog-transformer-mgmp/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/transformer/catalog-transformer-mgmp/src/main/resources/injectors.config
catalog/transformer/catalog-transformer-mgmp/src/test/java/org/codice/alliance/catalog/transformer/mgmp/TestMgmpTransformer.java
catalog/transformer/catalog-transformer-mgmp/src/test/resources/empty_mgmp.xml
catalog/transformer/catalog-transformer-mgmp/src/test/resources/full_data_mgmp.xml
catalog/transformer/catalog-transformer-mgmp/src/test/resources/sample_mgmp_1.xml
catalog/transformer/catalog-transformer-mgmp/src/test/resources/sample_mgmp_2.xml
catalog/transformer/pom.xml
distribution/alliance-app/pom.xml
distribution/alliance-app/src/main/resources/features.xml
distribution/alliance/pom.xml
distribution/alliance/src/main/filtered-resources/etc/org.apache.karaf.features.cfg
distribution/install-profiles/src/main/resources/features.xml
distribution/pom.xml
libs/pom-fix-run/pom.xml

This PR adds an Input Transformer to support the MGMP specification.  It also adds an `Alliance App` to place miscellaneous functionality that does not fit under the current apps that exist within Alliance.  
@lcrosenbu @jrnorth @glenhein @jlcsmith @kcwire @codice/security 
Build and install Alliance, and run `catalog:ingest -t mgmp:MD_Metadata "mgmp2.xml"`.  Sample MGMP files are located in `catalog/transformer/catalog-transformer-mgmp/src/test/resources`.
Depends on https://github.com/codice/ddf/pull/1070
https://codice.atlassian.net/browse/CAL-102

CAL-102 Added MGMP input transformer and Alliance App

---

catalog/transformer/catalog-transformer-mgmp/src/test/java/org/codice/alliance/catalog/transformer/mgmp/TestMgmpTransformer.java
pom.xml

This PR fixes a small timezone bug in the MGMP transformer.  Updated the root pom to run unit tests in the UTC timezone.
@tbatie @glenhein 
@coyotesqrl
@jlcsmith
Build Alliance

CAL-102 Fixed timezone bug

---

catalog/video/video-security/pom.xml
catalog/video/video-security/src/main/java/org/codice/alliance/video/security/validator/videographer/VideographerValidator.java
catalog/video/video-security/src/test/java/org/codice/alliance/video/security/validator/videographer/TestVideographerValidator.java

Fix scoped ipv6 addresses in videographer tokens.
@clockard 
@glenhein 
@pklinef
@stustison
This is a port of DDF-2416 
CAL-118

CAL-118 Fix ipv6 videographer validation

---

catalog/transformer/catalog-transformer-mgmp/src/main/java/org/codice/alliance/catalog/transformer/mgmp/MgmpTransformer.java

@bdeining @troymohl 
@jlcsmith
@stustison

DDF-2442 removed use of DTD in XML parsing

---

catalog/transformer/catalog-transformer-mgmp/pom.xml

This PR fixes the Alliance build and itests
@troymohl 
@stustison 
@kcwire

CAL-128 Fixed dependency in MgmpTransformer / Fixed itest

---

catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/metacard/ModifiedDateMetacardUpdater.java
distribution/sdk/pom.xml
distribution/sdk/sample-mpegts-streamgenerator/pom.xml
distribution/sdk/sample-mpegts-streamgenerator/src/main/java/org/codice/alliance/distribution/sdk/video/stream/mpegts/MpegTsUdpClient.java
distribution/sdk/sdk-app/pom.xml
distribution/sdk/sdk-app/src/main/resources/features.xml
distribution/test/itests/test-itests-alliance/pom.xml
distribution/test/itests/test-itests-alliance/src/test/java/org/codice/alliance/test/itests/FederationTest.java
distribution/test/itests/test-itests-alliance/src/test/java/org/codice/alliance/test/itests/VideoTest.java
distribution/test/itests/test-itests-common/src/main/java/org/codice/alliance/test/itests/common/AbstractAllianceIntegrationTest.java
distribution/test/itests/test-itests-common/src/main/resources/nightflight.md

Adds integration tests for Alliance's streaming video capabilities
@glenhein 
@bdeining 
@lcrosenbu 
@jlcsmith
@kcwire
Run the Alliance integration tests.
[CAL-120](https://codice.atlassian.net/browse/CAL-120)
https://github.com/codice/alliance/pull/126 will have to be merged before this.

CAL-120 Add integration tests for streaming video

---

catalog/nsili/catalog-nsili-common/src/test/java/org/codice/alliance/nsili/common/BqsConverterTest.java
distribution/sdk/sample-nsili-client/pom.xml
distribution/sdk/sample-nsili-client/src/main/java/org/codice/alliance/nsili/client/Client.java
distribution/sdk/sample-nsili-client/src/main/java/org/codice/alliance/nsili/client/NsiliClient.java
distribution/sdk/sample-nsili-client/src/main/java/org/codice/alliance/nsili/client/NsiliWeb.java
distribution/sdk/sample-nsili-server/pom.xml
distribution/sdk/sample-nsili-server/src/main/java/org/codice/alliance/nsili/mockserver/impl/managers/CatalogMgrImpl.java
distribution/sdk/sample-nsili-server/src/main/java/org/codice/alliance/nsili/mockserver/impl/managers/OrderMgrImpl.java
distribution/sdk/sample-nsili-server/src/main/java/org/codice/alliance/nsili/mockserver/impl/managers/ProductMgrImpl.java
distribution/sdk/sample-nsili-server/src/main/java/org/codice/alliance/nsili/mockserver/server/MockNsili.java

This PR removes System.out.println from sample-nsili-server and sample-nsili-client in favor of SLF4J
@troymohl @peterhuffer 
@coyotesqrl
@jlcsmith
Build Alliance, run sample-nsili-server and client and observe logging

CAL-135 Added SLF4J to sample-nsili-client code and sample-nsili-server

---

pom.xml

@jlcsmith 
@kcwire 
@stustison

DDF-2511 updated karaf and cxf to the correct versions

---

catalog/video/video-mpegts-stream/pom.xml

This PR fixes a bamboo coverage failure
@lcrosenbu 
@coyotesqrl
@jlcsmith

CAL-142 Fixed coverage failure in video package

---

catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/UdpStreamMonitor.java

This PR fixes Video Itests
@troymohl @glenhein 
@jlcsmith
@kcwire
Run mvn clean install

CAL-142 Fixed Video Itests

---

catalog/imaging/imaging-transformer-chipping/src/test/java/org/codice/alliance/imaging/chip/transformer/TestCatalogOutputAdapter.java
catalog/nsili/catalog-nsili-common/src/test/java/org/codice/alliance/nsili/common/TestBqsConverter.java
pom.xml

- Upgrades the 0.1.x branch from DDF 2.9.1 to DDF 2.9.3-SNAPSHOT
- Added fix from CAL-14 so the build passes in Continuous Integration
- Added CAL-110 for a unit test fix
@bdeining @glenhein @tbatie 
@coyotesqrl
@shaundmorris 
Full build
This is a preliminary PR to build on DDF 2.9.3-SNAPSHOT. When 2.9.3 is released a follow-up PR will be submitted
CAL-149
CAL-14
CAL-110

CAL-149 Upgraded to DDF-2.9.3-SNAPSHOT

---

catalog/plugin/catalog-plugin-defaultsecurityattributevalues/src/main/java/org/codice/alliance/catalog/plugin/defaultsecurity/DefaultSecurityAttributeValuesPlugin.java
catalog/plugin/catalog-plugin-defaultsecurityattributevalues/src/main/resources/OSGI-INF/blueprint/blueprint.xml

Updates the security mapping from Clearance to classification. Also preserves attribute order.
@spearskw @emanns95  @brendan-hofmann 
@coyotesqrl
@lessarderic

CAL-153: Updated DefaultSecurityAttributeValuesPlugin mapping

---

catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/TreTestUtility.java
catalog/imaging/pom.xml

Set the imaging-nitf-library version to 0.5.
@roelens8 
@beyelerb
@jaymcnallie
1) build the alliance-imaging app.
2) update/install the app.
3) ingest NITFs.
4) verify that they appear in query results.
CAL-151, IMG-191

CAL-151 Increment the imaging-nitf libarary version

---

catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/AimidbAttribute.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/TreDescriptor.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/TreUtility.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/image/ImageMetacardType.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/AimidbAttributeTest.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/image/ImageInputTransformerTest.java

Parses the AIMIDB TRE from NITFs. 
@dcruver 
@jaymcnallie
@kcwire 
Run a full build and make sure unit tests pass.
CAL-79

CAL-79 Add support for parsing the AIMIDB TRE from NITFs

---

pom.xml

remove third party repositories we don't use them and shouldn't be using them if they are there we might accidentally use them so we need to remove them.
@jlcsmith
@stustison
run a clean install with a fresh m2 `mvn clean install -Dmaven.repo.local=../tmp.m2`

CAL-165 remove third party repositories.

---

CHANGES.md
PULL_REQUEST_TEMPLATE

Backports change log to 0.1.x branch.
@coyotesqrl @kcwire @shaundmorris 
@coyotesqrl
@kcwire
@shaundmorris
[CAL-156](https://codice.atlassian.net/browse/CAL-156)

CAL-156 added CHANGES.md to track changes between versions

---

libs/klv/pom.xml
libs/klv/src/main/java/org/codice/alliance/libs/klv/CopyPresentKlvProcessor.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/DistinctKlvProcessor.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/Utilities.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/KlvUtilities.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/TestCopyPresentKlvProcessor.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/UtilitiesTest.java

See [PR-173](https://github.com/codice/alliance/pull/173).
@bdeining 
@glenhein 
@coyotesqrl 
@kcwire

CAL-162: (back-port) Changed attribute setters in KlvProcessor impls to validate before setting

---

pom.xml

Updates the DDF version property from 2.9.3-SNAPSHOT to the released 2.9.3.
@lcrosenbu @mweser 
@kcwire
@shaundmorris
Full build and test run
N/A
CAL-169
N/A

CAL-169 Update DDF version from SNAPSHOT to released version of 2.9.3.

---

catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/TreUtility.java

CAL-134: Adds common TRE parsing methods for CSEXRA, CSDIDA, PIAIMC, and HISTOA TREs.
@glenhein 
@bdeining
@peterhuffer
@kcwire
@lessarderic
Run complete build with tests. Conversion methods are verified in TRE JUnit tests.
The PR for CAL-134 will be broken out into multiple PRs.

CAL-134: Common TreUtility for processing CSEXRA, CSDIDA, PIAIMC, and HISTOA TREs

---

catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/CsdidaAttribute.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/gmti/GmtiMetacardType.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/image/ImageMetacardType.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/common/CsdidaAttributeTest.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/image/ImageInputTransformerTest.java

CAL-134: Mapping for non-taxonomy CSDIDA NITF TRE fields.
@glenhein 
@bdeining
@peterhuffer
@kcwire
@lessarderic
Run complete build with tests.
The PR for CAL-134 will be broken out into multiple PRs.
This depends on: https://github.com/codice/alliance/pull/179

CAL-134: Mapping of CSDIDA attributes to ext.nitf.* fields.

---

catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/netty/RawUdpDataToMTSPacketDecoder.java
catalog/video/video-mpegts-stream/src/test/java/org/codice/alliance/video/stream/mpegts/netty/RawUdpDataToMTSPacketDecoderTest.java

Catch all exceptions when parsing MPEG-TS packets in order to make streaming video ingestion more resilient.
@bdeining 
@jrnorth 
@jlcsmith
@lessarderic
Under a windows vm, stream a long video (200MB+) using ffmpeg. Parsing exceptions will be logged to the DEBUG level. Observe that if an exception is logged, that the processing continues. 
FFMPEG Command: ffmpeg -re -i %1 -map 0 -c copy -f mpegts "udp://127.0.0.1:50000"
Enable logging: log:set DEBUG org.codice.alliance.video.stream.mpegts.netty
[CAL-196](https://codice.atlassian.net/browse/CAL-196)

CAL-196 Catch all exceptions when parsing MPEG-TS packets

---

catalog/nsili/catalog-nsili-common/src/main/java/org/codice/alliance/nsili/common/BqsConverter.java
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/NsiliCommonTest.java

Fixes Incompatibilities with latest versioning changes
@bdeining
@jlcsmith
@kcwire

CAL-209: updated NSILI for the latest versioning changes

---

catalog/nsili/catalog-nsili-endpoint/pom.xml

Fixes alliance build due to NSILI endpoint coverage check failure
@rzwiefel @troymohl 
@shaundmorris
[CAL-209](https://codice.atlassian.net/browse/CAL-209)

CAL-209: Corrected NSILI endpoint coverage check threshold

---

distribution/docs/src/main/resources/_contents/_formats/supported-file-formats-contents.adoc
distribution/docs/src/main/resources/_contents/config.adoc
distribution/docs/src/main/resources/documentation.adoc
pom.xml

Updates the list of NITF attributes in documentation to reflect behavior in v 0.2.0.
@peterhuffer @lcrosenbu @troymohl 
@pklinef
@shaundmorris
verify list of attributes
[CAL-206](https://codice.atlassian.net/browse/CAL-206)

Cal 206 update list of nitf attributes to documentation

---

distribution/test/itests/pom.xml

This PR updates the Pax Exam Version and fixes the Alliance build
@glenhein @rzwiefel 
@jlcsmith
@kcwire
Build Alliance
[CAL-218](https://codice.atlassian.net/browse/CAL-218)

CAL-218 Updated Pax Exam Version to 4.9.2

---

distribution/docs/pom.xml
pom.xml

- Aligns documentation dependencies with the documentation profile in DDF. 
@troymohl @AzGoalie @Lambeaux 
@coyotesqrl
@lessarderic
@shaundmorris
@stustison
- docs build successfully
- diagrams render and are included in html and pdf
[CAL-212](https://codice.atlassian.net/browse/CAL-212)

CAL-212 aligned docs dependency versions with DDF

---

distribution/docs/pom.xml
distribution/docs/src/main/resources/documentation.adoc
pom.xml

fixes dependency resolution error in documentation profile.
standardizes documentation profile with DDF project.
@bdeining @troymohl @AzGoalie 
@coyotesqrl
@jlcsmith
@shaundmorris
fixes build error.
[CAL-212](https://codice.atlassian.net/browse/CAL-212)

CAL-212 fix for asciidoctor dependency versions

---

distribution/docs/src/main/resources/_contents/_introduction/applications-contents.adoc
distribution/docs/src/main/resources/_contents/_introduction/introduction-contents.adoc
distribution/docs/src/main/resources/_contents/_video/managing-video-contents.adoc
distribution/docs/src/main/resources/draft-documentation.adoc

Updates draft-documentation to follow new, component based outline. 
@troymohl @peterhuffer @Lambeaux @lcrosenbu @mcalcote @jrnorth
@jaymcnallie
@jlcsmith
@kcwire
@shaundmorris
Documentation renders successfully, no missing sections
[CAL-85](https://codice.atlassian.net/browse/CAL-85)
[DDF-2489](https://codice.atlassian.net/browse/DDF-2489)

CAL-85 Updated docs to new outline

---

catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/UdpStreamMonitor.java

This PR reduces the time it takes to close netty channels when the stream is shut down.
@glenhein @rzwiefel 
@jlcsmith
@kcwire
Build / Install Experimental / Stream Video / Shut down stream during transmission / Observe shutdown performance.  No new content should be created after a few seconds.
Prior to this fix, the netty channel would continue to receive data after shutdown was called.
[CAL-227](https://codice.atlassian.net/browse/CAL-227)

CAL-227 Increased FMV stream shutdown speed

---

distribution/docs/src/main/resources/draft-documentation.adoc

Updates documentation for renamed file imported from DDF. 
@lcrosenbu @jrnorth @mcalcote @emmberk @vinamartin @peterhuffer 
@jlcsmith
@kcwire
@pklinef
@shaundmorris
builds successfully with no missing files. 
Builds on changes made in https://github.com/codice/ddf/pull/1546.
[CAL-233](https://codice.atlassian.net/browse/CAL-233)
[DDF-2471](https://codice.atlassian.net/browse/DDF-2471)
n/a

CAL-233 updated draft-documentation for Core Concepts docs

---

distribution/alliance-branding-plugin/src/main/java/org/codice/alliance/distribution/branding/AllianceBrandingPlugin.java

just what it says
@bdeining 
@jlcsmith
@stustison
[CAL-236](https://codice.atlassian.net/browse/CAL-236)

CAL-236 closes the streams that load images for the branding plugin

---

distribution/alliance/pom.xml
distribution/alliance/src/main/filtered-resources/etc/org.apache.karaf.features.cfg
distribution/alliance/src/main/filtered-resources/etc/org.codice.ddf.admin.application.service.impl.ApplicationServiceImpl.config

Fixes dependencies in Alliance so that artemis-core can be installed.
@lcrosenbu @peterhuffer 
@beyelerb
@jaymcnallie
1. Build and install Alliance (initial run through installer)
2. feature:install artemis-core 
3. feature:list | grep -i artemis-core 
Ensure that artemis-core feature shows Started
https://codice.atlassian.net/browse/CAL-213
[CAL-xxxx](https://codice.atlassian.net/browse/CAL-xxxx)

CAL-213: Updated dependencies so artemis-core feature can be installed.

---

catalog/imaging/imaging-actionprovider-chip/src/main/webapp/js/chipping.js

This PR fixes the Image Chip Offset (10 pixels off).
@rzwiefel @glenhein 
@jlcsmith
Build / Install / Ingest NITF / Chip the NITF and test top/bottom edge cases
[CAL-237](https://codice.atlassian.net/browse/CAL-237)

CAL-237 Fixed offset in image chip page

---

distribution/alliance/pom.xml
distribution/alliance/src/main/filtered-resources/etc/org.apache.karaf.features.cfg
distribution/docs/src/main/resources/_contents/_dependency-list/dependency-list-contents.adoc
distribution/sdk/sdk-app/pom.xml

This PR updates the search-ui-app mvn coordinate and fixes a build stability issue.
@emmberk @troymohl 
@jlcsmith
@kcwire
Build / Install / Verify Catalog UI is installed and accessible
[CAL-231](https://codice.atlassian.net/browse/CAL-231)

CAL-231 Updated search-ui-app mvn coordinate

---

distribution/docs/src/main/resources/_contents/_imaging/managing-imaging-contents.adoc
distribution/docs/src/main/resources/_contents/config.adoc
distribution/docs/src/main/resources/documentation.adoc

updates `draft-documentation` to reflect changes made in https://github.com/codice/ddf/pull/1594. 
@spearskw @brianfelix @adimka 
@coyotesqrl
@shaundmorris
@stustison
verify builds successfully and all content included.
builds on https://github.com/codice/ddf/pull/1594
[CAL-239](https://codice.atlassian.net/browse/CAL-239)
[DDF-2472](https://github.com/codice/ddf/pull/1594)

CAL-239 updated documentation for securing and hardening

---

distribution/docs/src/main/resources/_contents/_data/isr-attributes-table-contents.adoc
distribution/docs/src/main/resources/_contents/_formats/supported-file-formats-contents.adoc

Cleans up taxonomy documentation and adds missing content.
@brendan-hofmann @bdeining 
@shaundmorris
[CAL-224](https://codice.atlassian.net/browse/CAL-224)

CAL-224: Updated Alliance taxonomy docs

---

distribution/docs/src/main/resources/_contents/_data/isr-attributes-table-contents.adoc
distribution/docs/src/main/resources/_contents/_data/security-attributes-table-contents.adoc

CAL-224 Address some comments from pr #240

---

distribution/docs/src/main/resources/documentation.adoc

updates federated sources docs to include confluence source. for (0.2.x branch)
@Lambeaux @vinamartin @mcalcote @ahoffer @bdeining @jrnorth 
@coyotesqrl
@jlcsmith
@pklinef
@shaundmorris
verify content included in rendered documentation.
[CAL-254](https://codice.atlassian.net/browse/CAL-254)
[documentation.pdf](https://github.com/codice/alliance/files/781460/documentation.pdf)

CAL-254 fix for confluence source docs

---

distribution/alliance/pom.xml
distribution/docs/pom.xml
pom.xml

_distribution/alliance/pom.xml, distribution/docs/pom.xml_
Changes the documentation profile to be activated when the property “skipDocs” is false or not provided. (Reference an example here: http://maven.apache.org/guides/introduction/introduction-to-profiles.html). This was done to prevent issues with profile activation that were happening. 
From the Maven website, emphasis mine:
_[A profile using `<activeByDefault>`] will automatically be active for all builds unless another profile **in the same POM** is activated using one of the previously described methods. All profiles that are active by default are **automatically deactivated when a profile in the POM is activated** on the command line or through its activation config._
By changing it to property based activation, the profile …

CAL-257 Updates & cleans up maven profiles

---

distribution/test/itests/test-itests-alliance/src/test/java/org/codice/alliance/test/itests/ImagingTest.java
distribution/test/itests/test-itests-alliance/src/test/java/org/codice/alliance/test/itests/NsiliEndpointTest.java
distribution/test/itests/test-itests-alliance/src/test/java/org/codice/alliance/test/itests/NsiliSourceTest.java
distribution/test/itests/test-itests-alliance/src/test/java/org/codice/alliance/test/itests/SecurityAuditPluginTest.java
distribution/test/itests/test-itests-alliance/src/test/java/org/codice/alliance/test/itests/VideoTest.java

@tbatie @ahoffer @brendan-hofmann @coyotesqrl
@pklinef
@stustison

DDF-2827 updated tests to use guest web context profile

---

CHANGES.md

updates changelog for 0.2.1 release
@mcalcote @Lambeaux @jrnorth @clockard 
@coyotesqrl
@figliold
@jaymcnallie
@jlcsmith
@lessarderic
@pklinef
@shaundmorris
@stustison
preview changes at https://github.com/ricklarsen/alliance/blob/CAL-240/CHANGES.md
Seeking suggestions for additional content. Leave as a comment on this PR.
n/a

CAL-240 updated changelog

---

CHANGES.md

backports changelog to 0.2.x branch.
@coyotesqrl
@jlcsmith
@lessarderic
@pklinef
@shaundmorris
Verify changelog file

CAL-240 replaced contents of CHANGES.md with jira-release-notes content

---

distribution/docs/pom.xml

removed duplicate dependency from docs/pom.xml
@coyotesqrl
@pklinef
@shaundmorris
verify pom changes.
n/a
[CAL-269](https://codice.atlassian.net/browse/CAL-269)
n/a

CAL-269 moved documentation out of documentation profile

---

catalog/imaging/imaging-actionprovider-chip/package.json
catalog/imaging/imaging-actionprovider-chip/yarn.lock

Removes version range markings in package.json files and includes the updated yarn.lock files.
@ahoffer @AzGoalie @emanns95 @djblue 
[Build](https://github.com/orgs/codice/teams/build)
@pklinef
@stustison
Run full build, then verify that catalog ui and log viewer works.
Important for ensuring control over the version used for each dependency.
[](https://codice.atlassian.net/browse/CAL-262)

CAL-262 Remove version range characters from package.json files

---

catalog/imaging/imaging-actionprovider-chip/package.json
catalog/imaging/imaging-actionprovider-chip/yarn.lock

Removes version range markings in package.json files and includes the updated yarn.lock files.
@ahoffer @AzGoalie @emanns95 @djblue 
[Build](https://github.com/orgs/codice/teams/build)
@pklinef
@stustison
Run full build, then verify that catalog ui and log viewer works.
Important for ensuring control over the version used for each dependency.
[](https://codice.atlassian.net/browse/CAL-262)

CAL-262 [Backport] Remove version range characters from package.json files 

---

catalog/imaging/imaging-plugin-nitf/pom.xml
catalog/imaging/imaging-plugin-nitf/src/main/java/org/codice/alliance/plugin/nitf/NitfPreStoragePlugin.java
catalog/imaging/imaging-plugin-nitf/src/test/java/org/codice/alliance/plugin/nitf/PreStoragePluginTest.java
catalog/imaging/imaging-plugin-nitf/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker

Backport of https://github.com/codice/alliance/pull/288
@lessarderic @jlcsmith @figliold

CAL-283 Catches exception that could cause thumbnail gen to fail

---

catalog/video/video-admin-plugin/src/main/webapp/css/index.css
catalog/video/video-admin-plugin/src/main/webapp/templates/streamMonitorTable.handlebars

This PR fixes overflow issues in the Video Admin Plugin
@glenhein 
@jlcsmith
Build / Install Experimental / Configure Stream with very large name and observe overflow handling
[CAL-265](https://codice.atlassian.net/browse/CAL-265)

CAL-265 Fixed overflow issues in Video Admin Plugin

---

distribution/docs/src/main/resources/documentation.adoc

This PR fixes issues with scrolling and usability for documentation in the admin-ui.
@coyotesqrl
@pklinef
- quickbuild with build with docs
- open admin ui and ensure docs are usable
[CAL-285](https://codice.atlassian.net/browse/CAL-285)

CAL-285: added iframeresizer to documentation to fix scrolling issue.

---

distribution/test/itests/test-itests-common/src/main/java/org/codice/alliance/test/itests/common/AbstractAllianceIntegrationTest.java

Fixes broken Alliance itests caused by a chance in the Abstract test class in DDF. 
Depends on https://github.com/codice/ddf/pull/1848
@bdeining 
@glenhein 
@kcwire
@millerw8 
Full Alliance build running all itests with `mvn clean install` from alliance root.
[CAL-286](https://codice.atlassian.net/browse/CAL-286)
[DDF-2921](https://codice.atlassian.net/browse/DDF-2921)

CAL-286: Fix Alliance itests.

---

CHANGES.md

updates changelog for version 0.2.2 
@coyotesqrl
@figliold
@kcwire
@lessarderic
@pklinef
@shaundmorris
preview at https://github.com/ricklarsen/alliance/blob/CAL-240-0.2.x/CHANGES.md#022

CAL-240 updated changelog for v 0.2.2

---

catalog/core/catalog-core-api-impl/src/main/java/org/codice/alliance/catalog/core/api/impl/types/IsrAttributes.java

Updates isr.mission-id to be multi-valued
@bdeining @brendan-hofmann 
@kcwire
[CAL-263](https://codice.atlassian.net/browse/CAL-263)

CAL-263: Changed isr.mission-id to be multi-valued

---

CHANGES.md

updates changelog for master branch.
@coyotesqrl
@jlcsmith
@kcwire
@lessarderic
@pklinef
@shaundmorris
preview at https://github.com/ricklarsen/alliance/blob/CAL-240/CHANGES.md

CAL-240 updated changelog for v 0.3.0

---

distribution/docs/src/main/resources/documentation.adoc

adds include statement for Updating System Users section of documentation.
@clockard 
@lessarderic
@pklinef
@shaundmorris
@stustison
verify section included correctly
[documentation.pdf](https://github.com/codice/alliance/files/931152/documentation.pdf)

CAL-291 adding Updating System Users section to docs

---

distribution/alliance/pom.xml
distribution/alliance/src/main/filtered-resources/etc/org.apache.karaf.features.cfg
distribution/install-profiles/src/main/resources/features.xml

adds the broker-app feature repository
@jrnorth @spearskw 
@jaymcnallie
@jlcsmith
quick build and start up alliance, check for broker-app feature repository in console.
[CAL-292](https://codice.atlassian.net/browse/CAL-292)

CAL-292 add broker-app feature repository

---

catalog/video/video-admin-plugin/src/main/webapp/css/index.css
catalog/video/video-admin-plugin/src/main/webapp/templates/streamMonitorTable.handlebars

This PR fixes overflow issues in the Video Admin Plugin
@glenhein 
@jlcsmith
Build / Install Experimental / Configure Stream with very large name and observe overflow handling
[CAL-265](https://codice.atlassian.net/browse/CAL-365)

(0.2.x) CAL-265 Fixed overflow issues in Video Admin Plugin

---

Jenkinsfile
catalog/nsili/catalog-nsili-endpoint/pom.xml
catalog/nsili/catalog-nsili-sourcestoquery-ui/package.json
catalog/nsili/catalog-nsili-sourcestoquery-ui/yarn.lock
catalog/video/video-admin-plugin/package.json
catalog/video/video-admin-plugin/yarn.lock
distribution/test/itests/test-itests-alliance/pom.xml
distribution/test/itests/test-itests-alliance/src/test/java/org/codice/alliance/test/itests/VideoTest.java
pom.xml

Add static analysis tools to alliance pipeline
Update coverage numbers in catalog-nsili-endpoint so it will pass on windows builds
Update owasp and surefire versions
Marked VedeoTest.testStreamingVideo as unstable.
@mcalcote @oconnormi 
@lessarderic
@shaundmorris
Verify build works as expected in test environment
Note: Owasp and nsp runs will fail due to findings. The findings will need to be fixed in a separate ticket.
[CAL-299](https://codice.atlassian.net/browse/CAL-299)

CAL-299 Add static analysis tools to alliance pipeline

---

distribution/docs/src/main/jdocs/content/_tables/NITF_Render_Plugin-table-contents.adoc
distribution/docs/src/main/jdocs/content/_tables/NSILI_Connected_Source-table-contents.adoc
distribution/docs/src/main/jdocs/content/_tables/NSILI_Federated_Source-table-contents.adoc
distribution/docs/src/main/jdocs/content/_tables/conf-NITF_Render_Plugin-table-contents.adoc
distribution/docs/src/main/jdocs/content/_tables/conf-NSILI_Connected_Source-table-contents.adoc
distribution/docs/src/main/jdocs/content/_tables/conf-NSILI_Federated_Source-table-contents.adoc
distribution/docs/src/main/jdocs/content/_tables/conf-org.codice.alliance.nsili.endpoint-table-contents.adoc
distribution/docs/src/main/jdocs/content/_tables/conf-org.codice.alliance.nsili.orb.impl.corbaorb-table-contents.adoc
distribution/docs/src/main/jdocs/content/_tables/conf-org.codice.alliance.transformer.video.MpegTsInputTransformer-table-contents.adoc
distribution/docs/src/main/jdocs/content/_tables/conf-org.codice.alliance.video.stream.mpegts.UdpStreamMonitor-table-contents.adoc
distribution/docs/src/main/jdocs/content/_tables/org.codice.alliance.nsili.endpoint-table-contents.adoc
distribution/docs/src/main/jdocs/content/_tables/org.codice.alliance.nsili.orb.impl.corbaorb-table-contents.adoc
distribution/docs/src/main/jdocs/content/_tables/org.codice.alliance.transformer.video.MpegTsInputTransformer-table-contents.adoc
distribution/docs/src/main/jdocs/content/_tables/org.codice.alliance.video.stream.mpegts.UdpStreamMonitor-table-contents.adoc
distribution/docs/src/main/jdocs/content/_transformers/chipping-metacard-transformer-contents.adoc
distribution/docs/src/main/jdocs/content/_transformers/mpegts-input-transformer-contents.adoc
distribution/docs/src/main/jdocs/content/_transformers/nitf-input-transformer-contents.adoc
distribution/docs/src/main/resources/_contents/_tables/NSILI_Connected_Source-table-contents.adoc
distribution/docs/src/main/resources/_contents/_transformers/chipping-metacard-transformer-contents.adoc
distribution/docs/src/main/resources/_contents/_transformers/input-transformers-contents.adoc
distribution/docs/src/main/resources/_contents/_transformers/metacard-transformers-contents.adoc
distribution/docs/src/main/resources/_contents/_transformers/mpegts-input-transformer-contents.adoc
distribution/docs/src/main/resources/_contents/_transformers/nitf-input-transformer-contents.adoc
distribution/docs/src/main/resources/_contents/_video/managing-video-contents.adoc
distribution/docs/src/main/resources/documentation.adoc

Documents Alliance transformers.
@mcalcote @vinamartin @Lambeaux @jrnorth @bdeining @troymohl 
@jaymcnallie
@jlcsmith
@lessarderic
@pklinef
@shaundmorris
review new content.
[CAL-295](https://codice.atlassian.net/browse/CAL-295)

CAL-295 added content to transformers docs

---

catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/NsiliCommonTest.java
catalog/video/video-mpegts-stream/pom.xml
catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/netty/UdpStreamProcessor.java
catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/plugins/RolloverStreamCreationPlugin.java
catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/rollover/CatalogRolloverAction.java
catalog/video/video-mpegts-stream/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/video/video-mpegts-stream/src/test/java/org/codice/alliance/video/stream/mpegts/plugins/RolloverStreamCreationPluginTest.java
catalog/video/video-mpegts-stream/src/test/java/org/codice/alliance/video/stream/mpegts/rollover/CatalogRolloverActionTest.java

@mcalcote 
@jlcsmith
@kcwire
https://codice.atlassian.net/browse/CAL-302

CAL-302 Fixed compilation failures

---

distribution/common/src/main/resources/bin/alliance.bat

Remove extra characters from bat file
@bdeining @emanns95 @AzGoalie 
@clockard 
@stustison
Boot Alliance on windows using the Alliance.bat command and observe the console output.
Previously the console would output `alliance.bat
'setlocalM' is not recognized as an internal or external command,
operable program or batch file.`
[CAL-8](https://codice.atlassian.net/browse/CAL-8)

CAL-8 Remove extra characters from bat file

---

distribution/test/itests/test-itests-alliance/pom.xml
distribution/test/itests/test-itests-common/pom.xml
distribution/test/itests/test-itests-dependencies-app/pom.xml
distribution/test/itests/test-itests-dependencies-app/src/main/filtered-resources/features.xml
pom.xml

Awaitility was added in DDF itests and needs to be included in the alliance itests now
@mcalcote @emmberk 
@lessarderic
@shaundmorris
verify build and tests pass
[CAL-304](https://codice.atlassian.net/browse/CAL-304)

CAL-304 Add awaitility to alliance itests

---

pom.xml

Removes the obr repository
@coyotesqrl
@lessarderic
@stustison
[CAL-xxxx](https://codice.atlassian.net/browse/CAL-xxxx)

CAL-307 removed obr repository

---

.gitignore

Removes erroneous pattern matching `bin`.
@dcruver @bdeining 
@clockard 
@shaundmorris
Pull down branch and confirm that git does not show any untracked files in `bin` folders.
N/A
[CAL-309](https://codice.atlassian.net/browse/CAL-309)
N/A

CAL-309 Removes incorrect ignore pattern from .gitignore.

---

catalog/imaging/imaging-nitf-impl/pom.xml
catalog/imaging/imaging-transformer-nitf/pom.xml
catalog/imaging/pom.xml
catalog/video/video-mpegts-stream/pom.xml
dependency-check-maven-config.xml
distribution/sdk/pom.xml
gitsetup/pom.xml
pom.xml

Address Alliance owasp vulnerabilities
@emmberk @ryeats 
@coyotesqrl
@lessarderic
Verify build and basic alliance functionality
[CAL-311](https://codice.atlassian.net/browse/CAL-311)

CAL-311 Address Alliance owasp vulnerabilities

---

distribution/test/itests/test-itests-alliance/src/test/java/org/codice/alliance/test/itests/NsiliSourceTest.java
pom.xml

Updates the ddf version and fixes an issue with one of the itests
@lessarderic
@shaundmorris
[CAL-316](https://codice.atlassian.net/browse/CAL-316)

CAL-316 Update DDF version to 2.10.3 and fix NsiliSourceTest

---

Jenkinsfile

Update the maven settings config file used during the deploy stage.
@oconnormi @LinkMJB 
@codice/build 
@clockard @shaundmorris 
Inspect the changed config file
The current .xml file is indeed the name of the config that allows the deployment of artifacts, but the ID is used to find the proper settings during the build stages.
[CAL-294](https://codice.atlassian.net/browse/CAL-294)
- ❗ (Exclamation Mark) This comment is critical and requires …

CAL-294 Updated Deploy step settings config

---

distribution/docs/src/main/resources/_contents/_formats/supported-file-formats-contents.adoc
distribution/docs/src/main/resources/documentation.adoc

Moves metadata attributes and catalog taxonomy to an appendix in the documentation.
@vinamartin @Lambeaux @jrnorth @ahoffer @brendan-hofmann 
@clockard 
@coyotesqrl
@lessarderic
@pklinef
@shaundmorris
review for outline/organization. New content will come from future PRs.
[CAL-226](https://codice.atlassian.net/browse/CAL-226)
[documentation.pdf](https://github.com/codice/alliance/files/1089407/documentation.pdf)

CAL-226 moved format-specific attributes to appendix.

---

PULL_REQUEST_TEMPLATE

Updates committers in the template - added Andrew, Chris, and Ben
@clockard 
@bdeining 

Updated committers in PR Template

---

distribution/alliance/src/main/filtered-resources/etc/org.codice.ddf.admin.application.service.impl.ApplicationServiceImpl.config

Exclude karaf decanter from applications list
@emmberk @mcalcote 
@coyotesqrl
@shaundmorris
[CAL-323](https://codice.atlassian.net/browse/CAL-323)

CAL-323 Exclude karaf decanter from applications list

---

catalog/security/banner-marking/pom.xml
catalog/security/banner-marking/src/main/java/org/codice/alliance/security/banner/marking/MarkingExtractor.java

Updates to support interface change. The interface change was made for performance reasons.
The DDF PR can be reviewed here (https://github.com/codice/ddf/pull/2166).
@ahoffer @rzwiefel @bdeining 
@clockard
@jlcsmith
@stustison
The unit and integration tests for the BannerMarking extractor should be sufficient.
N/A
[DDF-3177](https://codice.atlassian.net/browse/DDF-3177)
N/A

DDF-3177 Updates the MarkingExtractor to support its new InputStream-based process method

---

distribution/common/src/main/resources/etc/log4j2.config.xml
distribution/common/src/main/resources/etc/org.ops4j.pax.logging.cfg

Overrides configuration made in https://github.com/codice/ddf/pull/2154
@emmberk @mcalcote 
@clockard
@figliold
See original PR for instructions.

CAL-324 Adds configuration for failover alerts to logging config

---

distribution/docs/src/main/resources/documentation.adoc

Added Removing Expired Records section to the documentation because it has been split up from the Ingesting Data section.
This PR depends on https://github.com/codice/ddf/pull/2187.
@josephthweatt @alexaabrd @mcalcote @vinamartin 
@clockard
There is no noticeable changes from this PR. Confirm the documentation looks the same.
[CAL-326](https://codice.atlassian.net/browse/CAL-326)
- ❗ (Exclamation Mark) This comment is …

CAL-326 Added Removing Expired Records section to the documentation

---

Jenkinsfile

Specifying JAVA_HOME for windows builds, adjusting cron statement to avoid overlapping deployments, adding retry to all scm operations.
@oconnormi @LinkMJB 
@codice/build 
@clockard @shaundmorris
Run the pipeline build in a test jenkins environment and confirm the changes compile/operate as expected. Inspect the java_home change and make sure the windows path is updated correctly.
See recent jenkins failures for origin of these changes.

CAL-294 Updating Jenkinsfile for various build improvements

---

Jenkinsfile

Updates the version of Maven used for building and performing static analysis stages.
@vinamartin @LinkMJB  @rzwiefel
@codice/build 
@clockard @shaundmorris
[CAL-294](https://codice.atlassian.net/browse/CAL-294)

CAL-294 Update Maven version used during build and analysis stages

---

catalog/nsili/catalog-nsili-endpoint/pom.xml
dependency-check-maven-config.xml
pom.xml

Upgrade CXF from 3.1.7 to 3.1.11
@emmberk @stustison @clockard 
@bdeining  
@coyotesqrl 
Full build passes
Dependency check was failing. Decided on CXF 3.1.11 to stay consistent with DDF Platform
[CAL-332](https://codice.atlassian.net/browse/CAL-332)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codice/alliance/357)

CAL-332: Upgraded to CXF 3.1.11

---

catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/requests/OrderRequestImpl.java
distribution/sdk/sample-nsili-client/src/main/java/org/codice/alliance/nsili/client/SampleNsiliClient.java

Add try with resources to a few blocks - verify if there are any regressions or concerns
@emmberk @glenhein @bdeining 
@bdeining
@clockard
Build
https://sonarcloud.io/project/issues?id=org.codice%3Aalliance&resolved=false&severities=BLOCKER&types=BUG
[CAL-328](https://codice.atlassian.net/browse/CAL-328)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codice/alliance/356)

CAL-328 Resolved SonarQube Findings on resources

---

catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/StdidcAttribute.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/common/StdidcAttributeTest.java
catalog/imaging/imaging-transformer-nitf/src/test/resources/fipsToIso.properties

Fixes issue with conversion of fips country code to iso3 country code.
@roelens8 
@bdeining 
@coyotesqrl
Unit tests should cover this. 
[CAL-333](https://codice.atlassian.net/browse/CAL-333)

CAL-333 Fix STDIDC country code conversion from fips to iso3

---

catalog/video/video-mpegts-transformer/src/main/resources/DDF_Custom_Mime_Type_Resolver-mpegts.config
catalog/video/video-mpegts-transformer/src/main/resources/org.codice.alliance.transformer.video.MpegTsInputTransformer.config
dependency-check-maven-config.xml
distribution/alliance/src/main/filtered-resources/etc/org.apache.karaf.features.cfg
distribution/alliance/src/main/filtered-resources/etc/org.codice.ddf.admin.application.service.impl.ApplicationServiceImpl.config
distribution/alliance/src/main/filtered-resources/etc/org.codice.ddf.catalog.plugin.security.audit.SecurityAuditPlugin.config
distribution/common/src/main/resources/etc/org.codice.ddf.distribution.landingpage.properties.config
pom.xml

This PR upgrades the Alliance Karaf version from 4.1.1 to 4.1.2.
@vinamartin @brjeter @brendan-hofmann @paouelle
@clockard
@lessarderic
This PR must be built on top of https://github.com/codice/ddf/pull/2241.
- See test steps for https://github.com/codice/ddf/pull/2241
[CAL-317](https://codice.atlassian.net/browse/CAL-317)

CAL-317 Upgraded Karaf to 4.1.2

---

catalog/security/banner-marking/src/main/java/org/codice/alliance/security/banner/marking/BannerMarkings.java
catalog/security/banner-marking/src/main/java/org/codice/alliance/security/banner/marking/ValidationError.java

Sonarqube has identified critical bugs in Alliance which should be addressed before the next release. The issues can be found at https://sonarcloud.io/project/issues?id=org.codice%3Aalliance&resolved=false&severities=CRITICAL&types=BUG
@vinamartin 
@mcalcote 
@clockard 
@shaundmorris
[CAL-337](https://codice.atlassian.net/browse/CAL-xxx)

CAL-337 Resolve SonarQube Critical bugs

---

distribution/sdk/sdk-app/pom.xml

Fixes dependency issue
@mcalcote @emmberk @vinamartin @emanns95 
Verify build passes
[CAL-331](https://codice.atlassian.net/browse/CAL-331)

CAL-331 Fix SDK App dependency issue.

---

catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/common/StdidcAttributeTest.java

Fixes the STDIDC unit test. 
Fixes the build.
@mcalcote @emmberk 
@rzwiefel 
@bdeining 
Build passes
[CAL-333](https://codice.atlassian.net/browse/CAL-333)

CAL-331 Fix STDIDC unit test

---

catalog/video/video-mpegts-transformer/src/main/resources/DDF_Custom_Mime_Type_Resolver-mpegts.config
catalog/video/video-mpegts-transformer/src/main/resources/org.codice.alliance.transformer.video.MpegTsInputTransformer.config
distribution/alliance/src/main/filtered-resources/etc/org.codice.ddf.admin.application.service.impl.ApplicationServiceImpl.config
distribution/alliance/src/main/filtered-resources/etc/org.codice.ddf.catalog.plugin.security.audit.SecurityAuditPlugin.config
distribution/common/src/main/resources/etc/org.codice.ddf.distribution.landingpage.properties.config

This is the corresponding Alliance PR to https://github.com/codice/ddf/pull/2320.
@mackncheesiest @figliold @vinamartin
@bdeining
@lessarderic
See test steps on https://github.com/codice/ddf/pull/2320.
This change does not affect Alliance nor Aliiance itests because there are no `.config` files being modified in the itests. However, it protects against this issue in the future.
[CAL-317](https://codice.atlassian.net/browse/CAL-317)

CAL-317 Removed spaces in .config files as a work-around for a Felix bug in itests

---

catalog/imaging/imaging-actionprovider-chip/pom.xml
catalog/imaging/imaging-actionprovider-chip/src/main/resources/chipping.html
catalog/nsili/catalog-nsili-sourcestoquery-ui/pom.xml
catalog/nsili/catalog-nsili-sourcestoquery-ui/src/main/resources/index.html
catalog/video/video-admin-plugin/pom.xml
catalog/video/video-admin-plugin/src/main/resources/index.html

Implements cache busting for all Alliance ui modules.
@blen-desta 
@bdeining
See [DDF-3222 ](https://github.com/codice/ddf/pull/2225)
[CAL-330](https://codice.atlassian.net/browse/CAL-330)

CAL-330 Implemented cache busting for all Alliance ui modules.

---

catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/TreUtility.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/TreTestUtility.java

-Add input validation in "convertToFloat" and "convertToInt" using a regular expressions.
@derekwilhelm 
@coyotesqrl
@jaymcnallie
Run a full build, make sure itests pass. Ingest a NITF containing bad data, and verify that no exceptions occur.
[CAL-338](https://codice.atlassian.net/browse/CAL-338)

CAL-338 Improve input validation in TreUtility

---

Jenkinsfile

Updates Jenkinsfile to support using multi-branch pipeline in jenkins.
Various steps were updated to detect when a pull request is being built vs a regular branch
Several settings were tweaked to bring build closer to the legacy jobs in configuration.
* Updated maven memory options
* Added property to override random device on linux
* Made deploy step conditional
* Made coverity step conditional
* Made Incremental vs Full build conditional
* Set git longpath support on windows
@mcalcote @LinkMJB @clockard
Select relevant component teams:
@codice/build
Choose 2 committers to review/merge the PR.
@lessarderic
@shaundmorris
Any background context you want to provide?
What are the …

CAL-335 Updating pipeline to support multi-branch jobs

---

catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/AccessManagerImplTest.java
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/CatalogMgrImplTest.java
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/CreationMgrImplTest.java
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/NsiliCommonTestHelper.java
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/NsiliEndpointTest.java
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/NsiliLibraryImplTest.java
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/NsiliTestCommon.java
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/NsiliWebEndpointTest.java
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/OrderMgrImplTest.java
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/ProductMgrImplTest.java
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/StandingQueryMgrImplTest.java
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/SubmitStandingQueryRequestImplTest.java
catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/requests/OrderRequestImplTest.java
catalog/nsili/catalog-nsili-source/src/main/java/org/codice/alliance/nsili/source/NsiliSource.java

SonarQube has identified code smell in Alliance which should be addressed before the next release. The issues can be found at https://sonarcloud.io/project/issues?id=org.codice%3Aalliance&resolved=false&severities=BLOCKER&types=CODE_SMELL
@emmberk @vinamartin 
@clockard 
@shaundmorris 
[CAL-341](https://codice.atlassian.net/browse/CAL-xxx)

CAL-341 Resolve SonarQube Blocker severity code smells

---

Jenkinsfile

Updates the validate poms stage with the correct module for pom-fix-run. 
@mcalcote @LinkMJB 
@clockard 
@shaundmorris 
[CAL-335](https://codice.atlassian.net/browse/CAL-335)

CAL-335 Updated Validate Poms stage in jenkinsfile

---

distribution/common/pom.xml
distribution/common/src/main/resources/common-bin.xml
distribution/common/src/main/resources/version/Version.txt

This PR fixes an issue that was causing Alliance itests to fail.
@mackncheesiest @vinamartin @mcalcote @paouelle 
@bdeining
@clockard
Itests.
DDF Platform Migration requires a Version.txt file to be in <distribution_home>: https://github.com/codice/ddf/blob/dd74349c3f2260e96d74ee8a2c0383dff35c5ab0/platform/migration/platform-migration/src/main/java/org/codice/ddf/configuration/migration/ConfigurationMigrationManager.java#L100-L102.
[CAL-343](https://codice.atlassian.net/browse/CAL-343)

CAL-343 Added Version.txt to the distribution

---

catalog/nsili/catalog-nsili-common/src/main/java/org/codice/alliance/nsili/common/NsiliConstants.java
catalog/nsili/catalog-nsili-common/src/main/java/org/codice/alliance/nsili/common/NsiliManagerType.java
distribution/sdk/sample-nsili-client/src/main/java/org/codice/alliance/nsili/client/SampleNsiliClient.java
distribution/test/itests/test-itests-common/src/main/java/org/codice/alliance/test/itests/common/AbstractAllianceIntegrationTest.java

Sonarqube has identified potential vulnerabilities in Alliance which should be addressed before the next release. The issues can be found at https://sonarcloud.io/project/issues?id=org.codice%3Aalliance&resolved=false&types=VULNERABILITY
@vinamartin @mcalcote 
@clockard 
@shaundmorris 
[CAL-340](https://codice.atlassian.net/browse/CAL-340)

Cal-340 Resolve SonarQube Identified Vulnerabilities

---

pom.xml

Upgrades ddf-support version
@clockard
@coyotesqrl
@kcwire
@shaundmorris
[CAL-344](https://codice.atlassian.net/browse/CAL-344)

CAL-344 Upgraded ddf-support version

---

Jenkinsfile

Adds several optimizations to the pipeline
* Added timestamps
* Block concurrent builds
* Incremental owasp for prs
* Incremental sonar for prs
* Added longpath support on windows full build
@mcalcote @LinkMJB 
@shaundmorris 
@clockard 
[CAL-335](https://codice.atlassian.net/browse/CAL-335)

CAL-335 multi-branch-pipeline optimizations

---

catalog/imaging/imaging-transformer-nitf/pom.xml
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/common/StdidcAttributeTest.java

Copy of https://github.com/codice/alliance/pull/397 for Alliance 0.3.x
@clockard
[CAL-352](https://codice.atlassian.net/browse/CAL-352)

CAL-352 Improve stability of unit tests in StdidcAttributeTest Alliance 0.3.x

---

dependency-check-maven-config.xml
distribution/docs/pom.xml
distribution/docs/src/main/resources/content/_dependency-list/alliance-dependency-list.adoc
pom.xml

Newer versions of the asciidoctorj plugins have been released and this change points our build at them.
@AzGoalie @vinamartin 
@codice/docs 
@ricklarsen @rzwiefel 
Build, look for errors during the build process. Open the built documentation and confirm it appears as expected.
There may be conflicts between our version of jbake and the older asciidoctorj plugins
- ❗ (Exclamation Mark) This …

(0.3.x) CAL-291 Updated asciidoctorj and jbake mvn plugin versions

---

dependency-check-maven-config.xml
distribution/docs/pom.xml
distribution/docs/src/main/resources/content/_dependency-list/alliance-dependency-list.adoc
pom.xml

Newer versions of the asciidoctorj plugins have been released and this change points our build at them.
@AzGoalie @vinamartin 
@codice/docs 
@ricklarsen @rzwiefel 
Build, look for errors during the build process. Open the built documentation and confirm it appears as expected.
There may be conflicts between our version of jbake and the older asciidoctorj plugins
- ❗ (Exclamation Mark) This …

CAL-291 Updated asciidoctorj and jbake mvn plugin versions

---

distribution/common/pom.xml
distribution/common/src/main/resources/bin/alliance
distribution/common/src/main/resources/bin/alliance.bat
distribution/common/src/main/resources/common-bin.xml
pom.xml

This PR ensures that the ddf and ddf.bat scripts which implements restart behavior in case of errors is kept in the distribution and that the alliance and alliance.bat script invokes these instead of karaf and karaf.bat. It also upgrades the maven resource plugin to avoid the random corruption creating by it.
(please choose AT LEAST two reviewers that need to approve the PR before it can get merged)
@figliold
@emanns95 
@tbatie
@clockard
@coyotesqrl
1. Unzip and install the distribution on Linux and on Windows
2. Go through the installation and make sure that the restart step at the end still works
3. On Linux only, force a segmentation fault in the Java …

[0.3.x] CAL-357 Added OutOfMemory and VM error support

---

catalog/imaging/imaging-transformer-chipping/pom.xml
catalog/imaging/imaging-transformer-chipping/src/main/java/org/codice/alliance/imaging/chip/transformer/CatalogOutputAdapter.java

Resolves a static analysis finding.
(cherry picked from commit 438366f)
@glenhein @paouelle 
@bdeining
@rzwiefel
Full CI run.
[CAL-358](https://codice.atlassian.net/browse/CAL-358)

CAL-358 Ensures that resource stream will be properly closed.

---

catalog/imaging/imaging-transformer-chipping/pom.xml
catalog/imaging/imaging-transformer-chipping/src/main/java/org/codice/alliance/imaging/chip/transformer/CatalogOutputAdapter.java

Resolves a static analysis finding.
@glenhein @paouelle 
@bdeining
@rzwiefel
Full CI run.
[CAL-358](https://codice.atlassian.net/browse/CAL-358)

[0.3.x] CAL-358 Ensures that resource stream will be properly closed.

---

catalog/nsili/catalog-nsili-endpoint/pom.xml
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/requests/OrderRequestImpl.java

This PR resolves potential unclosed streams in OrderRequestImpl.
@peterhuffer @AzGoalie
@clockard
@coyotesqrl
Full build.
[CAL-360](https://codice.atlassian.net/browse/CAL-360)

[0.3.x] CAL-360 Resolved potential unclosed streams in OrderRequestImpl

---

catalog/nsili/catalog-nsili-endpoint/pom.xml
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/requests/OrderRequestImpl.java

Port of https://github.com/codice/alliance/pull/420.
@clockard 
@coyotesqrl

CAL-360 Resolved potential unclosed streams in OrderRequestImpl

---

catalog/imaging/imaging-actionprovider-chip/pom.xml
catalog/imaging/imaging-actionprovider-chip/src/main/java/org/codice/alliance/imaging/chip/actionprovider/ImagingChipActionProvider.java
catalog/imaging/imaging-actionprovider-chip/src/main/resources/chipping.html
catalog/imaging/imaging-actionprovider-chip/src/main/webapp/js/chipping.js
catalog/imaging/imaging-actionprovider-chip/src/test/groovy/org/codice/alliance/imaging/chip/actionprovider/ImageChipActionProviderSpec.groovy
catalog/imaging/imaging-actionprovider-chip/src/test/java/org/codice/alliance/imaging/chip/actionprovider/ImageChipActionProviderTest.java
catalog/imaging/imaging-transformer-chipping/src/main/java/org/codice/alliance/imaging/chip/transformer/CatalogInputAdapter.java
catalog/imaging/imaging-transformer-chipping/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/imaging/imaging-transformer-chipping/src/test/java/org/codice/alliance/imaging/chip/transformer/CatalogInputAdapterTest.java

Port of https://github.com/codice/alliance/pull/408.
@clockard
[CAL-355](https://codice.atlassian.net/browse/CAL-355)

CAL-355 Fixed Download Chip as JPEG and as NITF

---

catalog/nsili/catalog-nsili-source/src/main/java/org/codice/alliance/nsili/source/NsiliSource.java

This PR fixes a potential NPE in NsiliSource.
@peterhuffer @AzGoalie 
@clockard
@coyotesqrl
Full build.
[CAL-359](https://codice.atlassian.net/browse/CAL-359)

[0.3.x] CAL-359 Fixed potential NPE in NsiliSource

---

catalog/video/video-mpegts-stream/pom.xml
libs/stanag4609/src/main/java/org/codice/alliance/libs/stanag4609/Stanag4609TransportStreamParser.java

Port: https://github.com/codice/alliance/pull/409
@rzwiefel 
@lessarderic

CAL-353 Handles non-UTF8 country codes

---

distribution/common/pom.xml
distribution/common/src/main/resources/bin/alliance
distribution/common/src/main/resources/bin/alliance.bat
distribution/common/src/main/resources/common-bin.xml
pom.xml

*Backport PR from 0.3.x PR: [415](https://github.com/codice/alliance/pull/415)*
This PR ensures that the ddf and ddf.bat scripts which implements restart behavior in case of errors is kept in the distribution and that the alliance and alliance.bat script invokes these instead of karaf and karaf.bat. It also upgrades the maven resource plugin to avoid the random corruption creating by it.
(please choose AT LEAST two reviewers that need to approve the PR before it can get merged)
@lessarderic 
@lessarderic 
1. Unzip and install the distribution on Linux and on Windows
2. Go through the installation and make sure that the restart step at the end still works
3. On Linux only, force a …

CAL-357 Added OutOfMemory and VM error support 

---

catalog/nsili/catalog-nsili-source/src/main/java/org/codice/alliance/nsili/source/NsiliSource.java

Port of https://github.com/codice/alliance/pull/419.
@clockard
[CAL-359](https://codice.atlassian.net/browse/CAL-359)

CAL-359 Fixed potential NPE in NsiliSource

---

catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/image/NitfImageTransformer.java
catalog/video/video-mpegts-transformer/src/main/java/org/codice/alliance/transformer/video/MpegTsInputTransformer.java
distribution/test/itests/test-itests-dependencies-app/src/main/filtered-resources/features.xml
pom.xml

Port of https://github.com/codice/alliance/pull/421
@bdeining
@lessarderic
CI build
[CAL-361](https://codice.atlassian.net/browse/CAL-361)

CAL-361 Update MpegTsInputTransformer to use correct DCMI data type

---

Jenkinsfile

[0.3.x] CAL-362 Updated nsp Static Analysis stage to only scan projects using browserify or webpack

---

pom.xml

**PORT to MASTER of PR https://github.com/codice/alliance/pull/432**
Replaces inconsistent references to the DDF_HOME directory with a maven property to ensure consistent usage. 
@mcalcote @vinamartin @ahoffer @rzwiefel @garrettfreibott @emmberk 
@clockard
@coyotesqrl
@lessarderic
@pklinef
@rzwiefel
@shaundmorris
- All references to `${branding}_HOME`, `INSTALL_HOME`, or `INSTALLATION_DIR` (or others) have been replaced with the ${home_directory} property.
[DDF-3391](https://codice.atlassian.net/browse/DDF-3391)
(Depends on changes from https://github.com/codice/ddf/pull/2538
[CAL-364](https://codice.atlassian.net/browse/CAL-364)
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a …

CAL-364 updated pom with new documentation replacement

---

distribution/docs/src/main/resources/content/_dependency-list/alliance-dependency-list.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_ACFTB-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_AIMIDB-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_CSDIDA-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_CSEXRA-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_Graphic_Segment-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_HISTOA-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_Header-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_Image_Segment-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_Label_Segment-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_MTIRPB-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_PIAIMC-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_PIAPRD-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_PIATGB-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_STDIDC-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_Symbol_Segment-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_Text_Segment-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/extended-attributes-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/isr-attributes-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/security-attributes-table.adoc

Fixes appendix template in docs to allow specifying defined order to sections.
@emmberk @mcalcote @vinamartin @ahoffer @garrettfreibott 
@clockard
@coyotesqrl
@lessarderic
@pklinef
@rzwiefel
@shaundmorris
-appendix builds successfully. No content changes made.

CAL-291 updates to appendix docs template

---

catalog/imaging/imaging-transformer-chipping/pom.xml
libs/klv/pom.xml

Updates unit tests to build on locales with comma-separated decimals
@garrettfreibott @rzwiefel @mcalcote @josephthweatt 
@clockard
@rzwiefel
Set system language/locale to Swedish and run a full build. 

CAL-366 Updates unit tests to build on locales with comma separated decimals

---

distribution/docs/src/main/resources/content/_configuring/banner-markings-content-extractor.adoc
distribution/docs/src/main/resources/content/_configuring/hardening-checklist-contents.adoc

Updates configuration instructions for the "Configuring User Access" section of documentation.
@mcalcote @vinamartin @ahoffer @rzwiefel @garrettfreibott @Lambeaux @AzGoalie @emanns95 
@clockard
@coyotesqrl
@lessarderic
@pklinef
@rzwiefel
@shaundmorris
@stustison
- Verify outline and new content for accuracy.
[DDF-3351](https://codice.atlassian.net/browse/DDF-3351)
[CAL-367](https://codice.atlassian.net/browse/CAL-367)
[documentation.pdf](https://github.com/codice/alliance/files/1431829/documentation.pdf)
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or …

[0.3.x] CAL-367 updates to configuring documentation

---

distribution/docs/src/main/resources/content/_configuring/banner-markings-content-extractor.adoc
distribution/docs/src/main/resources/content/_configuring/hardening-checklist-contents.adoc

**PORT of PR https://github.com/codice/alliance/pull/439**
Updates configuration instructions for the "Configuring ~~User Access~~" section of documentation.
@mcalcote @vinamartin @ahoffer @rzwiefel @garrettfreibott @Lambeaux @AzGoalie @emanns95 
@clockard
@coyotesqrl
@lessarderic
@pklinef
@rzwiefel
@shaundmorris
@stustison
- Verify outline and new content for accuracy.
[DDF-3351](https://codice.atlassian.net/browse/DDF-3351)
[CAL-367](https://codice.atlassian.net/browse/CAL-367)
[documentation.pdf](https://github.com/codice/alliance/files/1431829/documentation.pdf)
- ❓ (Question …

CAL-367 updates to configuring documentation

---

dependency-check-maven-config.xml

Backport of PR [PR 450](https://github.com/codice/alliance/pull/450) Suppression for Solr 6.6.1 CVE-2017-12629.
@clockard
Select relevant component teams:
Choose 2 committers to review/merge the PR.
@lessarderic
@coyotesqrl
How should this be tested? (List steps with links to updated documentation)
Run OWASP
Any background context you want to provide?
What are the relevant tickets?
https://codice.atlassian.net/browse/CAL-373
Screenshots (if appropriate)
Checklist:
Documentation Updated
Update / Add Unit Tests
Update / Add Integration Tests
Review Comment Legend:
✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in …

[0.3.x] CAL-373: Added OWASP Suppression for Solr 6.6.1 CVE-2017-12629

---

dependency-check-maven-config.xml

Adds Suppression for Solr 6.6.1 CVE-2017-12629.
@clockard
Select relevant component teams:
Choose 2 committers to review/merge the PR.
@lessarderic
@coyotesqrl
How should this be tested? (List steps with links to updated documentation)
Run OWASP
Any background context you want to provide?
What are the relevant tickets?
https://codice.atlassian.net/browse/CAL-373
Screenshots (if appropriate)
Checklist:
Documentation Updated
Update / Add Unit Tests
Update / Add Integration Tests
Review Comment Legend:
✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist.
❓ (Question Mark) This comment is to …

CAL-373: Added OWASP Suppression for Solr 6.6.1 CVE-2017-12629

---

pom.xml

Update gitflow incremental builder to latest version
@codice/build @lessarderic @LinkMJB @oconnormi @clockard 
Make a trival change on top of this version bump and then use gib maven command to confirm the incremental build works.
`mvn clean install -B -T 1C -pl -Dgib.enabled=true -Dgib.referenceBranch=/refs/remotes/origin/$CHANGE_TARGET`
https://github.com/vackosar/gitflow-incremental-builder
- ❗ (Exclamation Mark) This comment is critical and …

CAL-266 Updated gitflow incremental builder to latest version

---

catalog/imaging/imaging-transformer-nitf/pom.xml
catalog/nsili/catalog-nsili-common/pom.xml
catalog/nsili/catalog-nsili-source/src/main/java/org/codice/alliance/nsili/source/NsiliFilterFactory.java
catalog/video/video-mpegts-transformer/pom.xml
gitsetup/pom.xml
libs/klv/pom.xml
pom.xml

Switches to up-to-date static analysis tool and resolves a small handful of static analysis issues in the process.
*_This change must follow https://github.com/codice/ddf/pull/2656_*
@paouelle @troymohl 
@bdeining
@clockard
Full CI build should be sufficient, though @bdeining and @troymohl may want to verify the changes made to `NsiliFilterFactory`.
[CAL-376](https://codice.atlassian.net/browse/CAL-376)

CAL-376 Removes Findbugs and installs ErrorProne.

---

distribution/docs/src/main/resources/jbake.properties

updates jbake.properties file to align with changes made in https://github.com/codice/ddf/pull/2647
@clockard
@coyotesqrl
@lessarderic
@pklinef
@rzwiefel
@shaundmorris
- content builds successfully
[CAL-371](https://codice.atlassian.net/browse/CAL-371)
[DDF-3349](https://codice.atlassian.net/browse/DDF-3349)

CAL-371 updated jbake.properties file in docs

---

dependency-check-maven-config.xml

This is the corresponding Alliance PR to https://github.com/codice/ddf/pull/2704.
@mcalcote @vinamartin @brjeter 
@clockard
@coyotesqrl
Full `-Powasp` build
[CAL-380](https://codice.atlassian.net/browse/CAL-380)

CAL-380 Suppressed warning for Xerces OWASP finding

---

pom.xml

Bumps DDF to 2.11.3-SNAPSHOT
@emmberk @peterhuffer @Lambeaux 
@clockard
@figliold
Run the build.

CAL-377 bumped DDF to 2.11.3-SNAPSHOT

---

dependency-check-maven-config.xml

Suppresses two non-applicable CVEs that are failing the build. For background, see https://github.com/codice/ddf/pull/2728
@mcalcote @vinamartin 
@clockard 
@shaundmorris 
[CAL-380](https://codice.atlassian.net/browse/CAL-380)

[0.3.x]CAL-380 Suppress camel cve that does not apply to Alliance

---

dependency-check-maven-config.xml

Suppresses two non-applicable CVEs that are failing the build. For background, see https://github.com/codice/ddf/pull/2728
@mcalcote @vinamartin 
@clockard 
@shaundmorris 
[CAL-380](https://codice.atlassian.net/browse/CAL-380)

CAL-380 Suppress camel CVE that does not apply to Alliance

---

catalog/nsili/catalog-nsili-common/src/main/java/org/codice/alliance/nsili/common/NsiliConstants.java
catalog/nsili/catalog-nsili-source/src/main/java/org/codice/alliance/nsili/source/NsiliSource.java
catalog/nsili/catalog-nsili-source/src/test/java/org/codice/alliance/nsili/source/NsiliSourceTest.java
distribution/sdk/sample-nsili-server/src/main/java/org/codice/alliance/nsili/mockserver/data/AttributeInformationGenerator.java
distribution/sdk/sample-nsili-server/src/main/java/org/codice/alliance/nsili/mockserver/server/MockNsili.java

Address remaining SonarQube Vulnerability findings
@josephthweatt @bdeining @troymohl 
@clockard
@rzwiefel 
Succesful build
[CAL-340](https://codice.atlassian.net/browse/CAL-340)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codice/alliance/443)

[0.3.x] CAL-340 Resolved SonarQube Findings

---

catalog/nsili/catalog-nsili-common/src/main/java/org/codice/alliance/nsili/common/NsiliConstants.java
catalog/nsili/catalog-nsili-source/src/main/java/org/codice/alliance/nsili/source/NsiliSource.java
catalog/nsili/catalog-nsili-source/src/test/java/org/codice/alliance/nsili/source/NsiliSourceTest.java
distribution/sdk/sample-nsili-server/src/main/java/org/codice/alliance/nsili/mockserver/data/AttributeInformationGenerator.java
distribution/sdk/sample-nsili-server/src/main/java/org/codice/alliance/nsili/mockserver/server/MockNsili.java

CAL-340 Resolved SonarQube Vulnerability Findings. Backport of https://github.com/codice/alliance/pull/443
@troymohl   @josephthweatt 
@clockard
@lessarderic
Passing build
[CAL-340](https://codice.atlassian.net/browse/CAL-340)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codice/alliance/479)

CAL-340 Resolved SonarQube Findings (#443)

---

Jenkinsfile

Removed scripted parallel stage syntax and TODOs related to the DSL.
Also fixed a typo, removed skip findbugs from commands, updated sonar url and coverage filter.
@oconnormi @mackncheesiest @vinamartin @blen-desta @LinkMJB 
@codice/build 
@clockard @shaundmorris
These changes were run in the local test jenkins under "matt test multibranch".
[CAL-296](https://codice.atlassian.net/browse/CAL-296)
- ❗ (Exclamation Mark) This comment is critical and …

CAL-296 Refactor the Jenkinsfile to match updated Jenkins DSL

---

distribution/docs/src/main/resources/content/_core-concepts/data-standards.adoc
distribution/docs/src/main/resources/content/_core-concepts/service-standards.adoc

Adds a section to the *Core Concepts* section of the documentation to enumerate standards used in Alliance. 
Seeking feedback and input on 
- Organization of information (categorization)
- Level of detail (column headers, more information needed)
- Accuracy
- Completeness.
@mcalcote @vinamartin @ahoffer @garrettfreibott @jrnorth @Lambeaux 
@jlcsmith
@kcwire
@lessarderic
@pklinef
@shaundmorris
@stustison
- builds successfully. 
- check attached pdf for section `_standards_supported_by_alliance`
[CAL-378](https://codice.atlassian.net/browse/CAL-378)
[DDF-3461](https://codice.atlassian.net/browse/DDF-3461)
~[documentation.pdf](https://github.com/codice/alliance/files/1511567/documentation.pdf)~
Updated: 
[documentation.pdf](https://github.com/codice/alliance/files/ …

CAL-378 added list of standards to alliance docs

---

catalog/plugin/catalog-plugin-defaultsecurityattributevalues/pom.xml
catalog/plugin/catalog-plugin-defaultsecurityattributevalues/src/main/java/org/codice/alliance/catalog/plugin/defaultsecurity/DefaultSecurityAttributeValuesPlugin.java
catalog/plugin/catalog-plugin-defaultsecurityattributevalues/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/plugin/catalog-plugin-defaultsecurityattributevalues/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/plugin/catalog-plugin-defaultsecurityattributevalues/src/test/java/org/codice/alliance/catalog/plugin/defaultsecurity/DefaultSecurityAttributeValuesPluginTest.java
distribution/docs/src/main/resources/content/_plugins/default-attribute-plugin.adoc
distribution/docs/src/main/resources/content/_tables/DefaultAttributeValuesPlugin.adoc

____
This PR is a port of https://github.com/codice/alliance/pull/453.
@peterhuffer @AzGoalie 
@lessarderic 
@stustison
[CAL-375](https://codice.atlassian.net/browse/CAL-375)

CAL-375 Updated the DefaultSecurityAttributeValuesPlugin to use the system high values from the etc/users.attributes file

---

dependency-check-maven-config.xml

Port of https://github.com/codice/alliance/pull/463
@brendan-hofmann @coyotesqrl

CAL-373 Removes OWASP suppression for Solr 6.6.1 

---

distribution/docs/src/main/resources/content/_core-concepts/data-standards.adoc

fixes a typo in documentation.
@mcalcote @vinamartin @ahoffer @garrettfreibott @rzwiefel 
@clockard
@coyotesqrl
@lessarderic
@rzwiefel
@shaundmorris
review content

CAL-291 Fixed typo in docs

---

pom.xml

See https://github.com/codice/ddf/pull/2513/
@oconnormi 
@clockard 
@vinamartin

DDF-3386 Upgrades yarn and frontend-maven-plugin

---

libs/pom-fix-run/yarn.lock

Updated yarn lock
@mackncheesiest @glenhein 
@jlcsmith
Full build
[DDF-3386](https://codice.atlassian.net/browse/DDF-3386)

DDF-3386 Updated yarn lock

---

catalog/core/catalog-email-impl/src/main/java/org/codice/alliance/core/email/impl/EmailSenderImpl.java

Updated past tense version of occur to `occurred` from `occured`
@vinamartin @ricklarsen @clockard @rzwiefel @shaundmorris

CAL-394 Corrected typo in 'occurred'

---

distribution/docs/src/main/resources/content/_configuring/configuring-security-default.adoc

Updates configuration instructions to include steps to set up data management plugins
Depends on changes in PR https://github.com/codice/ddf/pull/2788
@clockard
@coyotesqrl
@lessarderic
@pklinef
@rzwiefel
@shaundmorris
@stustison
content review
[DDF-3352](https://codice.atlassian.net/browse/DDF-3352)
[CAL-393](https://codice.atlassian.net/browse/CAL-393)
[documentation.pdf](https://github.com/codice/alliance/files/1582989/documentation.pdf)

CAL-393 updated configuring data mgmt docs

---

catalog/imaging/imaging-app/src/main/resources/features.xml
catalog/imaging/imaging-transformer-nitf/pom.xml
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/ExtNitfUtility.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/NitfAttributeConverters.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/NitfAttributeTransformException.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/NitfAttribute.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/NitfHeaderAttribute.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/SegmentHandler.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/StdidcAttribute.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/image/ImageAttribute.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/image/NitfImageTransformer.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/image/TextAttribute.java
catalog/imaging/imaging-transformer-nitf/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/NitfAttributeConvertersTest.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/NitfTestCommons.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/TreTestUtility.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/common/NitfHeaderAttributeTest.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/common/NitfHeaderTransformerTest.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/common/StdidcAttributeTest.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/gmti/NitfGmtiTransformerTest.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/image/ImageInputTransformerTest.java

Port forward of https://github.com/codice/alliance/pull/478 .
@emmberk @AzGoalie 
@coyotesqrl
@lessarderic
See https://github.com/codice/alliance/pull/478 instructions.
[CAL-382](https://codice.atlassian.net/browse/CAL-382)

CAL-382 Convert NITF digraphs to trigraphs

---

pom.xml

See: https://github.com/vackosar/gitflow-incremental-builder/issues/15#issuecomment-318679437
Updates default GIB behavior to perform a full build if it loses git context
@oconnormi @lessarderic @shaundmorris @vinamartin 
@lessarderic
@shaundmorris
Perform PR build on CI environment
Perform manual GIB enabled build (use options: `-Dgib.enabled=true -Dgib.referenceBranch=refs/remotes/origin/0.3.x`)
See: https://trello.com/c/7iBsxkdi
- https://codice.atlassian.net/projects/CAL/issues/CAL-395
- [N/A] Documentation Updated
- [N/A] Update / Add Unit Tests
- [N/A] Update / Add Integration Tests
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment …

[0.3.x] CAL-395 Set gib.failOnError=false

---

distribution/docs/src/main/resources/content/_configuring/configuring-security-default.adoc

**Port to `master` of PR https://github.com/codice/alliance/pull/492**
Updates configuration instructions to include steps to set up data management plugins
Depends on changes in PR https://github.com/codice/ddf/pull/2788
@clockard
@coyotesqrl
@lessarderic
@pklinef
@rzwiefel
@shaundmorris
@stustison
content review
[DDF-3352](https://codice.atlassian.net/browse/DDF-3352)
[CAL-393](https://codice.atlassian.net/browse/CAL-393)

CAL-393 updated configuring data mgmt docs (#492)

---

catalog/core/catalog-core-api-impl/src/main/java/org/codice/alliance/catalog/core/api/impl/types/IsrAttributes.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/CsexraAttribute.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/common/CsexraAttributeTest.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/image/ImageInputTransformerTest.java
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_TRE_CSEXRA-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/isr-attributes-table.adoc

Forward port of https://github.com/codice/alliance/pull/487
@peterhuffer @emmberk 
@clockard
@lessarderic

CAL-391 Changed NIIRS values from int to float.

---

Jenkinsfile

Updates the project key used for the SonarCloud stage in the Jenkins pipeline
@mcalcote @vinamartin @blen-desta @oconnormi 
@clockard
@shaundmorris
This project key has been verified as correct in the most recent Jenkins Pipeline execution of the `0.3.X` branch
[CAL-296](https://codice.atlassian.net/browse/CAL-296)

CAL-296 Updated SonarCloud project key in Jenkinsfile

---

catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/OverviewSupplier.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/OverviewSupplierTest.java

Corresponding changes to https://github.com/codice/ddf/pull/2834.
@vinamartin @AzGoalie 
@clockard
@coyotesqrl 
Full build on top of https://github.com/codice/ddf/pull/2834.
[CAL-402](https://codice.atlassian.net/browse/CAL-402)

CAL-402 Updated ddf.catalog.content.data.ContentItem#QUALIFIER to new constant name

---

dependency-check-maven-config.xml
distribution/test/itests/test-itests-alliance/pom.xml
pom.xml

Upgrade Karaf to 4.1.4
@emmberk @vinamartin @peterhuffer
@bdeining
@lessarderic
@coyotesqrl 
See testing for codice/ddf#2689
CAL-379

[0.3.x] CAL-379 Update karaf to 4.1.4

---

distribution/test/itests/test-itests-alliance/pom.xml
distribution/test/itests/test-itests-dependencies-app/pom.xml
distribution/test/itests/test-itests-dependencies-app/src/main/filtered-resources/features.xml

Back-port of https://github.com/codice/alliance/pull/385.
Depends on https://github.com/codice/ddf/pull/2882.
@tbatie 
@rzwiefel
Successful build.
Back-port of https://github.com/codice/alliance/pull/385.
[CAL-345](https://codice.atlassian.net/browse/CAL-345)

[0.3.x] CAL-345 Update pom and feature files to reflect new third-party module maven coordinates

---

distribution/common/src/main/resources/etc/definitions/isr-attributes-injector.json
distribution/common/src/main/resources/etc/definitions/security-attributes-injector.json
distribution/docs/src/main/resources/content/_metadataAttributes/extended-attributes-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/isr-attributes-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/security-attributes-table.adoc

Add ISR attributes to injections and update docs
@emmberk @peterhuffer @AzGoalie 
@bdeining
@figliold
@pklinef
Same process as in https://github.com/codice/ddf/pull/2875
[CAL-405](https://codice.atlassian.net/browse/CAL-405)
[documentation.pdf](https://github.com/codice/alliance/files/1660919/documentation.pdf)

[0.3.x] CAL-405 Add ISR attributes to injections and update docs

---

distribution/common/src/main/resources/etc/definitions/isr-attributes-injector.json
distribution/common/src/main/resources/etc/definitions/security-attributes-injector.json
distribution/docs/src/main/resources/content/_metadataAttributes/extended-attributes-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/isr-attributes-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/security-attributes-table.adoc

Port of https://github.com/codice/alliance/pull/513
@figliold
CI Build
[CAL-705](https://codice.atlassian.net/browse/CAL-405)

CAL-405 Add ISR attributes to injections and update docs (#513)

---

catalog/imaging/imaging-actionprovider-chip/src/main/webapp/js/chipping.js

**What does this PR do?**
Port of 
[#519](https://github.com/codice/alliance/pull/519)
**Who is reviewing it?**
@emmberk
@peterhuffer
**Choose 2 committers to review/merge the PR.**
@bdeining
@clockard
**What are the relevant tickets?**
[CAL-406](https://codice.atlassian.net/browse/CAL-406)

[0.3.x] CAL-406 Updated Chipping.js to allow bounding selection from all directions

---

dependency-check-maven-config.xml

Suppress invalid Jackson owasp finding
@emmberk @peterhuffer 
@bdeining
@shaundmorris
CI Build
[CAL-411](https://codice.atlassian.net/browse/CAL-411)

CAL-411 Suppress invalid Jackson owasp finding

---

dependency-check-maven-config.xml

Suppress invalid Jackson owasp finding (#525)
Port of https://github.com/codice/alliance/pull/525
@bdeining
@rzwiefel
CI Build
[CAL-411](https://codice.atlassian.net/browse/CAL-411)

CAL-411 Suppress invalid Jackson owasp finding (#525)

---

distribution/docs/src/main/resources/content/_applicationReferences/mg-ic-security.adoc
distribution/docs/src/main/resources/content/_applicationReferences/mg-imaging.adoc
distribution/docs/src/main/resources/content/_applicationReferences/mg-nsili.adoc
distribution/docs/src/main/resources/content/_applicationReferences/mg-video.adoc

Refactors appendix sections to match template updates in PR https://github.com/codice/ddf/pull/2912
@clockard
@coyotesqrl
@lessarderic
@rzwiefel
@shaundmorris
verify formatting on appendix section headers
[DDF-3554](https://codice.atlassian.net/browse/DDF-3554)
[CAL-403](https://codice.atlassian.net/browse/CAL-403)

CAL-403 updated appendix docs

---

catalog/core/catalog-core-api-impl/src/main/java/org/codice/alliance/catalog/core/api/impl/types/IsrAttributes.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/PiaimcAttribute.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/common/PiaimcAttributeTest.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/image/ImageInputTransformerTest.java
catalog/nsili/catalog-nsili-common/src/main/java/org/codice/alliance/nsili/common/ResultDAGConverter.java
catalog/nsili/catalog-nsili-common/src/test/java/org/codice/alliance/nsili/common/ResultDAGConverterTest.java
catalog/nsili/catalog-nsili-transformer/src/main/java/org/codice/alliance/nsili/transformer/DAGConverter.java
catalog/nsili/catalog-nsili-transformer/src/test/java/org/codice/alliance/nsili/transformer/DAGConverterTest.java
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_TRE_PIAIMC-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/isr-attributes-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/nsili-attributes-table.adoc

CAL-412 Updated Cloud Cover to be a float.  Updated NSILI transformer accordingly
@troymohl @beyelerb 
@jlcsmith
Full Build
[CAL-412](https://codice.atlassian.net/browse/CAL-412)

CAL-412 Updated Cloud Cover to be a float

---

catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/RoutingSlipTest.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/TreUtilityTest.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/common/NitfHeaderTransformerTest.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/gmti/NitfGmtiTransformerTest.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/image/ImageInputTransformerTest.java

Renames a test file conform with standards.
@vinamartin @mcalcote @ahoffer
@clockard
@rzwiefel
Run the test files
[CAL - 409] (https://codice.atlassian.net/browse/CAL-409)

CAL-409 Renamed unit test files

---

distribution/docs/src/main/resources/content/_transformers/chipping-metacard-transformer.adoc
distribution/docs/src/main/resources/content/_transformers/mpegts-input-transformer.adoc
distribution/docs/src/main/resources/content/_transformers/nitf-input-transformer.adoc

As part of improvements made to Ingest instructions in PR https://github.com/codice/ddf/pull/2927, made minor edits to the input transformer documentation. 
@mcalcote @vinamartin @garrettfreibott @ahoffer 
@clockard
@coyotesqrl
@lessarderic
@rzwiefel
@shaundmorris
Build https://github.com/codice/ddf/pull/2927 prior to building this, review content renders correctly
[DDF-3579](https://codice.atlassian.net/browse/DDF-3579)
[CAL-410](https://codice.atlassian.net/browse/CAL-410)

CAL-410 updated input transformer docs

---

pom.xml

Aligns with changes to displaying default URLs in documentation. See also PR https://github.com/codice/ddf/pull/2955
@clockard
@coyotesqrl
@lessarderic
@rzwiefel
@shaundmorris

CAL-291 fixed formatting for sample Alliance urls in docs

---

distribution/docs/src/main/resources/content/_transformers/chipping-metacard-transformer.adoc
distribution/docs/src/main/resources/content/_transformers/mpegts-input-transformer.adoc
distribution/docs/src/main/resources/content/_transformers/nitf-input-transformer.adoc

**Port to `master` of PR https://github.com/codice/alliance/pull/527**
As part of improvements made to Ingest instructions in PR https://github.com/codice/ddf/pull/2927, made minor edits to the input transformer documentation. 
@mcalcote @vinamartin @garrettfreibott @ahoffer 
@clockard
@coyotesqrl
@lessarderic
@rzwiefel
@shaundmorris
Build https://github.com/codice/ddf/pull/2927 prior to building this, review content renders correctly
[DDF-3579](https://codice.atlassian.net/browse/DDF-3579)
[CAL-410](https://codice.atlassian.net/browse/CAL-410)

CAL-410 updated input transformer docs (#527)

---

catalog/video/video-mpegts-transformer/src/test/java/org/codice/alliance/transformer/video/MpegTsInputTransformerTest.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/CopyPresentKlvProcessorTest.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/LocationKlvProcessorTest.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/SetDatesKlvProcessorTest.java

Refactor BasicTypes.BASIC_METACARD usages to MetacardImpl.BASIC_METACARD
Depends on https://github.com/codice/ddf/pull/2983
@emmberk @peterhuffer 
@bdeining
@coyotesqrl
CI build
[CAL-416](https://codice.atlassian.net/browse/CAL-416)

CAL-416 Refactor BasicTypes.BASIC_METACARD usages to MetacardImpl.BASIC_METACARD

---

pom.xml

Upgrade to Jacoco 0.8.0
@codice/build 
@codice/test 
@bdeining
@clockard
@lessarderic 
Successful build on Windows and Linux
[CAL-417](https://codice.atlassian.net/browse/CAL-417)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codice/alliance/538)

CAL-417 Upgraded to Jacoco 0.8.0

---

catalog/imaging/imaging-app/src/main/resources/features.xml
catalog/nsili/nsili-app/src/main/resources/features.xml
catalog/security/security-app/src/main/resources/features.xml
catalog/video/video-app/src/main/resources/features.xml
distribution/alliance-branding-app/src/main/resources/features.xml
distribution/common/src/main/resources-filtered/etc/application-definitions/alliance-security.json
distribution/common/src/main/resources-filtered/etc/application-definitions/imaging.json
distribution/common/src/main/resources-filtered/etc/application-definitions/nsili.json
distribution/common/src/main/resources-filtered/etc/application-definitions/video.json
distribution/install-profiles/src/main/resources/features.xml
distribution/sdk/sdk-app/src/main/resources/features.xml

See https://github.com/codice/ddf/pull/2986
@emanns95 
@paouelle 
@figliold 
@pklinef 
Ensure install profiles are working as expected and each application tab shows configurations and plugins as before.

CAL-418: Decouple Applications from karaf features

---

catalog/nsili/catalog-nsili-sourcestoquery-ui/src/main/webapp/main.js
catalog/video/video-admin-plugin/pom.xml
catalog/video/video-admin-plugin/src/main/webapp/main.js

Upgrade the moment library to 2.20.1
@emmberk @peterhuffer @kcover @djblue 
@rzwiefel
Install alliance and verify that date/time functions in Intrigue and the admin ui still work.
[CAL-419](https://codice.atlassian.net/browse/CAL-419)

CAL-419 Update moment to 2.20.1

---

distribution/docs/src/main/resources/content/_applicationReferences/mg-nsili.adoc
distribution/docs/src/main/resources/content/_applicationReferences/mg-video.adoc

See PR title
(please choose AT LEAST two reviewers that need to approve the PR before it can get merged)
@emanns95 
@vinamartin 
@rzwiefel 
CI passes
[](https://codice.atlassian.net/browse/)
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may …

CAL-418: Update documentation to reflect application/karaf feature decoupling

---

catalog/core/catalog-email-impl/src/main/java/org/codice/alliance/core/email/impl/EmailSenderImpl.java
catalog/imaging/imaging-service-impl/src/main/java/org/codice/alliance/imaging/chip/service/impl/ChipServiceImpl.java
catalog/imaging/imaging-transformer-chipping/src/main/java/org/codice/alliance/imaging/chip/transformer/AbstractJpegService.java
catalog/imaging/imaging-transformer-chipping/src/main/java/org/codice/alliance/imaging/chip/transformer/CatalogInputAdapter.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/RoutingSlip.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/gmti/NitfGmtiTransformer.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/image/ImageAttribute.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/image/NitfImageTransformer.java
catalog/nsili/catalog-nsili-common/src/main/java/org/codice/alliance/nsili/common/BqsConverter.java
catalog/nsili/catalog-nsili-common/src/main/java/org/codice/alliance/nsili/common/NsiliAttributeMap.java
catalog/nsili/catalog-nsili-common/src/main/java/org/codice/alliance/nsili/common/NsiliClassificationComparator.java
catalog/nsili/catalog-nsili-common/src/main/java/org/codice/alliance/nsili/common/NsiliCommonUtils.java
catalog/nsili/catalog-nsili-common/src/main/java/org/codice/alliance/nsili/common/datamodel/NsiliAttributesGenerator.java
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/LibraryImpl.java
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/NsiliEndpoint.java
catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/requests/SubmitStandingQueryRequestImpl.java
catalog/nsili/catalog-nsili-orb-impl/src/main/java/org/codice/alliance/nsili/orb/impl/CorbaOrbImpl.java
catalog/nsili/catalog-nsili-source/src/main/java/org/codice/alliance/nsili/source/NsiliFilterDelegate.java
catalog/nsili/catalog-nsili-source/src/main/java/org/codice/alliance/nsili/source/NsiliFilterFactory.java
catalog/nsili/catalog-nsili-source/src/main/java/org/codice/alliance/nsili/source/NsiliSource.java
catalog/nsili/catalog-nsili-sourcestoquery-ui/src/main/java/org/codice/alliance/nsili/sourcestoquery/ui/service/SourcesToQuery.java
catalog/nsili/catalog-nsili-transformer/src/main/java/org/codice/alliance/nsili/transformer/DAGConverter.java
catalog/video/video-admin-plugin/src/main/java/org/codice/alliance/video/ui/service/StreamMonitorHelper.java
catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/UdpStreamMonitor.java
catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/netty/BitReader.java
catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/rollover/CatalogRolloverAction.java
distribution/sdk/sample-nsili-server/src/main/java/org/codice/alliance/nsili/mockserver/data/DAGGenerator.java

Addresses various Sonarqube findings.
@brjeter 
@blen-desta 
@bakejeyner 
@clockard
@coyotesqrl 
Bug listing can be found here: https://sonarcloud.io/project/issues?id=org.codice%3Aalliance&resolved=false&types=BUG
[CAL-415](https://codice.atlassian.net/browse/CAL-xxx)

CAL-415 Addressd Sonarqube bug findings

---

distribution/common/src/main/resources/security/alliance.policy

@SmithJosh @ahoffer @Lambeaux @lessarderic @oconnormi 
@coyotesqrl
@pklinef
@stustison

CAL-408 updated to work with security manager

---

catalog/imaging/pom.xml
distribution/docs/src/main/resources/content/_dependency-list/alliance-dependency-list.adoc

Partial port of https://github.com/codice/alliance/pull/541
@bdeining
@lessarderic
CI Build
[CAL-413](https://codice.atlassian.net/browse/CAL-413)

CAL-413 Update jpeg2000 library to latest codice version (#541)

---

catalog/nsili/catalog-nsili-sourcestoquery-ui/src/main/webapp/main.js
catalog/video/video-admin-plugin/pom.xml
catalog/video/video-admin-plugin/src/main/webapp/main.js

Port of https://github.com/codice/alliance/pull/540
@rzwiefel
@shaundmorris
CI Build
[CAL-419](https://codice.atlassian.net/browse/CAL-419)

CAL-419 Update moment to 2.20.1 (#540)

---

distribution/alliance/pom.xml
distribution/alliance/src/main/filtered-resources/etc/org.apache.karaf.features.cfg

See title.
@tbatie 
@adimka 
@pklinef
See https://github.com/codice/ddf/pull/2911
See https://github.com/codice/ddf/pull/2911
[CAL-426](https://codice.atlassian.net/browse/CAL-426)

CAL-426 Updates alliance to use new DDF UI feature

---

distribution/test/itests/test-itests-alliance/src/test/java/org/codice/alliance/test/itests/NsiliSourceTest.java
distribution/test/itests/test-itests-common/src/main/java/org/codice/alliance/test/itests/common/AbstractAllianceIntegrationTest.java

Ignore flaky nsili itests. 
@emmberk @peterhuffer @troymohl 
@bdeining
@shaundmorris
CI Build
[CAL-427](https://codice.atlassian.net/browse/CAL-427)

CAL-427 Ignore flaky nsili itests

---

catalog/nsili/catalog-nsili-endpoint/pom.xml
catalog/nsili/catalog-nsili-source/pom.xml
distribution/alliance/pom.xml
distribution/docs/pom.xml
distribution/sdk/pom.xml
gitsetup/pom.xml
pom.xml

The current nightly builds of Alliance contain various warnings. These warnings may lead to build instability. This PR addresses them.
@brjeter @blen-desta @bakejeyner 
@coyotesqrl 
@shaundmorris 
[CAL-425](https://codice.atlassian.net/browse/CAL-xxx)

CAL-425 Resolved maven build warnings

---

distribution/alliance/pom.xml
distribution/alliance/src/main/filtered-resources/etc/org.apache.karaf.features.cfg
distribution/test/itests/test-itests-dependencies-app/src/main/filtered-resources/features.xml

See https://github.com/codice/ddf/pull/2896
@Lambeaux 
@ryeats 
@figliold 
@pklinef
Ensure a normal install works, no bundles start up incorrectly and flex general functionality

CAL-433: Break apart platform-app feature file into several feature files

---

Jenkinsfile

Multithreaded builds have proven to be inconsistent and unstable. This change will improve stability by reverting to single-threaded builds.
@oconnormi @LinkMJB @clockard @mackncheesiest @shaundmorris 
@codice/build 
[CAL-439](https://codice.atlassian.net/browse/CAL-439)
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be …

CAL-439 Jenkinsfile single-threaded build update

---

Jenkinsfile

Multithreaded builds have proven to be inconsistent and unstable. This change will improve stability by reverting to single-threaded builds.
@oconnormi @LinkMJB @clockard @mackncheesiest @shaundmorris @brendan-hofmann @vinamartin 
@codice/build 
[CAL-439](https://codice.atlassian.net/browse/CAL-439)
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required …

0.3.X CAL-439 Jenkinsfile single-threaded build update

---

distribution/docs/pom.xml
distribution/docs/src/main/resources/content/_core-concepts/data-standards.adoc
distribution/docs/src/main/resources/content/_core-concepts/high-availability-supported-capabilities-alliance.adoc
distribution/docs/src/main/resources/content/_core-concepts/service-standards.adoc
distribution/docs/src/main/resources/content/_endpoints/nsili-endpoint.adoc
distribution/docs/src/main/resources/content/_introduction/applications.adoc
distribution/docs/src/main/resources/content/_introduction/introduction.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/attribute-mappings.adoc
distribution/docs/src/main/resources/content/_sources/nsili-connected.adoc
distribution/docs/src/main/resources/content/_sources/nsili-federated.adoc
distribution/docs/src/main/resources/content/_tables/nsili.endpoint.adoc
distribution/docs/src/main/resources/content/introduction.adoc

updates documentation content for improvements to documentation template. 
adds a new document, a standalone Overview/executive summary to be published with the full documentation compendium. (Relies on changes included in https://github.com/codice/ddf/pull/3248)
@mcalcote @ahoffer @rzwiefel @austinsteffes @garrettfreibott 
@lessarderic
@rzwiefel
@shaundmorris
- existing documentation still builds successfully. 
- new introduction.html/pdf is produced
[DDF-3816](https://codice.atlassian.net/browse/DDF-3816
[CAL-427](https://codice.atlassian.net/browse/CAL-427)

CAL-437 updated docs for new templates

---

distribution/common/src/main/resources/security/configurations.policy

Fix CDM section in configurations.policy so following docs works
Adds CDM permissions example
@emmberk @kcover @JGatley 
@clockard
@coyotesqrl
Follow documentation to setup CDM in place directory monitor and ingest a NITF. Verify successful ingest and downloading of product.
Copy paste fail :(
[CAL-413](https://codice.atlassian.net/browse/CAL-413)

CAL-413 fix alliance CDM policy section

---

pom.xml

Update Alliance to point at the latest snapshot of DDF.
@rzwiefel @clockard 
[CAL-444](https://codice.atlassian.net/browse/CAL-444)

CAL-444 Update DDF Version declared in root POM

---

distribution/docs/src/main/resources/content/_managing/attributes-added-by-pre-ingest-plugins.adoc

This PR updates the documentation to explain how attributes are added to metacards during ingestion/querying.
@blen-desta
@brjeter
@emanns95
@SmithJosh
@clockard
@coyotesqrl
@ricklarsen
1. Build DDF
2. Check to make sure the documentation includes this section
[CAL-441](https://codice.atlassian.net/browse/CAL-441)
[DDF-3876](https://codice.atlassian.net/browse/3876)
[DDF](https://github.com/codice/ddf/pull/3311)

CAL-441 Update documentation to explain how attributes are added to metacards.

---

catalog/imaging/imaging-actionprovider-chip/pom.xml
catalog/imaging/imaging-service-api/pom.xml
catalog/imaging/imaging-transformer-chipping/pom.xml
catalog/imaging/imaging-transformer-nitf/pom.xml
catalog/nsili/catalog-nsili-transformer/pom.xml
catalog/pom.xml
catalog/video/video-mpegts-stream/pom.xml
catalog/video/video-mpegts-transformer/pom.xml
libs/klv/pom.xml
pom.xml

@clockard
@coyotesqrl
@lessarderic
@rzwiefel
@shaundmorris
@stustison

CAL-442 upgrade geotools and other dependencies to latest versions

---

catalog/nsili/catalog-nsili-endpoint/pom.xml
catalog/video/video-mpegts-stream/pom.xml
distribution/docs/src/main/resources/content/_dependency-list/alliance-dependency-list.adoc
distribution/test/itests/test-itests-alliance/src/test/java/org/codice/alliance/test/itests/BannerMarkingsTest.java
distribution/test/itests/test-itests-common/pom.xml
pom.xml

Upgrades libraries.
*Note: I believe there is a security permission issue, unrelated to this change, with the `video-app` feature. I will be testing that further and potentially resolving in another PR.*
@mcalcote @brjeter 
@bdeining
@stustison
Full regression tests of an installation, in particular testing those modules where `Import-Package` exclusions were added.
[CAL-445](https://codice.atlassian.net/browse/CAL-445)
[DDF-3920](https://codice.atlassian.net/browse/DDF-3920)

CAL-445 Upgrades to latest wss4j and cxf library versions to match DDF.

---

PULL_REQUEST_TEMPLATE

https://github.com/codice/ddf/pull/3420
Adds @tbatie and @vinamartin to list of committers 
@shaundmorris @tbatie @coyotesqrl @rzwiefel @jlcsmith

Adds Tracy Batie and Vina Martin to list of committers

---

dependency-check-maven-config.xml

Suppresses CVE-2018-1270 and CVE-2018-1275.
@peterhuffer 
@clockard
@shaundmorris
Successful CI build with no OWASP findings.
Related to https://github.com/codice/ddf/pull/3417
[CAL-456](https://codice.atlassian.net/browse/CAL-456)

CAL-456 Address OWASP finding related to Spring Framework's spring-messaging module

---

distribution/test/itests/test-itests-alliance/pom.xml

update itests to work with external solr
`anyone`
running itests
[CAL-458](https://codice.atlassian.net/browse/CAL-458)

CAL-458 update itests to work with external solr

---

distribution/test/itests/test-itests-alliance/pom.xml

update itests to work with external solr
`anyone`
running itests
[CAL-458](https://codice.atlassian.net/browse/CAL-458)

[1.1.x] CAL-458 update itests to work with external solr

---

distribution/common/src/main/resources/common-bin.xml

FORWARD PORT OF PR 596
Copies over necessary Solr scripts
@peterhuffer 
@mcalcote 
@austinsteffes 
@clockard
@rzwiefel
Build and start Alliance. Upload a document to be sure Alliance is successfully communicating with Solr.
- [NA] Documentation Updated
- [NA] Update / Add Unit Tests
- [NA] Update / Add Integration Tests

CAL-458 Copy Solr scripts

---

distribution/docs/src/main/resources/content/_plugins/nitf-post-process-plugin.adoc
distribution/docs/src/main/resources/content/_plugins/nitf-render-plugin.adoc
distribution/docs/src/main/resources/content/architecture.adoc

*BACKPORT of PR https://github.com/codice/alliance/pull/591*
Updates documentation templates to add a standalone "architecture" reference.
@mcalcote @garrettfreibott @ahoffer @austinsteffes 
@lessarderic
@rzwiefel
@shaundmorris
builds successfully (no content changes made at this time)
[CAL-449](https://codice.atlassian.net/browse/CAL-449)

CAL-449 added a standalone architecture doc

---

distribution/docs/pom.xml
distribution/docs/src/main/resources/content/config.adoc
distribution/docs/src/main/resources/content/developing.adoc

updated docs template to publish developers' guide as standalone document.
@mcalcote @ahoffer @garrettfreibott @austinsteffes 
@clockard
@coyotesqrl
@lessarderic
@rzwiefel
@shaundmorris
builds successful
[CAL-450](https://codice.atlassian.net/browse/CAL-450)

CAL-450 updated docs template to add developer guide

---

distribution/alliance-branding-app/src/main/resources/features.xml

See https://github.com/codice/ddf/pull/3540
@ryeats 
@clockard 
@figliold
@stustison
@coyotesqrl 
Distribution successfully starts up.
[](https://codice.atlassian.net/browse/)
- ❗ (Exclamation Mark) This comment is …

[1.1.x] CAL-433: Ensure filter delegate runs before any context paths are registered with Jetty

---

distribution/common/src/main/resources/common-bin.xml

Forward port of https://github.com/codice/alliance/pull/602
This allows the system to be run with the start.bat scripts.
@clockard @rzwiefel @kcover @ahoffer @austinsteffes @peterhuffer @taz77 @kcrowe01 
Build, unzip the distribution and confirm service.ps1 is present in the bin directory.

CAL-458 Update common-bin to include DDF ps script

---

pom.xml

Fix stability issues in itests
NOTE: This PR requires: https://github.com/codice/ddf/pull/3557
@ethantmanns 
@clockard
@tbatie
CI Build

Fix stability issues in itests

---

Jenkinsfile

See https://github.com/codice/ddf/pull/3597.
@LinkMJB @mcalcote @oconnormi
@clockard
CI build
[CAL-462](https://codice.atlassian.net/browse/CAL-462)

[1.1.x] CAL-462 Removed "skipDocs" from quickbuild step on PR builds prior to GIB

---

Jenkinsfile

Link to 1.1.x PR: https://github.com/codice/alliance/pull/610
____
@clockard @ricklarsen 
[CAL-462](https://codice.atlassian.net/browse/CAL-462)
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews.

CAL-462 Removed "skipDocs" from quickbuild step on PR builds prior to GIB

---

catalog/nsili/catalog-nsili-source/pom.xml
catalog/nsili/catalog-nsili-source/src/main/java/org/codice/alliance/nsili/source/NsiliSource.java
catalog/nsili/catalog-nsili-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/nsili/catalog-nsili-source/src/test/java/org/codice/alliance/nsili/source/NsiliSourceTest.java
catalog/nsili/nsili-app/src/main/resources/features.xml
distribution/docs/src/main/resources/content/_dependency-list/alliance-dependency-list.adoc
distribution/sdk/sample-nsili-client/pom.xml
distribution/sdk/sample-nsili-client/src/main/java/org/codice/alliance/nsili/client/Client.java
distribution/sdk/sample-nsili-client/src/main/java/org/codice/alliance/nsili/client/SampleNsiliClient.java
distribution/sdk/sdk-app/src/main/resources/features.xml
distribution/test/itests/test-itests-alliance/src/test/java/org/codice/alliance/test/itests/NsiliEndpointTest.java

@brjeter @pklinef 
@clockard
@coyotesqrl
@stustison

CAL-461 update to work with security architecture changes in DDF

---

catalog/nsili/catalog-nsili-source/pom.xml
catalog/nsili/catalog-nsili-source/src/main/java/org/codice/alliance/nsili/source/NsiliSource.java
catalog/nsili/catalog-nsili-source/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/nsili/catalog-nsili-source/src/test/java/org/codice/alliance/nsili/source/NsiliSourceTest.java
catalog/nsili/nsili-app/src/main/resources/features.xml
distribution/docs/src/main/resources/content/_dependency-list/alliance-dependency-list.adoc
distribution/sdk/sample-nsili-client/pom.xml
distribution/sdk/sample-nsili-client/src/main/java/org/codice/alliance/nsili/client/Client.java
distribution/sdk/sample-nsili-client/src/main/java/org/codice/alliance/nsili/client/SampleNsiliClient.java
distribution/sdk/sdk-app/src/main/resources/features.xml
distribution/test/itests/test-itests-alliance/src/test/java/org/codice/alliance/test/itests/NsiliEndpointTest.java

ABBREVIATED REVIEW BETWEEN 1.1.X AND MASTER IS IN EFFECT
Link to master PR: https://github.com/codice/alliance/pull/609
Refactors some of the security modules and updates everything else accordingly
@lessarderic
@pklinef
@stustison

CAL-461 update to work with security architecture changes in DDF (#609)

---

catalog/core/catalog-email-api/pom.xml
catalog/core/catalog-email-impl/pom.xml
catalog/pom.xml
distribution/docs/src/main/resources/content/_dependency-list/alliance-dependency-list.adoc
pom.xml

CAL-137 Updated javax mail version

---

dependency-check-maven-config.xml

back porting
@jhunzik @brjeter 
@figliold 
@tbatie 
[CAL-465](https://codice.atlassian.net/browse/CAL-465)

[1.1.x]CAL-465 Suppressed jetty CVEs that no longer apply

---

distribution/alliance-branding-app/src/main/resources/features.xml

See https://github.com/codice/ddf/pull/3540
@ryeats 
@clockard 
@figliold
@stustison
@coyotesqrl 
Distribution successfully starts up.
[](https://codice.atlassian.net/browse/)
- ❗ (Exclamation Mark) This comment is …

CAL-433: Ensure filter delegate runs before any context paths are registered with Jetty

---

dependency-check-maven-config.xml

fixes dependency-check errors
@jhunzik @brjeter 
@tbatie @figliold 
[CAL-465](https://codice.atlassian.net/browse/CAL-465)

CAL-465 Suppressed jetty CVEs that no longer apply

---

distribution/docs/pom.xml
distribution/docs/src/main/resources/content/_dependency-list/alliance-dependency-list.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_Header-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_Segment_Graphic-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_Segment_Image-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_Segment_Label-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_Segment_Symbol-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_Segment_Text-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_TRE_ACFTB-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_TRE_AIMIDB-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_TRE_CSDIDA-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_TRE_CSEXRA-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_TRE_EXPLTB-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_TRE_HISTOA-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_TRE_MTIRPB-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_TRE_PIAIMC-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_TRE_PIAPRD-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_TRE_PIATGB-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/NITF_TRE_STDIDC-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/attribute-mappings.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/extended-attributes-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/isr-attributes-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/nsili-attributes-table.adoc
distribution/docs/src/main/resources/content/_metadataAttributes/security-attributes-table.adoc
distribution/docs/src/main/resources/content/reference.adoc

updates docs templates to publish standalone reference guide for apps, whitelists, and dependency list.
*Depends on changes in this PR: [DDF-3891](https://github.com/codice/ddf/pull/3633)*
@lessarderic
@rzwiefel
@shaundmorris
builds successfully and creates `reference.html` and `reference.pdf`
[DDF-3891](https://codice.atlassian.net/browse/DDF-3891)
[CAL-451](https://codice.atlassian.net/browse/CAL-451)

CAL-451 updated docs template to add ref guide

---

catalog/video/video-mpegts-stream/pom.xml
catalog/video/video-mpegts-stream/src/test/java/org/codice/alliance/video/stream/mpegts/plugins/FindChildrenStreamEndPluginTest.java
catalog/video/video-mpegts-stream/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker

ABBREVIATED REVIEW BETWEEN 1.1.X AND MASTER IS IN EFFECT
forward porting from #608 
@ethantmanns @jhunzik 
@tbatie @figliold 
get changes and test respective unit tests
[CAL-460](https://codice.atlassian.net/browse/CAL-460)

CAL-460 Changed to allow mocking of final methods/classes

---

distribution/docs/src/main/resources/content/_reference/hardening-checklist-contents.adoc

Move the hardening checklist to the appendix.
@ricklarsen @ahoffer @vinamartin @austinsteffes @garrettfreibott 
Build the docs module with unit tests and confirm the rendered document has a hardening checklist in the appendix. 
[CAL-451](https://codice.atlassian.net/browse/CAL-451)

CAL-451 Move hardening checklist to appendix

---

distribution/common/src/main/resources/common-bin.xml

Add new file to common-bin assembly file.
@austinsteffes @mcalcote @ricklarsen 
@clockard
@figliold

[1.1.x] CAL-240 Add file to assembly

---

distribution/common/src/main/resources/common-bin.xml

Adds a new file to the common-bin assembly
@mcalcote @clockard @austinsteffes 
@clockard
@figliold

CAL-240 Add new file to assembly

---

catalog/nsili/catalog-nsili-source/src/main/java/org/codice/alliance/nsili/source/NsiliSource.java
distribution/docs/pom.xml
distribution/docs/src/main/resources/content/_dependency-list/alliance-dependency-list.adoc
distribution/docs/src/test/java/alliance/docs/DocumentationTest.java

Do not merge until https://github.com/codice/ddf/pull/3656 is merged
Remove references to Search UI artifacts
@kcover @emmberk @garrettfreibott @ethantmanns 
@vinamartin
Full build.
[CAL-466](https://codice.atlassian.net/browse/CAL-466)

CAL-466 Remove references to Search UI artifacts

---

distribution/docs/src/main/resources/content/_applicationReferences/mg-ic-security.adoc
distribution/docs/src/main/resources/content/_applicationReferences/mg-imaging.adoc
distribution/docs/src/main/resources/content/_applicationReferences/mg-nsili.adoc
distribution/docs/src/main/resources/content/_applicationReferences/mg-video.adoc

Copy edits to documentation application reference sections.
@clockard
@lessarderic
@shaundmorris
content changes only.

CAL-291 copy edits to sources and applications docs

---

distribution/test/itests/test-itests-alliance/pom.xml

Update Solr port for itests
@emmberk @ahoffer @kcover 
@clockard
@coyotesqrl
@vinamartin
Itests
https://github.com/codice/ddf/commit/d63c09ce5bb71b1313c568054dc82b3ab646d1ec
[CAL-470](https://codice.atlassian.net/browse/CAL-470)

CAL-470 Update Solr port for itests

---

catalog/imaging/pom.xml
distribution/docs/src/main/resources/content/_reference/_dependency-list/alliance-dependency-list.adoc

Link to 1.1.x PR: #628 
____
@emmberk @ryeats @kcover
@clockard
@coyotesqrl
[CAL-467](https://codice.atlassian.net/browse/CAL-467)

CAL-467 Upgrade camel to 2.22.0 (#628)

---

distribution/docs/src/main/resources/content/_reference/_applicationReferences/mg-ic-security.adoc
distribution/docs/src/main/resources/content/_reference/_applicationReferences/mg-imaging.adoc
distribution/docs/src/main/resources/content/_reference/_applicationReferences/mg-nsili.adoc
distribution/docs/src/main/resources/content/_reference/_applicationReferences/mg-video.adoc

**Port to `master` of PR https://github.com/codice/alliance/pull/631**
Copy edits to documentation application reference sections.
@clockard
@lessarderic
@shaundmorris
content changes only.

CAL-291 copy edits to sources and applications docs (#631) 

---

catalog/imaging/imaging-actionprovider-chip/pom.xml
catalog/imaging/imaging-plugin-nitf/pom.xml
catalog/imaging/imaging-postprocess-plugin-nitf/pom.xml
catalog/imaging/imaging-service-impl/pom.xml
catalog/imaging/imaging-transformer-chipping/pom.xml
catalog/imaging/pom.xml
catalog/nsili/catalog-nsili-common/pom.xml
catalog/nsili/catalog-nsili-endpoint/pom.xml
catalog/nsili/catalog-nsili-source/pom.xml
catalog/nsili/catalog-nsili-sourcestoquery-ui/pom.xml
catalog/nsili/catalog-nsili-transformer/pom.xml
catalog/video/video-admin-plugin/pom.xml
catalog/video/video-mpegts-stream/pom.xml
catalog/video/video-mpegts-transformer/pom.xml
distribution/alliance-branding-plugin/pom.xml
distribution/alliance/pom.xml
distribution/docs/pom.xml
distribution/sdk/pom.xml
distribution/sdk/sample-mpegts-streamgenerator/pom.xml
distribution/sdk/sample-nsili-client/pom.xml
distribution/sdk/sample-nsili-server/pom.xml
distribution/test/itests/test-itests-alliance/pom.xml
distribution/test/itests/test-itests-dependencies-app/pom.xml
distribution/test/itests/test-itests-dependencies-app/src/main/filtered-resources/features.xml
libs/klv/pom.xml
libs/stanag4609/pom.xml
pom.xml

Added Codice-Parent as the parent project to Alliance. Removed pom properties that are also defined in the Codice-Parent pom. Also adjusted poms to utilize property replacement where possible. Some minor pre-existing pom issues cleaned up as well.
@garrettfreibott @austinsteffes @ahoffer @ricklarsen @shaundmorris @pklinef @clockard @djblue @lessarderic @coyotesqrl
Build, install and run to ensure compilation and runtime dependencies are satisfied. 
This is part of an effort to move dependency management to a centralized location. We will need to evaluate dependencies that are using other versions that what is specified in the parent pom and justify or update them as needed. 
[CAL-455](https://codice.atlassian.net/browse/CAL-455)
These changes are dependent on the following PR: …

CAL-455 Removed redundant pom properties

---

distribution/docs/src/test/java/alliance/docs/DocumentationTest.java

updates documentation unit test to be platform independent
@clockard
@lessarderic
@shaundmorris
builds successfully, and test passes.

CAL-291 improvement to docs test

---

distribution/alliance/pom.xml
distribution/docs/src/main/resources/content/_reference/_dependency-list/alliance-dependency-list.adoc

Upgrades to Karaf 4.2.0
@emmberk @blen-desta 
@clockard
@coyotesqrl 
[CAL-472](https://codice.atlassian.net/browse/CAL-472)

CAL-472 Upgraded to Karaf 4.2.0

---

distribution/common/src/main/resources/etc/profiles/ha.json

The name of a feature was updated in DDF in https://github.com/codice/ddf/pull/3790. This PR makes the same update in Alliance.
@peterhuffer @kcover @brjeter 
@clockard
@vinamartin
Confirm that the `catalog-admin-poller-service` feature is successfully installed with Alliance on first start-up using the `feature:list` command in the Karaf console.
The update to the feature name addresses some tech debt where the naming was inconsistent for the admin-poller-service bundle.
[CAL-474](https://codice.atlassian.net/browse/CAL-474)

CAL-474 Updated ha profile for updated feature name catalog-admin-poller-service

---

distribution/docs/src/test/java/alliance/docs/DocumentationTest.java

**PORT to `master` of PR [642](https://github.com/codice/alliance/pull/642)**
updates documentation unit test to be platform independent
@clockard
@lessarderic
@shaundmorris
builds successfully, and test passes.

CAL-291 improvement to docs test (#642)

---

catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/AbstractNitfMetacardType.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/common/TreDescriptor.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/complex/CmetaaAttribute.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/complex/CmetaaAttributeTest.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/gmti/GmtiMetacardTypeTest.java
catalog/imaging/imaging-transformer-nitf/src/test/java/org/codice/alliance/transformer/nitf/image/ImageMetacardTypeTest.java
pom.xml

Add support for the NITF CMETAA TRE.
@ryeats 
@dcruver 
@clockard
@jlcsmith 
This needs to be built with this imaging-nitf PR: [IMG-244 PR#190](https://github.com/codice/imaging-nitf/pull/190)
Ingest a NITF with a CMETAA TRE
Verify that the metacard has the "ext.nitf.cmetaa.*" attributes
[CAL-436](https://codice.atlassian.net/browse/CAL-436)
[IMG-244](https://codice.atlassian.net/browse/IMG-244)

[1.1.x] CAL-436 Add CMETAA TRE Support

---

catalog/imaging/imaging-actionprovider-chip/pom.xml
catalog/imaging/imaging-plugin-nitf/pom.xml
catalog/imaging/imaging-postprocess-plugin-nitf/pom.xml
catalog/security/banner-marking/pom.xml
pom.xml

It relocates various generic test and maven utilities to codice-test and codice-maven repositories.
@AzGoalie 
@figliold
@tbatie 
@codice/build 
@codice/test 
@coyotesqrl
@lessarderic
* successful PR build should be sufficient
[DDF-4166](https://codice.atlassian.net/browse/DDF-4166)
[CAL-473](https://codice.atlassian.net/browse/CAL-473)
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or …

CAL-473 Relocate test and maven utilities to other repos

---

distribution/alliance/pom.xml
distribution/docs/src/main/resources/content/_dependency-list/alliance-dependency-list.adoc
pom.xml

Link to master PR: #641 (merged to master first to maintain stability of the Alliance 1.1.2 release)
@emmberk @blen-desta 
@clockard
@coyotesqrl 
[CAL-472](https://codice.atlassian.net/browse/CAL-472)

[1.1.x]CAL-472 Upgraded to Karaf 4.2.0

---

pom.xml

[1.1.x]CAL-472 Update DDF version

---

catalog/imaging/imaging-actionprovider-chip/pom.xml
catalog/nsili/catalog-nsili-common/pom.xml
catalog/nsili/catalog-nsili-endpoint/pom.xml

Updates Alliance based on https://github.com/codice/ddf/pull/3842
@kcover @emmberk @clockard 
@coyotesqrl
@vinamartin
Full build.
[CAL-477](https://codice.atlassian.net/browse/CAL-477)

CAL-477 Declare dependencies that were received transitively

---

distribution/docs/pom.xml
distribution/docs/src/main/resources/content/_integrating/_endpoints/nsili-endpoint.adoc
distribution/docs/src/main/resources/content/integrating.adoc

updates documentation templates to publish a standalone integrator's guide. 
@mcalcote @garrettfreibott @ahoffer @austinsteffes 
@clockard
@lessarderic
@shaundmorris
Builds successfully and produces `integrating.html`
[DDF-3888](https://codice.atlassian.net/browse/DDF-3888)
[CAL-448](https://codice.atlassian.net/browse/CAL-448)

CAL-448 updated docs templates for standalone integrator docs

---

pom.xml

@mcalcote @blen-desta @brjeter
@clockard
@coyotesqrl
@stustison

CAL-479 update ddf-parent to 1.0.1

---

catalog/video/video-mpegts-stream/src/test/java/org/codice/alliance/video/stream/mpegts/SimpleSubject.java

Fixes the build by making SimpleSubject override getName.
@ethantmanns @KalCramer 
@clockard
@coyotesqrl
Build passes
[CAL-480](https://codice.atlassian.net/browse/CAL-480)

CAL-480 Updated SimpleSubject to override getName

---

distribution/docs/src/test/java/alliance/docs/DocumentationTest.java

updates documentation unit test to be more specific in the error text used to determine if a template error has occurred. 
@ahoffer @austinsteffes @garrettfreibott 
@clockard
@coyotesqrl
@lessarderic
@rzwiefel
@shaundmorris
builds successfully and test passes.
[DDF-4194](https://codice.atlassian.net/browse/DDF-4194)

CAL-291 update to documentation unit test

---

catalog/video/video-mpegts-stream/src/test/java/org/codice/alliance/video/stream/mpegts/SimpleSubject.java

**ABBREVIATED REVIEW BETWEEN 2.13.X AND MASTER IS IN EFFECT**
**This should be merged after the [DDF backport](https://github.com/codice/ddf/pull/3908) is merged**
Prevents the build from failing after https://github.com/codice/ddf/pull/3908 is merged by overriding getName in SimpleSubject.
@AzGoalie 
@ethantmanns 
@KalCramer 
@clockard 
@coyotesqrl 
Build passes
[CAL-480](https://codice.atlassian.net/browse/CAL-480)

[1.1.x] CAL-480 Updated SimpleSubject to override getName

---

distribution/docs/src/main/resources/content/_reference/_dependency-list/alliance-dependency-list.adoc
distribution/test/itests/pom.xml
distribution/test/itests/test-itests-common/pom.xml
pom.xml

Upstream PR: https://github.com/codice/ddf/pull/3884
@blen-desta @bakejeyner @emmberk
@clockard
@coyotesqrl 
[CAL-481](https://codice.atlassian.net/browse/CAL-481)

CAL-481 Upgrade to Karaf 4.2.1

---

distribution/docs/src/main/resources/content/_dependency-list/alliance-dependency-list.adoc
distribution/test/itests/pom.xml
distribution/test/itests/test-itests-common/pom.xml
pom.xml

Link to master PR: #658 
**Note:** The second commit is new and is specific to the release branch.
@emmberk @bakejeyner  @blen-desta 
@clockard
@coyotesqrl 
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before …

[1.1.x] CAL-481 Upgrade to Karaf 4.2.1

---

catalog/imaging/imaging-app/src/main/resources/features.xml
distribution/common/src/main/resources/common-bin.xml
distribution/common/src/main/resources/etc/profiles/ha.json
pom.xml

- Fix the features themselves to declare their dependencies
- Include the additional dependencies in the ha profile for maintenance purposes
- Removes some features/bundles that no longer exist
@Kjames5269  @paouelle 
@coyotesqrl 
@figliold 
- Install with the HA profile: `profile:install ha`
- Install with the standard profile via both the UI and CLI
[CAL-490](https://codice.atlassian.net/browse/CAL-490)

[1.1.x]CAL-490 Fix the HA installation profile

---

pom.xml

Link to master PR (DDF since no Alliance changes were needed on master because of DDF-Parent): https://github.com/codice/ddf/pull/3807 
Updates various dependencies. There are some minor incompatibilities between CXF 3.2.5 and Karaf 4.2.1 in downstream projects that this fixes.
@emmberk @blen-desta 
@clockard
@coyotesqrl 
[CAL-495](https://codice.atlassian.net/browse/CAL-495)

[1.1.x]CAL-495 updated cxf, camel, http, and shiro

---

ThreatDragonModels/ImagingApp/ImagingApp.json
ThreatDragonModels/NSILI/NSILI.json
ThreatDragonModels/README.md
ThreatDragonModels/VideoApp/VideoApp.json

See the screenshots on this PR for the diagrams.
@Kjames5269 @blen-desta 
@coyotesqrl 
@shaundmorris
@stustison 
[CAL-492](https://codice.atlassian.net/browse/CAL-492)
Video App:
NSILI:
Imaging App:

CAL-492 Convert existing threat models to Threat Dragon format

---

Jenkinsfile

- Simplifies CI workspace name
- Performs post-build cleanup to mitigate container reuse issues, like disk capacity
@oconnormi 
@clockard
@shaundmorris 
Tested using jenkins-test instance -- contact for URL
[CAL-497](https://codice.atlassian.net/browse/CAL-497?atlOrigin=eyJpIjoiMWNhZjliNzM2MzlkNDQwZDkyODhiNzJjZWU1MTFlY2IiLCJwIjoiaiJ9)

CAL-497 Simplify CI workspace name and perform post-build cleanup

---

PULL_REQUEST_TEMPLATE

Anybody
@coyotesqrl 
@shaundmorris 
[CAL-500](https://codice.atlassian.net/browse/CAL-500)

[1.1.x]CAL-500 Adding brjeter as a committer to the PR template

---

.github/PULL_REQUEST_TEMPLATE

Anybody
@coyotesqrl 
@shaundmorris 
[CAL-500](https://codice.atlassian.net/browse/CAL-500)

CAL-500 Adding brjeter as a committer to the PR template

---

ThreatDragonModels/ImagingApp/ImagingApp.json

Updates and completes the threat model for the Imaging App.
@bakejeyner @dcruver @SmithJosh 
@brjeter
@stustison
No testing is required short of ensuring that the model can be opened in [Threat Dragon](https://github.com/mike-goodwin/owasp-threat-dragon-desktop) on Windows and Mac (and on Github as well with the webapp if desired).
A screenshot has been provided for a quick once-over but the model should be reviewed in the application for thoroughness.
[CAL-499](https://codice.atlassian.net/browse/CAL-499)

CAL-499 Imaging App threat model

---

.github/PULL_REQUEST_TEMPLATE

Adds threat dragon models to checklist in PR template
@stustison 
@rzwiefel 
@codice/security 
@shaundmorris 
@coyotesqrl 
[CAL-500](https://codice.atlassian.net/browse/CAL-500)

CAL-500 Add threat dragon to checklist in PR template

---

pom.xml

Updates DDF version for release.
@emmberk @peterhuffer 
@brjeter 
@vinamartin
CI Build

Update DDF version

---

catalog/imaging/imaging-plugin-nitf/src/main/java/org/codice/alliance/plugin/nitf/NitfPostIngestPlugin.java
catalog/imaging/imaging-plugin-nitf/src/test/java/org/codice/alliance/plugin/nitf/NitfPostIngestPluginTest.java
catalog/imaging/imaging-postprocess-plugin-nitf/src/main/java/org/codice/alliance/plugin/nitf/NitfPostProcessPlugin.java
catalog/imaging/imaging-postprocess-plugin-nitf/src/test/groovy/org/codice/alliance/plugin/nitf/NitfPostProcessPluginSpec.groovy
catalog/imaging/imaging-service-impl/pom.xml
catalog/imaging/imaging-service-impl/src/main/java/org/codice/alliance/imaging/chip/service/impl/ChipServiceImpl.java
catalog/imaging/imaging-service-impl/src/test/java/org/codice/alliance/imaging/chip/service/impl/ChipServiceImplTest.java
catalog/imaging/imaging-transformer-chipping/src/main/java/org/codice/alliance/imaging/chip/transformer/CatalogOutputAdapter.java
catalog/imaging/imaging-transformer-chipping/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/imaging/imaging-transformer-chipping/src/test/java/org/codice/alliance/imaging/chip/transformer/CatalogOutputAdapterTest.java
catalog/video/video-security/src/test/java/org/codice/alliance/video/security/validator/videographer/VideographerValidatorTest.java
distribution/alliance/pom.xml

@brjeter
@coyotesqrl
@stustison 
@tbatie 

CAL-502 restricted the number of threads allowed to do NITF operations

---

catalog/imaging/imaging-actionprovider-chip/pom.xml
catalog/imaging/imaging-plugin-nitf/pom.xml
catalog/imaging/imaging-postprocess-plugin-nitf/pom.xml
catalog/security/banner-marking/pom.xml
pom.xml

Link to master PRs: #649 and #676 
It relocates various generic test and maven utilities to codice-test and codice-maven repositories.
@AzGoalie
@figliold
@tbatie
@peterhuffer 
@coyotesqrl
@lessarderic
@clockard 
successful PR build should be sufficient
[CAL-473](https://codice.atlassian.net/browse/CAL-473)
[CAL-498](https://codice.atlassian.net/browse/CAL-498)

[1.1.x] CAL-473 - Port of test dependency changes from master 

---

catalog/nsili/catalog-nsili-endpoint/pom.xml
distribution/docs/src/main/resources/content/_reference/_dependency-list/alliance-dependency-list.adoc
pom.xml

Note: Needed in order for Alliance to run on Java11.
@emmberk @Lambeaux 
@vinamartin  
@coyotesqrl 
[CAL-503](https://codice.atlassian.net/browse/CAL-503)
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before …

CAL-503 Upgrade to Karaf 4.2.2

---

catalog/video/video-mpegts-transformer/src/main/java/org/codice/alliance/transformer/video/MpegTsInputTransformer.java
catalog/video/video-mpegts-transformer/src/test/java/org/codice/alliance/transformer/video/MpegTsInputTransformerTest.java

Link to 1.1.x PR: #695 
@tyler30clemens @austinsteffes 
@emmberk @jrnorth 
[CAL-506](https://codice.atlassian.net/browse/CAL-506)

CAL-506 Update MpegTsInputTransformer to set media type to video/mp2t

---

distribution/docs/src/main/resources/content/_integrating/_endpoints/nsili-endpoint.adoc
distribution/docs/src/main/resources/content/_managing/_configuring/configuring-nsili-endpoint.adoc

Reformats documentation for NSILI endpoint to match content outline inherited from these changes to templates: https://github.com/codice/ddf/pull/4382
@bakejeyner @austinsteffes @garrettfreibott 
@brjeter
@clockard
@lessarderic
@shaundmorris
These changes are primarily structural. Future rewrites of individual sections will follow on from this work.
[CAL-551](https://codice.atlassian.net/browse/CAL-551)
[DDF-04331](https://github.com/codice/ddf/pull/4382)
[CAL-511-docs-revised.zip](https://github.com/codice/alliance/files/2866856/CAL-511-docs-revised.zip)

CAL-511 updated docs for NSILI endpoint

---

dependency-check-maven-config.xml
distribution/docs/src/main/resources/content/_dependency-list/alliance-dependency-list.adoc

fixes incorrect document type in dependency list docs. 
@ahoffer @bakejeyner @blen-desta @garrettfreibott 
@clockard
@lessarderic
@shaundmorris
builds successfully with dependency list included. 

CAL-291 fixed typo in dependency list docs

---

pom.xml

Bumping DDF version in order to run CI before releasing Alliance.
@ahoffer @clockard

[1.1.x]Update DDF version to 2.13.8

---

pom.xml

Updates the ddf version to 2.15.0-SNAPSHOT
@clockard 
@Bdthomson 
@shaundmorris 
@brjeter 
@rzwiefel 
(probably need this one in before https://github.com/codice/ddf/pull/4565)
CI Build
Fixes: https://github.com/codice/alliance/issues/712

CAL-0712 Update to next dev version

---

catalog/video/video-app/src/main/resources/features.xml
distribution/common/src/main/resources/etc/profiles/ha.json

~https://github.com/codice/ddf/pull/4677 will need to be merged before this is merged.~ Merged.
-----
validationparser is now definitionparser. there were two names that needed to be updated. 
@tbatie @glenhein @jordanwilking anyoneelse
build https://github.com/codice/ddf/pull/4677 and then ensure alliance builds and starts on top of it. 
https://github.com/codice/ddf/pull/4677

DDF-4675 Updated links to renamed validation parser

---

catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/NsiliEndpoint.java
catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/netty/RawUdpDataToMTSPacketDecoder.java
catalog/video/video-security/src/main/java/org/codice/alliance/video/security/token/videographer/VideographerAuthenticationToken.java
catalog/video/video-security/src/main/java/org/codice/alliance/video/security/validator/videographer/VideographerValidator.java
catalog/video/video-security/src/main/resources/OSGI-INF/blueprint/blueprint.xml
catalog/video/video-security/src/main/resources/OSGI-INF/metatype/metatype.xml
catalog/video/video-security/src/test/java/org/codice/alliance/video/security/token/videographer/VideographerAuthenticationTokenTest.java
catalog/video/video-security/src/test/java/org/codice/alliance/video/security/validator/videographer/VideographerValidatorTest.java
distribution/test/itests/test-itests-alliance/src/test/java/org/codice/alliance/test/itests/BannerMarkingsTest.java
distribution/test/itests/test-itests-alliance/src/test/java/org/codice/alliance/test/itests/ImagingTest.java
distribution/test/itests/test-itests-alliance/src/test/java/org/codice/alliance/test/itests/NsiliEndpointTest.java
distribution/test/itests/test-itests-alliance/src/test/java/org/codice/alliance/test/itests/NsiliSourceTest.java
distribution/test/itests/test-itests-alliance/src/test/java/org/codice/alliance/test/itests/VideoTest.java

Fixes alliance issues that will arise from the removal of realms from the Web Context Policy Manager by https://github.com/codice/ddf/pull/4620
@bakejeyner 
@stustison
Test that everything still works as expected.
See: https://github.com/codice/ddf/pull/4620
For GH Issues:
Fixes: https://github.com/codice/ddf/issues/4481

DDF-04481 Removed realm support from the Web Context Policy Manager

---

pom.xml

Updated DDF Snapshot Version
@bdeining
@beyelerb
@brjeter
@clockard
@coyotesqrl
@figliold
@jaymcnallie
@jlcsmith
@kcwire
@lessarderic
@millerw8
@mrmateo
@pklinef
@rzwiefel
@shaundmorris
@stustison
@tbatie
@vinamartin
Build

Updated DDF Snapshot Version

---

distribution/docs/src/main/resources/content/_metadataReference/NITF_Header-table.adoc

Updates NITF translations in documentation
@roelens8 @emmberk @brjeter @austinsteffes @tyler30clemens 
@brjeter
Build docs and look at results.
The hero should verify if the descriptions actually match what is in the code.
This work was triggered by PR #542
[CAL-722]

CAL-722 Update NITF translations in documentation

---

catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/metacard/LineStringMetacardUpdater.java
catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/plugins/FrameCenterUpdateField.java
catalog/video/video-mpegts-stream/src/test/java/org/codice/alliance/video/stream/mpegts/plugins/FrameCenterUpdateFieldTest.java
catalog/video/video-mpegts-transformer/src/main/resources/OSGI-INF/blueprint/blueprint.xml
distribution/test/itests/test-itests-alliance/src/test/java/org/codice/alliance/test/itests/VideoTest.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/FrameCenterKlvProcessor.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/GeometryUtility.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/LocationKlvProcessor.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/NonEmptyGeometryOperator.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/FrameCenterKlvProcessorTest.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/GeometryUtilityTest.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/LocationKlvProcessorTest.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/NonEmptyGeometryOperatorTest.java

Do not store empty geometries in the metacard.
@jlcsmith
@rzwiefel
https://github.com/codice/alliance/issues/721

CAL-721 Do not store empty geometries generated by video

---

pom.xml

DDF Version
@bdeining
@beyelerb
@brjeter
@clockard
@coyotesqrl
@figliold
@jaymcnallie
@jlcsmith
@kcwire
@lessarderic
@millerw8
@mrmateo
@pklinef
@rzwiefel
@shaundmorris
@stustison
@tbatie
@vinamartin

DDF Version

---

catalog/nsili/catalog-nsili-sourcestoquery-ui/Gruntfile.js
catalog/nsili/catalog-nsili-sourcestoquery-ui/package.json
catalog/nsili/catalog-nsili-sourcestoquery-ui/pom.xml
catalog/nsili/catalog-nsili-sourcestoquery-ui/src/main/resources/index.html
catalog/nsili/catalog-nsili-sourcestoquery-ui/src/main/webapp/js/application.js
catalog/nsili/catalog-nsili-sourcestoquery-ui/src/main/webapp/js/ich.js
catalog/nsili/catalog-nsili-sourcestoquery-ui/src/main/webapp/js/module.js
catalog/nsili/catalog-nsili-sourcestoquery-ui/src/main/webapp/js/view/Modal.js
catalog/nsili/catalog-nsili-sourcestoquery-ui/src/main/webapp/js/view/SourcesToQuery.view.js
catalog/nsili/catalog-nsili-sourcestoquery-ui/src/main/webapp/main.js
catalog/nsili/catalog-nsili-sourcestoquery-ui/yarn.lock
catalog/video/video-admin-plugin/Gruntfile.js
catalog/video/video-admin-plugin/package.json
catalog/video/video-admin-plugin/pom.xml
catalog/video/video-admin-plugin/src/main/resources/index.html
catalog/video/video-admin-plugin/src/main/webapp/js/application.js
catalog/video/video-admin-plugin/src/main/webapp/js/ich.js
catalog/video/video-admin-plugin/src/main/webapp/js/module.js
catalog/video/video-admin-plugin/src/main/webapp/js/view/Modal.js
catalog/video/video-admin-plugin/src/main/webapp/js/view/StreamMonitor.view.js
catalog/video/video-admin-plugin/src/main/webapp/main.js
catalog/video/video-admin-plugin/yarn.lock
catalog/video/video-mpegts-stream/src/main/resources/OSGI-INF/blueprint/blueprint.xml

Clean cherry-pick of  https://github.com/codice/alliance/pull/730
@Kjames5269 @austinsteffes @tyler30clemens 
@adimka 
@bdeining
@troymohl 
#729

[1.3.x]CAL-0729 Fixes NSILI and Video Admin Apps and removes unused webjars

---

catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/metacard/LineStringMetacardUpdater.java
catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/plugins/FrameCenterUpdateField.java
catalog/video/video-mpegts-stream/src/test/java/org/codice/alliance/video/stream/mpegts/plugins/FrameCenterUpdateFieldTest.java
catalog/video/video-mpegts-transformer/src/main/resources/OSGI-INF/blueprint/blueprint.xml
distribution/test/itests/test-itests-alliance/src/test/java/org/codice/alliance/test/itests/VideoTest.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/FrameCenterKlvProcessor.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/GeometryUtility.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/LocationKlvProcessor.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/NonEmptyGeometryOperator.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/FrameCenterKlvProcessorTest.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/GeometryUtilityTest.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/LocationKlvProcessorTest.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/NonEmptyGeometryOperatorTest.java

Backport of https://github.com/codice/alliance/pull/720 (clean cherry-pick)
@austinsteffes @tyler30clemens @Kjames5269 
@bdeining
@jlcsmith
#721

[1.3.x]CAL-721 Do not store empty geometries generated by video

---

catalog/nsili/catalog-nsili-sourcestoquery-ui/package.json
catalog/video/video-admin-plugin/package.json

Updates lodash to version 4.17.15
@bellcc 
@vinamartin 
@bdeining
@jlcsmith
Full build and verify UI functions normally
[Alliance-736](https://github.com/codice/alliance/issues/736)

CAL-736 Update lodash version

---

pom.xml

Update to DDF version 2.18.0-SNAPSHOT, as 2.17.0-SNAPSHOT is no longer available.
@shaundmorris 
@bdeining 
@bdeining
@jlcsmith
@millerw8

Update to DDF version 2.18.0-SNAPSHOT

---

catalog/nsili/catalog-nsili-sourcestoquery-ui/yarn.lock
catalog/video/video-admin-plugin/yarn.lock

Updates yarn locks from lodash change
@beyelerb
Build should sufcice

CAL-0729 Update yarn locks

---

catalog/video/video-mpegts-transformer/src/main/resources/OSGI-INF/blueprint/blueprint.xml
libs/klv/src/main/java/org/codice/alliance/libs/klv/AlphanumericDistinctKlvProcessor.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/SecurityReleasingInstructionsKlvProcessor.java
libs/klv/src/main/java/org/codice/alliance/libs/klv/Utilities.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/UtilitiesTest.java

port of https://github.com/codice/alliance/pull/742
@brjeter @brendan-hofmann

CAL-734 add none check on specific mpeg transformers

---

catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/SubmitStandingQueryRequestImplTest.java
pom.xml

@bdeining
@beyelerb
@brjeter
@clockard
@coyotesqrl
@figliold
@jaymcnallie
@jlcsmith
@kcwire
@lessarderic
@millerw8
@mrmateo
@pklinef
@rzwiefel
@shaundmorris
@stustison
@tbatie
@vinamartin

CAL-0725 DDF parent

---

pom.xml

@bdeining
@beyelerb
@brjeter
@clockard
@coyotesqrl
@figliold
@jaymcnallie
@jlcsmith
@kcwire
@lessarderic
@millerw8
@mrmateo
@pklinef
@rzwiefel
@shaundmorris
@stustison
@tbatie
@vinamartin

Using DDF snapshot development version

---

pom.xml

@bdeining
@beyelerb
@brjeter
@clockard
@coyotesqrl
@figliold
@jaymcnallie
@jlcsmith
@kcwire
@lessarderic
@millerw8
@mrmateo
@pklinef
@rzwiefel
@shaundmorris
@stustison
@tbatie
@vinamartin

using DDF development version

---

pom.xml

Bumps the DDF version. 
@brianfelix 
@bdeining
@shaundmorris

Fix DDF version from 2.19.0-SNAPSHOT to 2.20.0-SNAPSHOT

---

catalog/nsili/nsili-app/src/main/resources/features.xml
distribution/sdk/sample-content-metadata-extractor/pom.xml
distribution/test/itests/test-itests-dependencies-app/src/main/filtered-resources/features.xml
pom.xml

See https://github.com/codice/alliance/pull/744
@brianfelix 
@bdeining
@stustison

[1.5.x] Upgrade Guava to 25.1

---

distribution/test/itests/test-itests-alliance/src/test/java/org/codice/alliance/test/itests/VideoTest.java

Replaced WaitCondition with Awaitility
@brjeter
@pklinef
@shaundmorris

CAL-756 Replaced WaitCondition with Awaitility

---

catalog/nsili/nsili-app/src/main/resources/features.xml
distribution/sdk/sample-content-metadata-extractor/pom.xml
distribution/test/itests/test-itests-dependencies-app/src/main/filtered-resources/features.xml
pom.xml

See https://github.com/codice/alliance/pull/744
@brianfelix 
@bdeining
@stustison

[1.6.x] Upgrade Guava to 25.1

---

Jenkinsfile

Updates the Jenkinsfile to better match what was happening in the "old style" jobs we used before.
This is part of an effort to move off of free style jobs in Jenkins and use pipelines instead. 
@shaundmorris 
@TonyMorrison 
@LinkMJB 
A successful build should happen on this pr in the Alliance multibranch pipeline job. 
N/A
#763
Master build using this Jenkinsfile

CAL-763 Updated the Jenkinsfile 

---

catalog/ddms/catalog-ddms-transformer/src/test/java/org/codice/alliance/ddms/v2/Ddms20InputTransformerTest.java

Fix Gml3ToWkt broken from upstream changes
@jrnorth 
@millerw8
@rzwiefel
Build

[1.6.x] Fix Gml3ToWkt broken from upstream changes

---

Jenkinsfile

Added in commenting to the pull request with build start and end notices.
@TonyMorrison 
@LinkMJB 
@shaundmorris 
Build should pass with notifications.
#763

CAL-763: Pull request notifications in Jenkinsfile

---

Jenkinsfile

Added in commenting to the pull request with build start and end notices. (#766)
Also, broke up the incremental and full build into multiple shell calls
to make seeing how long a step took visible.
(cherry picked from commit f3a4568e45715da85e065f262c9c07e2ba79a2c7)
@shaundmorris 
@LinkMJB 
@TonyMorrison 
A build should run and post back to the PR
#763

Backport 766 to 1.8.x

---

Jenkinsfile
pom.xml

(cherry picked from commit babd791)
See #762
Includes the update from #766
@TonyMorrison
@LinkMJB
@shaundmorris
#763

Backport 766 to 1.6.x

---

Jenkinsfile
pom.xml

See #762
@TonyMorrison 
@LinkMJB 
@shaundmorris 
#763

Back port 766 to 1.5.x

---

Jenkinsfile
pom.xml

CAL-763 Updated the Jenkinsfile to better match what was happening in the "old style" jobs we used before. (#1) (#762)
See #762
@TonyMorrison 
@LinkMJB 
@shaundmorris 
#763

Backport 1.4.x

---

Jenkinsfile
pom.xml

See #762
@TonyMorrison 
@LinkMJB 
@shaundmorris 
#763

Backport 766 to 1.3.x

---

Jenkinsfile
pom.xml

See #762
@TonyMorrison 
@LinkMJB 
@shaundmorris 
#763

Backport 766 to 1.2.x

---

Jenkinsfile
pom.xml

See #762
@TonyMorrison 
@LinkMJB 
@shaundmorris 
#763

Backport 766 to 1.1.x

---

Jenkinsfile

See #762
@TonyMorrison 
@LinkMJB 
@shaundmorris 
#763

Backport 766 to 1.7.x

---

pom.xml

Upgrades to DDF 2.20.0-SNAPSHOT
@bdeining
@beyelerb
@brjeter
@clockard
@coyotesqrl
@figliold
@jlcsmith
@jrnorth 
@lessarderic
@millerw8
@pklinef
@rzwiefel
@shaundmorris
@stustison
@vinamartin
Build passes
DDF 2.21.0 was released
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codice/alliance/778)

Upgrade to DDF 2.22.0-SNAPSHOT

---

catalog/nsili/catalog-nsili-source/pom.xml

Fixes starting nsili-app and itests
@pklinef 
@codice/build 
@codice/test 
@bdeining
@brjeter
Run itests/passing build
Statup Alliance -> Start NSILI App
#780 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codice/alliance/781)

CAL-780 embedded gson-support into nsili-source to fix startup/itests

---

pom.xml

Upgrades to DDF 2.13.10
@bdeining
@beyelerb
@brjeter
@clockard
@coyotesqrl
@figliold 
@jlcsmith
@kcwire
@lessarderic
@millerw8
@pklinef
@rzwiefel
@shaundmorris
@stustison
@vinamartin
Build passes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codice/alliance/779)

Upgrade to DDF 2.13.10

---

catalog/nsili/catalog-nsili-endpoint/pom.xml
catalog/video/video-security/pom.xml
catalog/video/video-security/src/main/java/org/codice/alliance/video/security/videographer/realm/VideographerRealm.java
distribution/docs/src/main/resources/content/_reference/_dependencyList/alliance-dependency-list.adoc

Just updates to use with DDF master
@shaundmorris
@stustison
Run full build.

CAL-784 updated to work with the STS and IdP removal

---

catalog/imaging/imaging-postprocess-plugin-nitf/src/main/java/org/codice/alliance/plugin/nitf/NitfPostProcessPlugin.java

Fixed SonarCloud finding of having not enough arguments. 
https://sonarcloud.io/project/issues?id=org.codice%3Aalliance&issues=AWTAnHm0xXt_iLiSlTNx&open=AWTAnHm0xXt_iLiSlTNx
@oconnormi 
@glenhein 
@brjeter
@clockard
@figliold
Build passes, analysis of the debug statement
#782 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codice/alliance/783)

CAL-782 fixed NitfPostProcessPlugin debug statement

---

distribution/docs/src/main/resources/content/_managing/_installing/cal-setup-types.adoc

Removes link from documentation
@bdeining
@rzwiefel
@shaundmorris

CAL-291 removed broken link in Alliance documentation

---

catalog/nsili/catalog-nsili-endpoint/src/main/java/org/codice/alliance/nsili/endpoint/NsiliEndpoint.java
catalog/security/banner-marking/src/main/java/org/codice/alliance/security/banner/marking/BannerCommonMarkingExtractor.java
catalog/security/banner-marking/src/main/java/org/codice/alliance/security/banner/marking/Dod520001MarkingExtractor.java
catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/netty/RawUdpDataToMTSPacketDecoder.java
distribution/test/itests/test-itests-alliance/pom.xml

Removes checks for expired tokens.
@SmithJosh @bakejeyner 
@blen-desta 
@coyotesqrl 
@pklinef
@stustison

CAL-784 removed expired token checks

---

distribution/test/itests/test-itests-common/src/main/java/org/codice/alliance/test/itests/common/AbstractAllianceIntegrationTest.java
pom.xml

@bdeining
@beyelerb
@brjeter
@clockard
@coyotesqrl
@figliold
@jaymcnallie
@jlcsmith
@kcwire
@lessarderic
@millerw8
@mrmateo
@pklinef
@rzwiefel
@shaundmorris
@stustison
@tbatie
@vinamartin

[1.6.x] released version of DDF

---

catalog/nsili/catalog-nsili-endpoint/src/test/java/org/codice/alliance/nsili/endpoint/requests/OrderRequestImplTest.java

Just ignoring a single unit test. Initial glance looks like the issue really isn't specific to the one test, but in how the mocks are setup
@codice/test 
@AdamBurstynski 
@AzGoalie 
@pklinef 
Run unit tests
Trying out to handle flaky tests
#767 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codice/alliance/768)

CAL-767 Ignore flaky testMultipleTarCompressOrder

---

catalog/nsili/catalog-nsili-endpoint/pom.xml
catalog/nsili/catalog-nsili-source/pom.xml
catalog/video/video-mpegts-stream/pom.xml
distribution/alliance/src/main/filtered-resources/etc/org.codice.ddf.admin.applicationlist.properties
distribution/install-profiles/src/main/resources/features.xml
distribution/sdk/sample-nsili-client/pom.xml
distribution/sdk/sample-nsili-server/pom.xml
distribution/test/itests/test-itests-common/pom.xml
distribution/test/itests/test-itests-common/src/main/java/org/codice/alliance/test/itests/common/AbstractAllianceIntegrationTest.java
pom.xml

@SmithJosh @bakejeyner 
@blen-desta 
@pklinef
@shaundmorris
@stustison

CAL-795 upgrade plugins used in Alliance and point to new ddf-parent

---

catalog/nsili/catalog-nsili-source/pom.xml
pom.xml

This PR updates the versions of CXF, Camel, Netty, and Commons Lang
@mdang8
@rfding
@josephthweatt
@clockard
@stustison

Updating Dependency Versions

---

.github/stale.yml

Adds Stalebot to auto manage issues and PRs
@codice/ddf-contributors 
@Lambeaux 
No changes to build or runtime functionality
Helps manage obsolete issues and PRs
#805 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codice/alliance/806)

CAL-805 Added Stalebot Config for issues and PRs

---

Jenkinsfile
pom.xml

Upgraded the version of Maven to 'maven-latest' in the Jenkinsfile. Accordingly the pom was modified, with the ddf-parent upgraded to 1.0.10, and codice-maven to 0.3
Also added using an image pre-loaded with .m2 dependency cache and error trapping for cleanup routine at the end 
@shaundmorris 
@LinkMJB 
@paouelle 
@bdeining
@shaundmorris
http://jenkins.phx.connexta.com/service/jenkins/job/W.I.P./job/alliance_TM/job/master/
BR-42 Upgrade Maven version
https://octoconsulting.atlassian.net/jira/software/projects/BR/boards/47?selectedIssue=BR-42

BR-42 Upgrade Maven version

---

pom.xml

Upgrades jRuby dependency for documentation module
@codice/build 
@codice/docs 
@clockard
@mcalcote
@shaundmorris
Documentation module builds as expected

CAL-409 upgraded jruby dependency for docs module

---

Jenkinsfile
distribution/docker/alliance/pom.xml
distribution/docker/alliance/src/main/docker/Dockerfile
distribution/docker/alliance/src/main/docker/files.xml
distribution/docker/pom.xml
distribution/pom.xml
pom.xml

Adds docker image for alliance
@LinkMJB @AdamBurstynski 
@shaundmorris @clockard 
Run a build
Initially the images will only be built when running the build on linux. There will be future changes to support building the images from any OS

Add Alliance Docker Image

---

catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/rollover/CatalogRolloverAction.java
catalog/video/video-mpegts-stream/src/test/java/org/codice/alliance/video/stream/mpegts/plugins/RolloverStreamCreationPluginTest.java
catalog/video/video-security/src/main/resources/OSGI-INF/blueprint/blueprint.xml
distribution/alliance/pom.xml
distribution/alliance/src/main/filtered-resources/etc/org.apache.karaf.features.cfg
pom.xml

The purpose of this PR is help anticipate how changes to DDF will affect Alliance. This should help us be better prepared for the next DDF. We do not expect to merge this PR while it point to DDF Snapshot.
@bdeining
@beyelerb
@brjeter
@clockard
@coyotesqrl
@figliold
@jaymcnallie
@jlcsmith
@kcwire
@lessarderic
@millerw8
@mrmateo
@pklinef
@rzwiefel
@shaundmorris
@stustison
@tbatie
@vinamartin

CAL-XXXX upgrade to DDF 2.25.0

---

pom.xml

upgrades asciidoctor dependency from version 1.5.6 to 1.6.2
@clockard
@shaundmorris
@mcalcote 
builds successfully
relies on https://github.com/codice/ddf/pull/6119

CAL-410 upgraded asciidoctor dependency

---

pom.xml

Checks for local NVD (on mariadb) for dependency check instead of the Central NVD
@LinkMJB 
@jrnorth 
@bdeining
@shaundmorris
Should pass dependency check stage
This is was originally done in DDF to resolve the same issue
BR-123 Update Dependency check for local NVD

BR-123 Update dependency check for local NVD

---

catalog/video/video-mpegts-stream/pom.xml
catalog/video/video-mpegts-transformer/pom.xml
libs/klv/pom.xml

Gets Alliance (video-app) to start
@codice/test 
@jrnorth 
Alliance starts-up, itests pass
I'm not sure what caused this issue in the first place. Couldn't track an exact commit where this was introduced around June 24th. Could use feedback on the small change. Should we make the change optional, exclude it, or is there a better option?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codice/alliance/831)

Fixed Alliance video-app startup

---

distribution/install-profiles/src/main/resources/features.xml
pom.xml

Updates to DDF 2.25.1
Removes experimental profile
@rzwiefel 
@bdeining 
@rzwiefel 
@bdeining 

Update to DDF 2.25.1

---

pom.xml

Updates to DDF2.25.2-SNAPSHOT
@blen-desta @bakejeyner 
@shaundmorris
@stustison
CI
Needed by downstream project
none
- [n/a] Documentation Updated
- [n/a] Update / Add Threat Dragon models
- [n/a] Update / Add Unit Tests
- [n/a] Update / Add Integration Tests

Update to DDF 2.25.2-SNAPSHOT

---

catalog/imaging/imaging-plugin-nitf/src/main/java/org/codice/alliance/plugin/nitf/NitfPostIngestPlugin.java

@blen-desta 
@bakejeyner 
@emmberk 
@stustison
https://github.com/codice/alliance/issues/841

[1.13.x] CAL-841 added null check to resource size

---

catalog/imaging/imaging-plugin-nitf/pom.xml
catalog/imaging/imaging-plugin-nitf/src/main/java/org/codice/alliance/plugin/nitf/NitfPostIngestPlugin.java
catalog/imaging/imaging-plugin-nitf/src/test/java/org/codice/alliance/plugin/nitf/NitfPostIngestPluginTest.java

Port of https://github.com/codice/alliance/pull/842 + a unit test
@stustison @blen-desta @bakejeyner @garrettfreibott 
No hero needed. This is tested in CI.
Fixes: #841
- [n/a] Documentation Updated
- [n/a] Update / Add Threat Dragon models

CAL-841 added null check to resource size

---

libs/klv/src/test/java/org/codice/alliance/libs/klv/KlvUtilities.java
libs/klv/src/test/java/org/codice/alliance/libs/klv/Stanag4609ProcessorImplTest.java
libs/stanag4609/src/main/java/org/codice/alliance/libs/stanag4609/Stanag4609TransportStreamParser.java

Corresponding change for https://github.com/codice/ddf/pull/6304. This fixes the build.
@blen-desta @bakejeyner @garrettfreibott @stustison 
CI

[1.13.x] Update Klv.KeyLength constant names

---

pom.xml

Upgrades to DDF parent 1.0.11 and dependency-check 6.0.2
@emmberk 
@SmithJosh 
@TonyMorrison 
@AdamBurstynski 
@LinkMJB 
@codice/security 
@codice/build 
Successful build with the dependency-check stage (owasp profile) passing.
https://github.com/codice/ddf/pull/6354
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codice/alliance/860)

Upgraded to ddf-parent 1.0.11, dependency-check 6.0.2

---

catalog/video/video-mpegts-stream/src/main/resources/OSGI-INF/metatype/metatype.xml
distribution/docs/src/main/resources/content/_reference/_tables/UdpStreamMonitor.adoc

Port to master of: https://github.com/codice/alliance/pull/866
@kcover 
@josephthweatt 
@ricklarsen 
@jrnorth 
@clockard

Update docs about chunk frames when streaming video

---

catalog/video/video-app/pom.xml
catalog/video/video-app/src/main/resources/features.xml

forward port of: #872 
@aj-brooks 
@jrnorth 
@clockard
@pklinef

fwd Create video-core feature 

---

Jenkinsfile

Upgrades Sonar to use JDK 11. 8 will not supported as of next month
@TonyMorrison 
@LinkMJB 
@Lambeaux 
Build passes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codice/alliance/879)

Upgraded Sonar Analysis to use JDK 11

---

Jenkinsfile
pom.xml

Updating the Maven plugin to the maven-latest, allowing the deploy to function properly. 
Also updated the deploy and release plugins
@shaundmorris 
@LinkMJB 
@clockard
@shaundmorris

[1.6.x] BR-159 Update Alliance 1.6.x to maven-latest

---

libs/stanag4609/src/main/java/org/codice/alliance/libs/stanag4609/Stanag4609TransportStreamParser.java

Fixes SonarCloud minor bugs dealing with Long operations.
https://sonarcloud.io/project/issues?id=org.codice%3Aalliance&resolved=false&severities=MINOR&types=BUG#
https://sonarcloud.io/organizations/codice/rules?open=java%3AS2184&rule_key=java%3AS2184
@kentmorrissey 
@abel-connexta 
@jMoneee 
@zta6 
@gordocanchola 
@AzGoalie 
Successful build. Open to other ideas on it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codice/alliance/891)

Fix SonarCloud minor bugs

---

Jenkinsfile

Runs Sonar only on master branch. The current free tier can only support one branch at a time.
@TonyMorrison 
@Lambeaux 
@andrewzimmer 
@codice/build 
Build passes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codice/alliance/888)

Run Sonar only on master branch

---

catalog/core/catalog-email-impl/src/main/java/org/codice/alliance/core/email/impl/EmailSenderImpl.java
catalog/imaging/imaging-actionprovider-chip/src/main/java/org/codice/alliance/imaging/chip/actionprovider/ImagingChipActionProvider.java
catalog/imaging/imaging-transformer-nitf/src/main/java/org/codice/alliance/transformer/nitf/gmti/NitfGmtiTransformer.java
catalog/video/video-admin-plugin/src/main/java/org/codice/alliance/video/ui/service/StreamMonitorHelper.java
catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/StreamMonitorException.java
catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/UdpStreamMonitor.java
catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/rollover/CatalogRolloverAction.java

Fixes issues identified by SonarCloud here 
https://sonarcloud.io/project/issues?id=org.codice%3Aalliance&resolved=false&severities=MAJOR&types=BUG
Also fixed some other SonarCloud small findings in the classes changed.
@kentmorrissey
@lavoywj
@frnkshin
@hayleynorton
@jMoneee
@shaundmorris
@zta6 
Full build should be sufficient

SonarCloud Code Cleanup Major Bugs findings 8

---

catalog/imaging/imaging-transformer-chipping/src/main/java/org/codice/alliance/imaging/chip/transformer/CatalogOutputAdapter.java
catalog/security/banner-marking/src/main/java/org/codice/alliance/security/banner/marking/BannerMarkings.java
catalog/security/banner-marking/src/main/java/org/codice/alliance/security/banner/marking/BannerValidator.java
catalog/security/banner-marking/src/main/java/org/codice/alliance/security/banner/marking/PortionMarkings.java

Fixes issues identified by SonarCloud here 
https://sonarcloud.io/project/issues?id=org.codice%3Aalliance&resolved=false&rules=java%3AS1192&severities=CRITICAL 
@kentmorrissey
@lavoywj
@frnkshin
@hayleynorton
@jMoneee
@shaundmorris
@zta6 
Full build should be sufficient

SonarCloud findings - create constants for repeated string literals

---

pom.xml

Upgrades to latest version of ddf-parent 
@pklinef
@shaundmorris
Tested using quick build and executing dependency check on the project

ddf-parent upgrade

---

catalog/security/banner-marking/src/main/java/org/codice/alliance/security/banner/marking/BannerMarkings.java
catalog/security/banner-marking/src/test/groovy/org/codice/alliance/security/banner/marking/BannerMarkingsSpec.groovy
catalog/security/banner-marking/src/test/groovy/org/codice/alliance/security/banner/marking/PortionMarkingsSpec.groovy

Forward port of https://github.com/codice/alliance/pull/901

Support concealed FGI

---

pom.xml

Upgrades Alliance 1.6.x to use DDF 2.19.23 release
@kcwire @jrnorth 
@vinamartin @kcwire @jrnorth 

[1.6.x] Upgrade to DDF 2.19.23

---

pom.xml

Updates Alliance to DDF 2.19.24
@jrnorth @kcwire 
@jrnorth @kcwire 
n/a

Updates Alliance to DDF 2.19.24

---

catalog/imaging/imaging-nitf-impl/pom.xml
catalog/nsili/catalog-nsili-endpoint/pom.xml
pom.xml

Upgrade to DDF 2.19.25
@kcwire 
@pklinef 
@jrnorth 
@millerw8 
@kcwire 
@pklinef 
@jrnorth 
@millerw8 

Upgrade to DDF 2.19.25

---

pom.xml

Upgrade to DDF 2.19.26
anyone
anyone

[1.6.x] Upgrade to DDF 2.19.26

---

catalog/video/video-mpegts-stream/pom.xml
catalog/video/video-mpegts-stream/src/main/java/org/codice/alliance/video/stream/mpegts/UdpStreamMonitor.java
catalog/video/video-mpegts-stream/src/test/java/org/codice/alliance/video/stream/mpegts/UdpStreamMonitorTest.java

Forward port of https://github.com/codice/alliance/pull/962
@clockard 
@glenhein

Fix UdpStreamMonitor update callback to set all properties

---

pom.xml

Was originally changed to fix builds on Apple Silicon but does not work with CI

Downgrades Node back to previous version

---

catalog/imaging/imaging-transformer-nitf/src/main/resources/OSGI-INF/blueprint/blueprint.xml

Forward port of: https://github.com/codice/alliance/pull/961

[Forward Port] Add missing nitf metacard types
